import { useDesktopI18n } from '../i18n.js';
import type { DesktopLocaleId } from '../i18n/keys.js';
import type { IndependentScope } from '../independent-contracts.js';
import type { IndependentAssistantController } from '../independent-assistant-controller.js';
import { useSpaceAssistantStore } from '../stores/useSpaceAssistantStore.js';
import { IndependentAssistantReset, type AssistantResetLabels } from './IndependentAssistantReset.js';

type Copy = Omit<AssistantResetLabels, 'fieldNames' | 'runStates'>;
export const assistantResetCopy: Record<DesktopLocaleId, Copy> = {
  en: { title:'Assistant history and reset', choose:'Choose the change', clearInterview:'Delete interview history', resetAssistant:'Reset this Space Assistant', preview:'Review impact', confirm:'Confirm the reviewed change', busy:'Working…', cancel:'Cancel', removed:'Will be removed', preserved:'Will be preserved', interviewMessages:'Interview messages', conversationMessages:'Conversation messages', answers:'Answer records', cachedStates:'Cached states', draftFields:'Interview draft fields', currentProfileFields:'Current profile fields', keptProfileFields:'Preserved profile fields', snapshots:'Run profile snapshots', snapshotEvidence:'Snapshots retaining interview evidence', definitions:'Agent definitions', runs:'Existing runs', connections:'Connection bindings', schedules:'Schedules', unchangedAccess:'Permissions, access bindings, existing runs and schedules remain unchanged.', noSecureErasure:'This deletes active records. It does not guarantee secure erasure from storage or remove evidence already captured by runs.', empty:'None', enabled:'Enabled', disabled:'Disabled', applied:'The reviewed change was applied.', failed:'The change could not be applied. Reload the Assistant status.', stalePreview:'The impact changed. Review it again before confirming.' },
  de: { title:'Assistant-Verlauf und Zurücksetzen', choose:'Änderung auswählen', clearInterview:'Interviewverlauf löschen', resetAssistant:'Assistant dieses Space zurücksetzen', preview:'Auswirkungen prüfen', confirm:'Geprüfte Änderung bestätigen', busy:'Wird bearbeitet…', cancel:'Abbrechen', removed:'Wird entfernt', preserved:'Bleibt erhalten', interviewMessages:'Interviewnachrichten', conversationMessages:'Gesprächsnachrichten', answers:'Antwortdatensätze', cachedStates:'Zwischengespeicherte Zustände', draftFields:'Felder des Interviewentwurfs', currentProfileFields:'Aktuelle Profilfelder', keptProfileFields:'Erhaltene Profilfelder', snapshots:'Profilsnapshots der Läufe', snapshotEvidence:'Snapshots mit Interviewbelegen', definitions:'Agentendefinitionen', runs:'Bestehende Läufe', connections:'Verbindungsbindungen', schedules:'Zeitpläne', unchangedAccess:'Berechtigungen, Zugriffsbindungen, bestehende Läufe und Zeitpläne bleiben erhalten.', noSecureErasure:'Aktive Datensätze werden gelöscht. Dies garantiert keine sichere Löschung auf dem Datenträger und entfernt keine bereits von Läufen übernommenen Belege.', empty:'Keine', enabled:'Aktiviert', disabled:'Deaktiviert', applied:'Die geprüfte Änderung wurde angewendet.', failed:'Die Änderung konnte nicht angewendet werden. Assistant-Status erneut laden.', stalePreview:'Die Auswirkungen haben sich geändert. Vor der Bestätigung erneut prüfen.' },
  es: { title:'Historial y reinicio del Assistant', choose:'Elige el cambio', clearInterview:'Eliminar historial de entrevista', resetAssistant:'Reiniciar el Assistant de este espacio', preview:'Revisar efectos', confirm:'Confirmar el cambio revisado', busy:'Procesando…', cancel:'Cancelar', removed:'Se eliminará', preserved:'Se conservará', interviewMessages:'Mensajes de entrevista', conversationMessages:'Mensajes de conversación', answers:'Registros de respuestas', cachedStates:'Estados en caché', draftFields:'Campos del borrador de entrevista', currentProfileFields:'Campos del perfil actual', keptProfileFields:'Campos del perfil conservados', snapshots:'Copias del perfil de ejecución', snapshotEvidence:'Copias con pruebas de entrevista', definitions:'Definiciones de agentes', runs:'Ejecuciones existentes', connections:'Vínculos de conexión', schedules:'Programaciones', unchangedAccess:'Se conservan los permisos, los vínculos de acceso, las ejecuciones y las programaciones existentes.', noSecureErasure:'Se eliminan los registros activos. No garantiza un borrado seguro del almacenamiento ni elimina pruebas ya capturadas por las ejecuciones.', empty:'Ninguno', enabled:'Activado', disabled:'Desactivado', applied:'Se aplicó el cambio revisado.', failed:'No se pudo aplicar el cambio. Recarga el estado del Assistant.', stalePreview:'Los efectos han cambiado. Revísalos antes de confirmar.' },
  fr: { title:'Historique et réinitialisation de l’Assistant', choose:'Choisir la modification', clearInterview:'Supprimer l’historique de l’entretien', resetAssistant:'Réinitialiser l’Assistant de cet espace', preview:'Examiner les effets', confirm:'Confirmer la modification examinée', busy:'Traitement…', cancel:'Annuler', removed:'Sera supprimé', preserved:'Sera conservé', interviewMessages:'Messages d’entretien', conversationMessages:'Messages de conversation', answers:'Réponses enregistrées', cachedStates:'États en cache', draftFields:'Champs du brouillon d’entretien', currentProfileFields:'Champs du profil actuel', keptProfileFields:'Champs du profil conservés', snapshots:'Copies du profil des exécutions', snapshotEvidence:'Copies conservant les preuves de l’entretien', definitions:'Définitions des agents', runs:'Exécutions existantes', connections:'Liaisons de connexion', schedules:'Planifications', unchangedAccess:'Les autorisations, les liaisons d’accès, les exécutions et les planifications existantes sont conservées.', noSecureErasure:'Les enregistrements actifs sont supprimés. Cela ne garantit pas leur effacement sécurisé du stockage et ne supprime pas les preuves déjà capturées par les exécutions.', empty:'Aucun', enabled:'Activé', disabled:'Désactivé', applied:'La modification examinée a été appliquée.', failed:'La modification n’a pas pu être appliquée. Rechargez l’état de l’Assistant.', stalePreview:'Les effets ont changé. Examinez-les à nouveau avant de confirmer.' },
  it: { title:'Cronologia e ripristino dell’Assistant', choose:'Scegli la modifica', clearInterview:'Elimina la cronologia del colloquio', resetAssistant:'Ripristina l’Assistant di questo spazio', preview:'Verifica gli effetti', confirm:'Conferma la modifica verificata', busy:'Elaborazione…', cancel:'Annulla', removed:'Verrà eliminato', preserved:'Verrà conservato', interviewMessages:'Messaggi del colloquio', conversationMessages:'Messaggi della conversazione', answers:'Risposte registrate', cachedStates:'Stati nella cache', draftFields:'Campi della bozza del colloquio', currentProfileFields:'Campi del profilo attuale', keptProfileFields:'Campi del profilo conservati', snapshots:'Copie del profilo delle esecuzioni', snapshotEvidence:'Copie con prove del colloquio', definitions:'Definizioni degli agenti', runs:'Esecuzioni esistenti', connections:'Associazioni delle connessioni', schedules:'Pianificazioni', unchangedAccess:'Restano invariati permessi, associazioni di accesso, esecuzioni e pianificazioni esistenti.', noSecureErasure:'Vengono eliminati i record attivi. Non garantisce una cancellazione sicura dal disco né elimina prove già acquisite dalle esecuzioni.', empty:'Nessuno', enabled:'Abilitato', disabled:'Disabilitato', applied:'La modifica verificata è stata applicata.', failed:'Impossibile applicare la modifica. Ricarica lo stato dell’Assistant.', stalePreview:'Gli effetti sono cambiati. Verificali di nuovo prima di confermare.' },
  'pt-BR': { title:'Histórico e redefinição do Assistant', choose:'Escolha a alteração', clearInterview:'Excluir histórico da entrevista', resetAssistant:'Redefinir o Assistant deste espaço', preview:'Revisar impactos', confirm:'Confirmar a alteração revisada', busy:'Processando…', cancel:'Cancelar', removed:'Será removido', preserved:'Será preservado', interviewMessages:'Mensagens da entrevista', conversationMessages:'Mensagens da conversa', answers:'Registros de respostas', cachedStates:'Estados em cache', draftFields:'Campos do rascunho da entrevista', currentProfileFields:'Campos do perfil atual', keptProfileFields:'Campos do perfil preservados', snapshots:'Cópias do perfil das execuções', snapshotEvidence:'Cópias com evidências da entrevista', definitions:'Definições de agentes', runs:'Execuções existentes', connections:'Vínculos de conexão', schedules:'Agendamentos', unchangedAccess:'Permissões, vínculos de acesso, execuções e agendamentos existentes são preservados.', noSecureErasure:'Os registros ativos são excluídos. Não garante uma exclusão segura do armazenamento nem remove evidências já capturadas pelas execuções.', empty:'Nenhum', enabled:'Ativado', disabled:'Desativado', applied:'A alteração revisada foi aplicada.', failed:'Não foi possível aplicar a alteração. Recarregue o status do Assistant.', stalePreview:'Os impactos mudaram. Revise novamente antes de confirmar.' },
  ru: { title:'История и сброс Assistant', choose:'Выберите изменение', clearInterview:'Удалить историю интервью', resetAssistant:'Сбросить Assistant этого пространства', preview:'Проверить последствия', confirm:'Подтвердить проверенное изменение', busy:'Обработка…', cancel:'Отмена', removed:'Будет удалено', preserved:'Будет сохранено', interviewMessages:'Сообщения интервью', conversationMessages:'Сообщения беседы', answers:'Записи ответов', cachedStates:'Кэшированные состояния', draftFields:'Поля черновика интервью', currentProfileFields:'Поля текущего профиля', keptProfileFields:'Сохраняемые поля профиля', snapshots:'Снимки профиля запусков', snapshotEvidence:'Снимки с данными интервью', definitions:'Определения агентов', runs:'Существующие запуски', connections:'Привязки подключений', schedules:'Расписания', unchangedAccess:'Разрешения, привязки доступа, существующие запуски и расписания сохраняются.', noSecureErasure:'Удаляются активные записи. Это не гарантирует безопасное стирание с диска и не удаляет данные, уже сохранённые запусками.', empty:'Нет', enabled:'Включено', disabled:'Отключено', applied:'Проверенное изменение применено.', failed:'Не удалось применить изменение. Обновите состояние Assistant.', stalePreview:'Последствия изменились. Проверьте их ещё раз перед подтверждением.' },
  ja: { title:'Assistant の履歴とリセット', choose:'変更内容を選択', clearInterview:'インタビュー履歴を削除', resetAssistant:'このスペースの Assistant をリセット', preview:'影響を確認', confirm:'確認した変更を適用', busy:'処理中…', cancel:'キャンセル', removed:'削除される内容', preserved:'保持される内容', interviewMessages:'インタビューのメッセージ', conversationMessages:'会話のメッセージ', answers:'回答の記録', cachedStates:'キャッシュされた状態', draftFields:'インタビュー下書きの項目', currentProfileFields:'現在のプロファイル項目', keptProfileFields:'保持するプロファイル項目', snapshots:'実行時のプロファイルのコピー', snapshotEvidence:'インタビューの根拠を保持するコピー', definitions:'エージェントの定義', runs:'既存の実行', connections:'接続の関連付け', schedules:'スケジュール', unchangedAccess:'権限、アクセスの関連付け、既存の実行とスケジュールは保持されます。', noSecureErasure:'有効な記録を削除します。ストレージからの安全な消去や、実行がすでに取得した根拠の削除を保証するものではありません。', empty:'なし', enabled:'有効', disabled:'無効', applied:'確認した変更を適用しました。', failed:'変更を適用できませんでした。Assistant の状態を更新してください。', stalePreview:'影響が変わりました。適用前にもう一度確認してください。' },
};

export function IndependentResetSection({ scope, revision, controller }: { scope: IndependentScope; revision: number; controller: IndependentAssistantController }): React.JSX.Element {
  const { t, locale } = useDesktopI18n(), copy = assistantResetCopy[locale];
  const labels: AssistantResetLabels = { ...copy,
    fieldNames: { purpose:t('spaceAssistant.purpose'), requestedHelp:t('spaceAssistant.help'), workingStyle:t('spaceAssistant.style'), backgroundPreferences:t('spaceAssistant.background') },
    runStates: Object.fromEntries((['queued','running','waiting_for_user','waiting_for_approval','pausing','paused','cancelling','cancelled','completed','failed','interrupted'] as const).map(state => [state, t(`spaceAssistant.${state}`)])) };
  return <details className="independent-reset-section"><summary>{copy.title}</summary>
    <IndependentAssistantReset scope={scope} expectedRevision={revision} labels={labels} onPreview={async (captured, payload) => {
      const result = await controller.request({ schemaVersion:1, operation:'assistantReset', scope:captured, payload });
      if (!result.ok || !('expectedRevision' in result.value)) throw new Error(copy.failed);
      return result.value;
    }} onApply={async (captured, payload) => {
      const result = await controller.request({ schemaVersion:1, operation:'assistantReset', scope:captured, payload });
      if (!result.ok || !('revision' in result.value)) throw new Error(copy.failed);
      if (payload.action === 'reset_assistant') useSpaceAssistantStore.getState().setComposer(captured, '');
      const refreshed = await controller.load(captured);
      if (!refreshed.ok) throw new Error(copy.failed);
    }} />
  </details>;
}
