import {describe,it,expect,vi} from 'vitest';
import{createTerminalSession,type TerminalEvent}from'../src/renderer/terminal-session';
function fixture(){let listener:(e:TerminalEvent)=>void=()=>{};const unsubscribe=vi.fn();const bridge={start:vi.fn(),close:vi.fn(async()=>({ok:true})),write:vi.fn(async()=>({ok:true})),onData:vi.fn((fn:any)=>{listener=fn;return unsubscribe;})};const output=vi.fn(),changed=vi.fn(),error=vi.fn();return{bridge,output,changed,error,unsubscribe,emit:(e:TerminalEvent)=>listener(e),session:createTerminalSession(bridge,output,changed,error)}}
describe('workspace terminal lifetime',()=>{
 it('closes a PTY whose start resolves after unmount',async()=>{const f=fixture();let resolve:any;f.bridge.start.mockReturnValue(new Promise(r=>resolve=r));const start=f.session.start({cwd:'A',mode:'shell'});await Promise.resolve();f.session.dispose();resolve({id:'late'});await start;expect(f.bridge.close).toHaveBeenCalledWith('late');expect(f.unsubscribe).toHaveBeenCalledOnce();});
 it('retains early output and passes raw ANSI without splitting',async()=>{const f=fixture();f.bridge.start.mockImplementation(async()=>{f.emit({id:'one',data:'\x1b[31mhel'});return{id:'one'}});await f.session.start({cwd:'A',mode:'shell'});f.emit({id:'one',data:'lo\r\n'});expect(f.output.mock.calls).toEqual([['\x1b[31mhel'],['lo\r\n']]);f.session.dispose();expect(f.bridge.close).toHaveBeenCalledWith('one');});
 it('rejects overlapping starts and closes replaced terminals',async()=>{const f=fixture();const resolvers:any[]=[];f.bridge.start.mockImplementation(()=>new Promise(r=>resolvers.push(r)));const first=f.session.start({cwd:'A',mode:'shell'});await Promise.resolve();const second=f.session.start({cwd:'B',mode:'shell'});await Promise.resolve();resolvers[0]({id:'old'});await first;resolvers[1]({id:'new'});await second;expect(f.bridge.close).toHaveBeenCalledWith('old');f.session.dispose();expect(f.bridge.close).toHaveBeenCalledWith('new');});
 it('clears the session on process exit',async()=>{const f=fixture();f.bridge.start.mockResolvedValue({id:'one'});await f.session.start({cwd:'A',mode:'shell'});f.emit({id:'one',exitCode:0});await f.session.write('x');expect(f.bridge.write).not.toHaveBeenCalled();expect(f.changed).toHaveBeenLastCalledWith('');});
});
