import type { PinnedApp } from './stores/usePinnedAppStore.js';

export interface CatalogApp extends PinnedApp {
  category: 'communication' | 'productivity' | 'developer' | 'media';
  description?: string;
}

export const TOP_64_PINNED_APPS: CatalogApp[] = [
  // --- 1. Communication & Messaging (13 apps) ---
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    url: 'https://web.whatsapp.com',
    category: 'communication',
    color: '#25d366',
    bg: 'rgba(37, 211, 102, 0.15)',
    letter: 'W',
    iconName: 'whatsapp',
    domain: 'whatsapp.com',
    description: 'Echtzeit-Messaging & Telefonie'
  },
  {
    id: 'discord',
    name: 'Discord',
    url: 'https://discord.com/app',
    category: 'communication',
    color: '#5865f2',
    bg: 'rgba(88, 101, 242, 0.15)',
    letter: 'D',
    iconName: 'discord',
    domain: 'discord.com',
    description: 'Community Voice- & Text-Channels'
  },
  {
    id: 'telegram',
    name: 'Telegram',
    url: 'https://web.telegram.org',
    category: 'communication',
    color: '#229ed9',
    bg: 'rgba(34, 158, 217, 0.15)',
    letter: 'T',
    iconName: 'telegram',
    domain: 'telegram.org',
    description: 'Cloudbasierter Messenger & Channels'
  },
  {
    id: 'signal',
    name: 'Signal',
    url: 'https://signal.org',
    category: 'communication',
    color: '#3a76f0',
    bg: 'rgba(58, 118, 240, 0.15)',
    letter: 'S',
    iconName: 'signal',
    domain: 'signal.org',
    description: 'Ende-zu-Ende verschlüsselter Messenger'
  },
  {
    id: 'slack',
    name: 'Slack',
    url: 'https://slack.com',
    category: 'communication',
    color: '#e01e5a',
    bg: 'rgba(224, 30, 90, 0.15)',
    letter: 'S',
    iconName: 'slack',
    domain: 'slack.com',
    description: 'Team-Chat & Kollaboration'
  },
  {
    id: 'gmail',
    name: 'Gmail',
    url: 'https://mail.google.com',
    category: 'communication',
    color: '#ea4335',
    bg: 'rgba(234, 67, 53, 0.15)',
    letter: 'M',
    iconName: 'gmail',
    domain: 'mail.google.com',
    description: 'Google E-Mail Postfach'
  },
  {
    id: 'outlook',
    name: 'Outlook',
    url: 'https://outlook.live.com',
    category: 'communication',
    color: '#0078d4',
    bg: 'rgba(0, 120, 212, 0.15)',
    letter: 'O',
    iconName: 'outlook',
    domain: 'outlook.live.com',
    description: 'Microsoft E-Mail & Kalender'
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    url: 'https://teams.microsoft.com',
    category: 'communication',
    color: '#6264a7',
    bg: 'rgba(98, 100, 167, 0.15)',
    letter: 'T',
    iconName: 'teams',
    domain: 'teams.microsoft.com',
    description: 'Enterprise Meetings & Chats'
  },
  {
    id: 'zoom',
    name: 'Zoom',
    url: 'https://zoom.us',
    category: 'communication',
    color: '#2d8cff',
    bg: 'rgba(45, 140, 255, 0.15)',
    letter: 'Z',
    iconName: 'zoom',
    domain: 'zoom.us',
    description: 'Video-Konferenzen & Webinare'
  },
  {
    id: 'meet',
    name: 'Google Meet',
    url: 'https://meet.google.com',
    category: 'communication',
    color: '#00897b',
    bg: 'rgba(0, 137, 123, 0.15)',
    letter: 'M',
    iconName: 'meet',
    domain: 'meet.google.com',
    description: 'Browserbasierte Video-Meetings'
  },
  {
    id: 'messenger',
    name: 'Messenger',
    url: 'https://www.messenger.com',
    category: 'communication',
    color: '#0099ff',
    bg: 'rgba(0, 153, 255, 0.15)',
    letter: 'M',
    iconName: 'messenger',
    domain: 'messenger.com',
    description: 'Meta Web-Messenger'
  },
  {
    id: 'skype',
    name: 'Skype Web',
    url: 'https://web.skype.com',
    category: 'communication',
    color: '#00aff0',
    bg: 'rgba(0, 175, 240, 0.15)',
    letter: 'S',
    iconName: 'skype',
    domain: 'skype.com',
    description: 'Voice- & Video-Anrufe'
  },
  {
    id: 'matrix',
    name: 'Element (Matrix)',
    url: 'https://app.element.io',
    category: 'communication',
    color: '#0dbd8b',
    bg: 'rgba(13, 189, 139, 0.15)',
    letter: 'E',
    iconName: 'element',
    domain: 'element.io',
    description: 'Dezentraler, sicherer Matrix-Chat'
  },

  // --- 2. Productivity & Workspaces (17 apps) ---
  {
    id: 'notion',
    name: 'Notion',
    url: 'https://www.notion.so',
    category: 'productivity',
    color: '#ffffff',
    bg: '#000000',
    letter: 'N',
    iconName: 'notion',
    domain: 'notion.so',
    description: 'All-in-One Notizen, Docs & Wikis'
  },
  {
    id: 'linear',
    name: 'Linear',
    url: 'https://linear.app',
    category: 'productivity',
    color: '#5e6ad2',
    bg: 'rgba(94, 106, 210, 0.15)',
    letter: 'L',
    iconName: 'linear',
    domain: 'linear.app',
    description: 'High-Speed Issue Tracker'
  },
  {
    id: 'trello',
    name: 'Trello',
    url: 'https://trello.com',
    category: 'productivity',
    color: '#0079bf',
    bg: 'rgba(0, 121, 191, 0.15)',
    letter: 'T',
    iconName: 'trello',
    domain: 'trello.com',
    description: 'Visuelle Kanban-Boards'
  },
  {
    id: 'figma',
    name: 'Figma',
    url: 'https://www.figma.com',
    category: 'productivity',
    color: '#f24e1e',
    bg: 'rgba(242, 78, 30, 0.15)',
    letter: 'F',
    iconName: 'figma',
    domain: 'figma.com',
    description: 'Kollaboratives UI/UX-Design'
  },
  {
    id: 'jira',
    name: 'Jira',
    url: 'https://www.atlassian.com/software/jira',
    category: 'productivity',
    color: '#0052cc',
    bg: 'rgba(0, 82, 204, 0.15)',
    letter: 'J',
    iconName: 'jira',
    domain: 'atlassian.com',
    description: 'Agiles Projektmanagement & Sprints'
  },
  {
    id: 'asana',
    name: 'Asana',
    url: 'https://app.asana.com',
    category: 'productivity',
    color: '#f06a6a',
    bg: 'rgba(240, 106, 106, 0.15)',
    letter: 'A',
    iconName: 'asana',
    domain: 'asana.com',
    description: 'Team-Aufgaben & Workflows'
  },
  {
    id: 'miro',
    name: 'Miro',
    url: 'https://miro.com',
    category: 'productivity',
    color: '#ffd02f',
    bg: 'rgba(255, 208, 47, 0.15)',
    letter: 'M',
    iconName: 'miro',
    domain: 'miro.com',
    description: 'Interaktives Whiteboard & Brainstorming'
  },
  {
    id: 'gdrive',
    name: 'Google Drive',
    url: 'https://drive.google.com',
    category: 'productivity',
    color: '#34a853',
    bg: 'rgba(52, 168, 83, 0.15)',
    letter: 'D',
    iconName: 'drive',
    domain: 'drive.google.com',
    description: 'Cloud-Speicher & Dokumente'
  },
  {
    id: 'gdocs',
    name: 'Google Docs',
    url: 'https://docs.google.com',
    category: 'productivity',
    color: '#4285f4',
    bg: 'rgba(66, 133, 244, 0.15)',
    letter: 'D',
    iconName: 'docs',
    domain: 'docs.google.com',
    description: 'Online-Textverarbeitung'
  },
  {
    id: 'gsheets',
    name: 'Google Sheets',
    url: 'https://sheets.google.com',
    category: 'productivity',
    color: '#0f9d58',
    bg: 'rgba(15, 157, 88, 0.15)',
    letter: 'S',
    iconName: 'sheets',
    domain: 'sheets.google.com',
    description: 'Tabellenkalkulation im Web'
  },
  {
    id: 'calendar',
    name: 'Google Calendar',
    url: 'https://calendar.google.com',
    category: 'productivity',
    color: '#4285f4',
    bg: 'rgba(66, 133, 244, 0.15)',
    letter: 'C',
    iconName: 'calendar',
    domain: 'calendar.google.com',
    description: 'Termine & Kalenderplanung'
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    url: 'https://app.clickup.com',
    category: 'productivity',
    color: '#7b68ee',
    bg: 'rgba(123, 104, 238, 0.15)',
    letter: 'C',
    iconName: 'clickup',
    domain: 'clickup.com',
    description: 'All-in-One Workplace Plattform'
  },
  {
    id: 'monday',
    name: 'Monday.com',
    url: 'https://monday.com',
    category: 'productivity',
    color: '#ff3d57',
    bg: 'rgba(255, 61, 87, 0.15)',
    letter: 'M',
    iconName: 'monday',
    domain: 'monday.com',
    description: 'Work OS & Projekt-Tracking'
  },
  {
    id: 'todoist',
    name: 'Todoist',
    url: 'https://app.todoist.com',
    category: 'productivity',
    color: '#e44332',
    bg: 'rgba(228, 67, 50, 0.15)',
    letter: 'T',
    iconName: 'todoist',
    domain: 'todoist.com',
    description: 'Aufgabenliste & Produktivitätsplaner'
  },
  {
    id: 'confluence',
    name: 'Confluence',
    url: 'https://www.atlassian.com/software/confluence',
    category: 'productivity',
    color: '#172b4d',
    bg: 'rgba(23, 43, 77, 0.15)',
    letter: 'C',
    iconName: 'confluence',
    domain: 'atlassian.com',
    description: 'Enterprise Team-Wiki & Knowledge Base'
  },
  {
    id: 'obsidian',
    name: 'Obsidian Publish',
    url: 'https://obsidian.md',
    category: 'productivity',
    color: '#8b5cf6',
    bg: 'rgba(139, 92, 246, 0.15)',
    letter: 'O',
    iconName: 'obsidian',
    domain: 'obsidian.md',
    description: 'Vernetzte Markdown-Notizen'
  },
  {
    id: 'ms365',
    name: 'Microsoft 365',
    url: 'https://www.office.com',
    category: 'productivity',
    color: '#d83b01',
    bg: 'rgba(216, 59, 1, 0.15)',
    letter: 'M',
    iconName: 'office',
    domain: 'office.com',
    description: 'Office Online Suite'
  },

  // --- 3. Developer & AI Tools (17 apps) ---
  {
    id: 'github',
    name: 'GitHub',
    url: 'https://github.com',
    category: 'developer',
    color: '#f0f6fc',
    bg: 'rgba(240, 246, 252, 0.12)',
    letter: 'G',
    iconName: 'github',
    domain: 'github.com',
    description: 'Code-Hosting, Pull Requests & Actions'
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    url: 'https://gitlab.com',
    category: 'developer',
    color: '#fc6d26',
    bg: 'rgba(252, 109, 38, 0.15)',
    letter: 'G',
    iconName: 'gitlab',
    domain: 'gitlab.com',
    description: 'DevOps & CI/CD Plattform'
  },
  {
    id: 'stackoverflow',
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    category: 'developer',
    color: '#f48024',
    bg: 'rgba(244, 128, 36, 0.15)',
    letter: 'S',
    iconName: 'stackoverflow',
    domain: 'stackoverflow.com',
    description: 'Entwickler-Q&A & Troubleshooting'
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chatgpt.com',
    category: 'developer',
    color: '#10a37f',
    bg: 'rgba(16, 163, 127, 0.15)',
    letter: 'C',
    iconName: 'chatgpt',
    domain: 'chatgpt.com',
    description: 'OpenAI Sprachmodell & Assistent'
  },
  {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    category: 'developer',
    color: '#d97706',
    bg: 'rgba(217, 119, 6, 0.15)',
    letter: 'C',
    iconName: 'claude',
    domain: 'claude.ai',
    description: 'Anthropic AI Coding & Deep Research'
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    url: 'https://www.perplexity.ai',
    category: 'developer',
    color: '#20b2aa',
    bg: 'rgba(32, 178, 170, 0.15)',
    letter: 'P',
    iconName: 'perplexity',
    domain: 'perplexity.ai',
    description: 'KI-gestützte Quellensuche'
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    url: 'https://huggingface.co',
    category: 'developer',
    color: '#ffd21e',
    bg: 'rgba(255, 210, 30, 0.15)',
    letter: 'H',
    iconName: 'huggingface',
    domain: 'huggingface.co',
    description: 'Open Source ML & AI Models Hub'
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    category: 'developer',
    color: '#4d6bfe',
    bg: 'rgba(77, 107, 254, 0.15)',
    letter: 'D',
    iconName: 'deepseek',
    domain: 'deepseek.com',
    description: 'Advanced Reasoning & Coding AI'
  },
  {
    id: 'vercel',
    name: 'Vercel Dashboard',
    url: 'https://vercel.com',
    category: 'developer',
    color: '#ffffff',
    bg: '#000000',
    letter: 'V',
    iconName: 'vercel',
    domain: 'vercel.com',
    description: 'Frontend Cloud & Edge Deployment'
  },
  {
    id: 'supabase',
    name: 'Supabase',
    url: 'https://supabase.com',
    category: 'developer',
    color: '#3ecf8e',
    bg: 'rgba(62, 207, 142, 0.15)',
    letter: 'S',
    iconName: 'supabase',
    domain: 'supabase.com',
    description: 'Open Source Firebase Alternative (Postgres)'
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare Dash',
    url: 'https://dash.cloudflare.com',
    category: 'developer',
    color: '#f38020',
    bg: 'rgba(243, 128, 32, 0.15)',
    letter: 'C',
    iconName: 'cloudflare',
    domain: 'cloudflare.com',
    description: 'DNS, CDN & Edge Security'
  },
  {
    id: 'aws',
    name: 'AWS Console',
    url: 'https://console.aws.amazon.com',
    category: 'developer',
    color: '#ff9900',
    bg: 'rgba(255, 153, 0, 0.15)',
    letter: 'A',
    iconName: 'aws',
    domain: 'aws.amazon.com',
    description: 'Amazon Web Services Cloud Console'
  },
  {
    id: 'gcp',
    name: 'Google Cloud Console',
    url: 'https://console.cloud.google.com',
    category: 'developer',
    color: '#4285f4',
    bg: 'rgba(66, 133, 244, 0.15)',
    letter: 'G',
    iconName: 'gcp',
    domain: 'cloud.google.com',
    description: 'GCP Cloud-Ressourcen'
  },
  {
    id: 'npm',
    name: 'npm registry',
    url: 'https://www.npmjs.com',
    category: 'developer',
    color: '#cb3837',
    bg: 'rgba(203, 56, 55, 0.15)',
    letter: 'N',
    iconName: 'npm',
    domain: 'npmjs.com',
    description: 'JavaScript Package Registry'
  },
  {
    id: 'docker',
    name: 'Docker Hub',
    url: 'https://hub.docker.com',
    category: 'developer',
    color: '#2496ed',
    bg: 'rgba(36, 150, 237, 0.15)',
    letter: 'D',
    iconName: 'docker',
    domain: 'docker.com',
    description: 'Container Image Registry'
  },
  {
    id: 'replit',
    name: 'Replit',
    url: 'https://replit.com',
    category: 'developer',
    color: '#f26207',
    bg: 'rgba(242, 98, 7, 0.15)',
    letter: 'R',
    iconName: 'replit',
    domain: 'replit.com',
    description: 'Cloud IDE & Online Compiler'
  },
  {
    id: 'postman',
    name: 'Postman Web',
    url: 'https://web.postman.co',
    category: 'developer',
    color: '#ff6c37',
    bg: 'rgba(255, 108, 55, 0.15)',
    letter: 'P',
    iconName: 'postman',
    domain: 'postman.co',
    description: 'API Design, Testing & Debugging'
  },

  // --- 4. Media, Social & Entertainment (17 apps) ---
  {
    id: 'youtube',
    name: 'YouTube',
    url: 'https://www.youtube.com',
    category: 'media',
    color: '#ff0000',
    bg: 'rgba(255, 0, 0, 0.15)',
    letter: 'Y',
    iconName: 'youtube',
    domain: 'youtube.com',
    description: 'Video-Streaming & Podcasts'
  },
  {
    id: 'spotify',
    name: 'Spotify',
    url: 'https://open.spotify.com',
    category: 'media',
    color: '#1db954',
    bg: 'rgba(29, 185, 84, 0.15)',
    letter: 'S',
    iconName: 'spotify',
    domain: 'spotify.com',
    description: 'Musik & Podcast Web-Player'
  },
  {
    id: 'netflix',
    name: 'Netflix',
    url: 'https://www.netflix.com',
    category: 'media',
    color: '#e50914',
    bg: 'rgba(229, 9, 20, 0.15)',
    letter: 'N',
    iconName: 'netflix',
    domain: 'netflix.com',
    description: 'Filme & Serien Streaming'
  },
  {
    id: 'twitch',
    name: 'Twitch',
    url: 'https://www.twitch.tv',
    category: 'media',
    color: '#9146ff',
    bg: 'rgba(145, 70, 255, 0.15)',
    letter: 'T',
    iconName: 'twitch',
    domain: 'twitch.tv',
    description: 'Live Gaming & Creative Streams'
  },
  {
    id: 'reddit',
    name: 'Reddit',
    url: 'https://www.reddit.com',
    category: 'media',
    color: '#ff4500',
    bg: 'rgba(255, 69, 0, 0.15)',
    letter: 'R',
    iconName: 'reddit',
    domain: 'reddit.com',
    description: 'Community Foren & Diskussionen'
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    url: 'https://x.com',
    category: 'media',
    color: '#ffffff',
    bg: 'rgba(255, 255, 255, 0.1)',
    letter: 'X',
    iconName: 'twitter',
    domain: 'x.com',
    description: 'Echtzeit-Nachrichten & Social Feed'
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    url: 'https://www.linkedin.com',
    category: 'media',
    color: '#0a66c2',
    bg: 'rgba(10, 102, 194, 0.15)',
    letter: 'L',
    iconName: 'linkedin',
    domain: 'linkedin.com',
    description: 'Berufliches Netzwerk & Jobs'
  },
  {
    id: 'instagram',
    name: 'Instagram',
    url: 'https://www.instagram.com',
    category: 'media',
    color: '#e1306c',
    bg: 'rgba(225, 48, 108, 0.15)',
    letter: 'I',
    iconName: 'instagram',
    domain: 'instagram.com',
    description: 'Foto & Video Social Media'
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    url: 'https://www.pinterest.com',
    category: 'media',
    color: '#e60023',
    bg: 'rgba(230, 0, 35, 0.15)',
    letter: 'P',
    iconName: 'pinterest',
    domain: 'pinterest.com',
    description: 'Visuelle Ideen & Moodboards'
  },
  {
    id: 'threads',
    name: 'Threads',
    url: 'https://www.threads.net',
    category: 'media',
    color: '#ffffff',
    bg: '#000000',
    letter: 'T',
    iconName: 'threads',
    domain: 'threads.net',
    description: 'Textbasiertes Social Network von Meta'
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud',
    url: 'https://soundcloud.com',
    category: 'media',
    color: '#ff5500',
    bg: 'rgba(255, 85, 0, 0.15)',
    letter: 'S',
    iconName: 'soundcloud',
    domain: 'soundcloud.com',
    description: 'Indie Musik & DJ Sets'
  },
  {
    id: 'deezer',
    name: 'Deezer',
    url: 'https://www.deezer.com',
    category: 'media',
    color: '#a238ff',
    bg: 'rgba(162, 56, 255, 0.15)',
    letter: 'D',
    iconName: 'deezer',
    domain: 'deezer.com',
    description: 'Musikstreaming & HiFi Audio'
  },
  {
    id: 'primevideo',
    name: 'Prime Video',
    url: 'https://www.primevideo.com',
    category: 'media',
    color: '#00a8e1',
    bg: 'rgba(0, 168, 225, 0.15)',
    letter: 'P',
    iconName: 'primevideo',
    domain: 'primevideo.com',
    description: 'Amazon Filme & Serien'
  },
  {
    id: 'disney',
    name: 'Disney+',
    url: 'https://www.disneyplus.com',
    category: 'media',
    color: '#113ccf',
    bg: 'rgba(17, 60, 207, 0.15)',
    letter: 'D',
    iconName: 'disney',
    domain: 'disneyplus.com',
    description: 'Disney, Marvel, Star Wars'
  },
  {
    id: 'applemusic',
    name: 'Apple Music',
    url: 'https://music.apple.com',
    category: 'media',
    color: '#fc3c44',
    bg: 'rgba(252, 60, 68, 0.15)',
    letter: 'A',
    iconName: 'applemusic',
    domain: 'music.apple.com',
    description: 'Apple Music Web Player'
  },
  {
    id: 'wikipedia',
    name: 'Wikipedia',
    url: 'https://www.wikipedia.org',
    category: 'media',
    color: '#ffffff',
    bg: '#202122',
    letter: 'W',
    iconName: 'wikipedia',
    domain: 'wikipedia.org',
    description: 'Freie Online-Enzyklopädie'
  },
  {
    id: 'gmaps',
    name: 'Google Maps',
    url: 'https://maps.google.com',
    category: 'media',
    color: '#34a853',
    bg: 'rgba(52, 168, 83, 0.15)',
    letter: 'M',
    iconName: 'maps',
    domain: 'maps.google.com',
    description: 'Karten, Routen & Satellitenbilder'
  }
];
