/**
 * GENERATED FILE — do not edit by hand.
 *
 * Source: the live Sidekick WebUI (FastAPI routes scan).
 * Regenerate with: npm --workspace apps/desktop run catalog:generate
 *
 * Endpoints: 418
 */
import type { LastbrowserPanelId } from './shell-state.js';

export type CatalogEndpoint = {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | '*';
  path: string;
  panel: LastbrowserPanelId;
  label: string;
  dangerous: boolean;
};

export const webuiEndpointCatalog: CatalogEndpoint[] = [
  { method: "*", path: "/api/agents", panel: "agents", label: "agents", dangerous: false },
  { method: "*", path: "/api/agents/activated", panel: "agents", label: "agents \\\\\\\\u00b7 activated", dangerous: false },
  { method: "*", path: "/api/agents/activities", panel: "agents", label: "agents \\\\\\\\u00b7 activities", dangerous: false },
  { method: "*", path: "/api/agents/create", panel: "agents", label: "agents \\\\\\\\u00b7 create", dangerous: false },
  { method: "*", path: "/api/agents/current", panel: "agents", label: "agents \\\\\\\\u00b7 current", dangerous: false },
  { method: "*", path: "/api/agents/list", panel: "agents", label: "agents \\\\\\\\u00b7 list", dangerous: false },
  { method: "*", path: "/api/agents/profiles", panel: "agents", label: "agents \\\\\\\\u00b7 profiles", dangerous: false },
  { method: "*", path: "/api/agents/splash/complete", panel: "agents", label: "agents \\\\\\\\u00b7 splash \\\\\\\\u00b7 complete", dangerous: false },
  { method: "*", path: "/api/agents/splash/question", panel: "agents", label: "agents \\\\\\\\u00b7 splash \\\\\\\\u00b7 question", dangerous: false },
  { method: "*", path: "/api/agents/splash/status", panel: "agents", label: "agents \\\\\\\\u00b7 splash \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/agents/stats", panel: "agents", label: "agents \\\\\\\\u00b7 stats", dangerous: false },
  { method: "*", path: "/api/agents/workspace", panel: "agents", label: "agents \\\\\\\\u00b7 workspace", dangerous: false },
  { method: "*", path: "/api/agents/workspace/stream", panel: "agents", label: "agents \\\\\\\\u00b7 workspace \\\\\\\\u00b7 stream", dangerous: false },
  { method: "*", path: "/api/agents/workspaces", panel: "agents", label: "agents \\\\\\\\u00b7 workspaces", dangerous: false },
  { method: "DELETE", path: "/api/dashboard/agent-plugins/{name}", panel: "agents", label: "DELETE dashboard · agent plugins · {name}", dangerous: true },
  { method: "POST", path: "/api/dashboard/agent-plugins/{name}/disable", panel: "agents", label: "POST dashboard · agent plugins · {name} · disable", dangerous: false },
  { method: "POST", path: "/api/dashboard/agent-plugins/{name}/enable", panel: "agents", label: "POST dashboard · agent plugins · {name} · enable", dangerous: false },
  { method: "POST", path: "/api/dashboard/agent-plugins/{name}/update", panel: "agents", label: "POST dashboard · agent plugins · {name} · update", dangerous: false },
  { method: "POST", path: "/api/dashboard/agent-plugins/install", panel: "agents", label: "POST dashboard · agent plugins · install", dangerous: true },
  { method: "*", path: "/api/nova/events", panel: "agents", label: "nova \\\\\\\\u00b7 events", dangerous: false },
  { method: "GET", path: "/api/nova/events", panel: "agents", label: "GET nova · events", dangerous: false },
  { method: "*", path: "/api/nova/personality", panel: "agents", label: "nova \\\\\\\\u00b7 personality", dangerous: false },
  { method: "GET", path: "/api/nova/personality", panel: "agents", label: "GET nova · personality", dangerous: false },
  { method: "*", path: "/api/nova/presence", panel: "agents", label: "nova \\\\\\\\u00b7 presence", dangerous: false },
  { method: "GET", path: "/api/nova/presence", panel: "agents", label: "GET nova · presence", dangerous: false },
  { method: "GET", path: "/api/nova/presence-card", panel: "agents", label: "GET nova · presence card", dangerous: false },
  { method: "*", path: "/api/nova/routes", panel: "agents", label: "nova \\\\\\\\u00b7 routes", dangerous: false },
  { method: "GET", path: "/api/nova/space-inventory", panel: "agents", label: "GET nova · space inventory", dangerous: false },
  { method: "*", path: "/api/nova/status", panel: "agents", label: "nova \\\\\\\\u00b7 status", dangerous: false },
  { method: "GET", path: "/api/nova/status", panel: "agents", label: "GET nova · status", dangerous: false },
  { method: "*", path: "/api/nova/voice-event", panel: "agents", label: "nova \\\\\\\\u00b7 voice event", dangerous: false },
  { method: "POST", path: "/api/nova/voice-event", panel: "agents", label: "POST nova · voice event", dangerous: false },
  { method: "*", path: "/api/nova/yolo", panel: "agents", label: "nova \\\\\\\\u00b7 yolo", dangerous: false },
  { method: "GET", path: "/api/nova/yolo", panel: "agents", label: "GET nova · yolo", dangerous: false },
  { method: "POST", path: "/api/nova/yolo", panel: "agents", label: "POST nova · yolo", dangerous: false },
  { method: "GET", path: "/api/space/nova-management", panel: "agents", label: "GET space · nova management", dangerous: false },
  { method: "POST", path: "/api/space/nova-management", panel: "agents", label: "POST space · nova management", dangerous: false },
  { method: "GET", path: "/api/space/nova-management/audit", panel: "agents", label: "GET space · nova management · audit", dangerous: false },
  { method: "*", path: "/api/subagents", panel: "agents", label: "subagents", dangerous: false },
  { method: "*", path: "/api/swarm", panel: "agents", label: "swarm", dangerous: false },
  { method: "*", path: "/api/swarm/models", panel: "agents", label: "swarm \\\\\\\\u00b7 models", dangerous: false },
  { method: "*", path: "/api/swarm/models/refresh", panel: "agents", label: "swarm \\\\\\\\u00b7 models \\\\\\\\u00b7 refresh", dangerous: false },
  { method: "*", path: "/api/swarm/packs", panel: "agents", label: "swarm \\\\\\\\u00b7 packs", dangerous: false },
  { method: "*", path: "/api/swarm/runs", panel: "agents", label: "swarm \\\\\\\\u00b7 runs", dangerous: false },
  { method: "*", path: "/api/swarm/supervisor/release-slot", panel: "agents", label: "swarm \\\\\\\\u00b7 supervisor \\\\\\\\u00b7 release slot", dangerous: false },
  { method: "*", path: "/api/appstore", panel: "appstore", label: "appstore", dangerous: false },
  { method: "*", path: "/api/appstore/install", panel: "appstore", label: "appstore \\\\\\\\u00b7 install", dangerous: true },
  { method: "*", path: "/api/appstore/sdk", panel: "appstore", label: "appstore \\\\\\\\u00b7 sdk", dangerous: false },
  { method: "*", path: "/api/appstore/space-toggle", panel: "appstore", label: "appstore \\\\\\\\u00b7 space toggle", dangerous: false },
  { method: "*", path: "/api/appstore/submit", panel: "appstore", label: "appstore \\\\\\\\u00b7 submit", dangerous: false },
  { method: "*", path: "/api/appstore/uninstall", panel: "appstore", label: "appstore \\\\\\\\u00b7 uninstall", dangerous: true },
  { method: "*", path: "/api/appstore/update-all", panel: "appstore", label: "appstore \\\\\\\\u00b7 update all", dangerous: false },
  { method: "*", path: "/api/appstore/updates", panel: "appstore", label: "appstore \\\\\\\\u00b7 updates", dangerous: false },
  { method: "*", path: "/api/browser/action", panel: "browser", label: "browser \\\\\\\\u00b7 action", dangerous: false },
  { method: "*", path: "/api/browser/agent-context", panel: "browser", label: "browser \\\\\\\\u00b7 agent context", dangerous: false },
  { method: "*", path: "/api/browser/agent-control", panel: "browser", label: "browser \\\\\\\\u00b7 agent control", dangerous: false },
  { method: "*", path: "/api/browser/control", panel: "browser", label: "browser \\\\\\\\u00b7 control", dangerous: false },
  { method: "*", path: "/api/browser/events", panel: "browser", label: "browser \\\\\\\\u00b7 events", dangerous: false },
  { method: "*", path: "/api/browser/frame", panel: "browser", label: "browser \\\\\\\\u00b7 frame", dangerous: false },
  { method: "*", path: "/api/browser/permission", panel: "browser", label: "browser \\\\\\\\u00b7 permission", dangerous: false },
  { method: "*", path: "/api/browser/qa", panel: "browser", label: "browser \\\\\\\\u00b7 qa", dangerous: false },
  { method: "*", path: "/api/browser/state", panel: "browser", label: "browser \\\\\\\\u00b7 state", dangerous: false },
  { method: "*", path: "/api/browser/webui-smoke", panel: "browser", label: "browser \\\\\\\\u00b7 webui smoke", dangerous: false },
  { method: "GET", path: "/api/sessions/search", panel: "browser", label: "GET sessions · search", dangerous: false },
  { method: "*", path: "/api/approval", panel: "chat", label: "approval", dangerous: false },
  { method: "*", path: "/api/approval/inject_test", panel: "chat", label: "approval \\\\\\\\u00b7 inject test", dangerous: false },
  { method: "*", path: "/api/approval/pending", panel: "chat", label: "approval \\\\\\\\u00b7 pending", dangerous: false },
  { method: "*", path: "/api/approval/pending-all", panel: "chat", label: "approval \\\\\\\\u00b7 pending all", dangerous: false },
  { method: "*", path: "/api/approval/respond", panel: "chat", label: "approval \\\\\\\\u00b7 respond", dangerous: false },
  { method: "*", path: "/api/approval/stream", panel: "chat", label: "approval \\\\\\\\u00b7 stream", dangerous: false },
  { method: "*", path: "/api/btw", panel: "chat", label: "btw", dangerous: false },
  { method: "*", path: "/api/chat", panel: "chat", label: "chat", dangerous: false },
  { method: "*", path: "/api/chat/apply-code", panel: "chat", label: "chat \\\\\\\\u00b7 apply code", dangerous: true },
  { method: "*", path: "/api/chat/apply-patch", panel: "chat", label: "chat \\\\\\\\u00b7 apply patch", dangerous: true },
  { method: "*", path: "/api/chat/cancel", panel: "chat", label: "chat \\\\\\\\u00b7 cancel", dangerous: false },
  { method: "*", path: "/api/chat/plan/accept", panel: "chat", label: "chat \\\\\\\\u00b7 plan \\\\\\\\u00b7 accept", dangerous: false },
  { method: "*", path: "/api/chat/plan/revise", panel: "chat", label: "chat \\\\\\\\u00b7 plan \\\\\\\\u00b7 revise", dangerous: false },
  { method: "*", path: "/api/chat/start", panel: "chat", label: "chat \\\\\\\\u00b7 start", dangerous: false },
  { method: "*", path: "/api/chat/steer", panel: "chat", label: "chat \\\\\\\\u00b7 steer", dangerous: false },
  { method: "*", path: "/api/chat/stream", panel: "chat", label: "chat \\\\\\\\u00b7 stream", dangerous: false },
  { method: "*", path: "/api/chat/stream/status", panel: "chat", label: "chat \\\\\\\\u00b7 stream \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/clarify/inject_test", panel: "chat", label: "clarify \\\\\\\\u00b7 inject test", dangerous: false },
  { method: "*", path: "/api/clarify/pending", panel: "chat", label: "clarify \\\\\\\\u00b7 pending", dangerous: false },
  { method: "*", path: "/api/clarify/respond", panel: "chat", label: "clarify \\\\\\\\u00b7 respond", dangerous: false },
  { method: "*", path: "/api/clarify/stream", panel: "chat", label: "clarify \\\\\\\\u00b7 stream", dangerous: false },
  { method: "DELETE", path: "/api/providers/oauth/sessions/{session_id}", panel: "chat", label: "DELETE providers · oauth · sessions · {session_id}", dangerous: true },
  { method: "*", path: "/api/session", panel: "chat", label: "session", dangerous: false },
  { method: "GET", path: "/api/session", panel: "chat", label: "GET session", dangerous: false },
  { method: "*", path: "/api/session/archive", panel: "chat", label: "session \\\\\\\\u00b7 archive", dangerous: false },
  { method: "*", path: "/api/session/branch", panel: "chat", label: "session \\\\\\\\u00b7 branch", dangerous: false },
  { method: "*", path: "/api/session/clear", panel: "chat", label: "session \\\\\\\\u00b7 clear", dangerous: true },
  { method: "*", path: "/api/session/compress", panel: "chat", label: "session \\\\\\\\u00b7 compress", dangerous: false },
  { method: "*", path: "/api/session/context-info", panel: "chat", label: "session \\\\\\\\u00b7 context info", dangerous: false },
  { method: "*", path: "/api/session/conversation-rounds", panel: "chat", label: "session \\\\\\\\u00b7 conversation rounds", dangerous: false },
  { method: "*", path: "/api/session/delete", panel: "chat", label: "session \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/session/draft", panel: "chat", label: "session \\\\\\\\u00b7 draft", dangerous: false },
  { method: "*", path: "/api/session/duplicate", panel: "chat", label: "session \\\\\\\\u00b7 duplicate", dangerous: false },
  { method: "*", path: "/api/session/export", panel: "chat", label: "session \\\\\\\\u00b7 export", dangerous: false },
  { method: "*", path: "/api/session/handoff-summary", panel: "chat", label: "session \\\\\\\\u00b7 handoff summary", dangerous: false },
  { method: "*", path: "/api/session/import", panel: "chat", label: "session \\\\\\\\u00b7 import", dangerous: false },
  { method: "*", path: "/api/session/import_cli", panel: "chat", label: "session \\\\\\\\u00b7 import cli", dangerous: false },
  { method: "*", path: "/api/session/lineage/report", panel: "chat", label: "session \\\\\\\\u00b7 lineage \\\\\\\\u00b7 report", dangerous: false },
  { method: "*", path: "/api/session/move", panel: "chat", label: "session \\\\\\\\u00b7 move", dangerous: false },
  { method: "*", path: "/api/session/new", panel: "chat", label: "session \\\\\\\\u00b7 new", dangerous: false },
  { method: "*", path: "/api/session/pin", panel: "chat", label: "session \\\\\\\\u00b7 pin", dangerous: false },
  { method: "*", path: "/api/session/recovery/audit", panel: "chat", label: "session \\\\\\\\u00b7 recovery \\\\\\\\u00b7 audit", dangerous: false },
  { method: "*", path: "/api/session/recovery/repair-safe", panel: "chat", label: "session \\\\\\\\u00b7 recovery \\\\\\\\u00b7 repair safe", dangerous: false },
  { method: "*", path: "/api/session/rename", panel: "chat", label: "session \\\\\\\\u00b7 rename", dangerous: false },
  { method: "*", path: "/api/session/retry", panel: "chat", label: "session \\\\\\\\u00b7 retry", dangerous: false },
  { method: "*", path: "/api/session/status", panel: "chat", label: "session \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/session/toolsets", panel: "chat", label: "session \\\\\\\\u00b7 toolsets", dangerous: false },
  { method: "*", path: "/api/session/truncate", panel: "chat", label: "session \\\\\\\\u00b7 truncate", dangerous: false },
  { method: "*", path: "/api/session/undo", panel: "chat", label: "session \\\\\\\\u00b7 undo", dangerous: false },
  { method: "*", path: "/api/session/update", panel: "chat", label: "session \\\\\\\\u00b7 update", dangerous: false },
  { method: "*", path: "/api/session/usage", panel: "chat", label: "session \\\\\\\\u00b7 usage", dangerous: false },
  { method: "*", path: "/api/session/worktree/status", panel: "chat", label: "session \\\\\\\\u00b7 worktree \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/session/yolo", panel: "chat", label: "session \\\\\\\\u00b7 yolo", dangerous: false },
  { method: "*", path: "/api/sessions", panel: "chat", label: "sessions", dangerous: false },
  { method: "GET", path: "/api/sessions", panel: "chat", label: "GET sessions", dangerous: false },
  { method: "DELETE", path: "/api/sessions/{session_id}", panel: "chat", label: "DELETE sessions · {session_id}", dangerous: true },
  { method: "GET", path: "/api/sessions/{session_id}", panel: "chat", label: "GET sessions · {session_id}", dangerous: false },
  { method: "GET", path: "/api/sessions/{session_id}/latest-descendant", panel: "chat", label: "GET sessions · {session_id} · latest descendant", dangerous: false },
  { method: "GET", path: "/api/sessions/{session_id}/messages", panel: "chat", label: "GET sessions · {session_id} · messages", dangerous: false },
  { method: "*", path: "/api/sessions/cleanup", panel: "chat", label: "sessions \\\\\\\\u00b7 cleanup", dangerous: true },
  { method: "*", path: "/api/sessions/cleanup_zero_message", panel: "chat", label: "sessions \\\\\\\\u00b7 cleanup zero message", dangerous: true },
  { method: "*", path: "/api/sessions/gateway/stream", panel: "chat", label: "sessions \\\\\\\\u00b7 gateway \\\\\\\\u00b7 stream", dangerous: false },
  { method: "*", path: "/api/sessions/search", panel: "chat", label: "sessions \\\\\\\\u00b7 search", dangerous: false },
  { method: "*", path: "/api/discord", panel: "discord", label: "discord", dangerous: false },
  { method: "*", path: "/api/discord/ban", panel: "discord", label: "discord \\\\\\\\u00b7 ban", dangerous: true },
  { method: "*", path: "/api/discord/bot/info", panel: "discord", label: "discord \\\\\\\\u00b7 bot \\\\\\\\u00b7 info", dangerous: false },
  { method: "*", path: "/api/discord/channel", panel: "discord", label: "discord \\\\\\\\u00b7 channel", dangerous: false },
  { method: "*", path: "/api/discord/channels", panel: "discord", label: "discord \\\\\\\\u00b7 channels", dangerous: false },
  { method: "PUT", path: "/api/discord/channels/{channel_id}", panel: "discord", label: "PUT discord · channels · {channel_id}", dangerous: false },
  { method: "*", path: "/api/discord/channels/tree", panel: "discord", label: "discord \\\\\\\\u00b7 channels \\\\\\\\u00b7 tree", dangerous: false },
  { method: "*", path: "/api/discord/config", panel: "discord", label: "discord \\\\\\\\u00b7 config", dangerous: false },
  { method: "*", path: "/api/discord/debug", panel: "discord", label: "discord \\\\\\\\u00b7 debug", dangerous: false },
  { method: "*", path: "/api/discord/guild", panel: "discord", label: "discord \\\\\\\\u00b7 guild", dangerous: false },
  { method: "GET", path: "/api/discord/guilds", panel: "discord", label: "GET discord · guilds", dangerous: false },
  { method: "GET", path: "/api/discord/guilds/{guild_id}/channels", panel: "discord", label: "GET discord · guilds · {guild_id} · channels", dangerous: false },
  { method: "GET", path: "/api/discord/guilds/{guild_id}/members", panel: "discord", label: "GET discord · guilds · {guild_id} · members", dangerous: false },
  { method: "GET", path: "/api/discord/guilds/{guild_id}/roles", panel: "discord", label: "GET discord · guilds · {guild_id} · roles", dangerous: false },
  { method: "*", path: "/api/discord/kick", panel: "discord", label: "discord \\\\\\\\u00b7 kick", dangerous: true },
  { method: "*", path: "/api/discord/member", panel: "discord", label: "discord \\\\\\\\u00b7 member", dangerous: false },
  { method: "*", path: "/api/discord/members", panel: "discord", label: "discord \\\\\\\\u00b7 members", dangerous: false },
  { method: "PUT", path: "/api/discord/members/{member_id}/roles", panel: "discord", label: "PUT discord · members · {member_id} · roles", dangerous: false },
  { method: "*", path: "/api/discord/purge", panel: "discord", label: "discord \\\\\\\\u00b7 purge", dangerous: true },
  { method: "*", path: "/api/discord/rawtest", panel: "discord", label: "discord \\\\\\\\u00b7 rawtest", dangerous: false },
  { method: "*", path: "/api/discord/roles", panel: "discord", label: "discord \\\\\\\\u00b7 roles", dangerous: false },
  { method: "*", path: "/api/discord/send", panel: "discord", label: "discord \\\\\\\\u00b7 send", dangerous: false },
  { method: "*", path: "/api/discord/stats", panel: "discord", label: "discord \\\\\\\\u00b7 stats", dangerous: false },
  { method: "*", path: "/api/discord/timeout", panel: "discord", label: "discord \\\\\\\\u00b7 timeout", dangerous: false },
  { method: "*", path: "/api/discord/unban", panel: "discord", label: "discord \\\\\\\\u00b7 unban", dangerous: true },
  { method: "*", path: "/api/discord/untimeout", panel: "discord", label: "discord \\\\\\\\u00b7 untimeout", dangerous: false },
  { method: "*", path: "/api/discord/warn", panel: "discord", label: "discord \\\\\\\\u00b7 warn", dangerous: false },
  { method: "*", path: "/api/discord/warns", panel: "discord", label: "discord \\\\\\\\u00b7 warns", dangerous: false },
  { method: "*", path: "/api/gmail", panel: "gmail", label: "gmail", dangerous: false },
  { method: "*", path: "/api/gmail/accounts", panel: "gmail", label: "gmail \\\\\\\\u00b7 accounts", dangerous: false },
  { method: "*", path: "/api/gmail/ai/draft", panel: "gmail", label: "gmail \\\\\\\\u00b7 ai \\\\\\\\u00b7 draft", dangerous: false },
  { method: "*", path: "/api/gmail/ai/related", panel: "gmail", label: "gmail \\\\\\\\u00b7 ai \\\\\\\\u00b7 related", dangerous: false },
  { method: "*", path: "/api/gmail/ai/summary", panel: "gmail", label: "gmail \\\\\\\\u00b7 ai \\\\\\\\u00b7 summary", dangerous: false },
  { method: "*", path: "/api/gmail/ai/summary/stream", panel: "gmail", label: "gmail \\\\\\\\u00b7 ai \\\\\\\\u00b7 summary \\\\\\\\u00b7 stream", dangerous: false },
  { method: "*", path: "/api/gmail/ai/task", panel: "gmail", label: "gmail \\\\\\\\u00b7 ai \\\\\\\\u00b7 task", dangerous: false },
  { method: "*", path: "/api/gmail/delete", panel: "gmail", label: "gmail \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/gmail/folders", panel: "gmail", label: "gmail \\\\\\\\u00b7 folders", dangerous: false },
  { method: "*", path: "/api/gmail/list", panel: "gmail", label: "gmail \\\\\\\\u00b7 list", dangerous: false },
  { method: "*", path: "/api/gmail/move", panel: "gmail", label: "gmail \\\\\\\\u00b7 move", dangerous: false },
  { method: "*", path: "/api/gmail/read", panel: "gmail", label: "gmail \\\\\\\\u00b7 read", dangerous: false },
  { method: "*", path: "/api/gmail/search", panel: "gmail", label: "gmail \\\\\\\\u00b7 search", dangerous: false },
  { method: "*", path: "/api/gmail/send", panel: "gmail", label: "gmail \\\\\\\\u00b7 send", dangerous: false },
  { method: "*", path: "/api/mail/config", panel: "gmail", label: "mail \\\\\\\\u00b7 config", dangerous: false },
  { method: "*", path: "/api/mail/folders", panel: "gmail", label: "mail \\\\\\\\u00b7 folders", dangerous: false },
  { method: "*", path: "/api/mail/inbox", panel: "gmail", label: "mail \\\\\\\\u00b7 inbox", dangerous: false },
  { method: "*", path: "/api/mail/search", panel: "gmail", label: "mail \\\\\\\\u00b7 search", dangerous: false },
  { method: "*", path: "/api/mail/send", panel: "gmail", label: "mail \\\\\\\\u00b7 send", dangerous: false },
  { method: "*", path: "/api/mail/setup", panel: "gmail", label: "mail \\\\\\\\u00b7 setup", dangerous: false },
  { method: "*", path: "/api/analytics/usage", panel: "insights", label: "analytics \\\\\\\\u00b7 usage", dangerous: false },
  { method: "*", path: "/api/insights", panel: "insights", label: "insights", dangerous: false },
  { method: "*", path: "/api/kanban", panel: "kanban", label: "kanban", dangerous: true },
  { method: "*", path: "/api/kanban/assignees", panel: "kanban", label: "kanban \\\\\\\\u00b7 assignees", dangerous: true },
  { method: "*", path: "/api/kanban/board", panel: "kanban", label: "kanban \\\\\\\\u00b7 board", dangerous: true },
  { method: "*", path: "/api/kanban/boards", panel: "kanban", label: "kanban \\\\\\\\u00b7 boards", dangerous: true },
  { method: "*", path: "/api/kanban/config", panel: "kanban", label: "kanban \\\\\\\\u00b7 config", dangerous: true },
  { method: "*", path: "/api/kanban/dispatch", panel: "kanban", label: "kanban \\\\\\\\u00b7 dispatch", dangerous: true },
  { method: "*", path: "/api/kanban/events", panel: "kanban", label: "kanban \\\\\\\\u00b7 events", dangerous: true },
  { method: "*", path: "/api/kanban/events/stream", panel: "kanban", label: "kanban \\\\\\\\u00b7 events \\\\\\\\u00b7 stream", dangerous: true },
  { method: "*", path: "/api/kanban/links", panel: "kanban", label: "kanban \\\\\\\\u00b7 links", dangerous: true },
  { method: "*", path: "/api/kanban/links/delete", panel: "kanban", label: "kanban \\\\\\\\u00b7 links \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/kanban/stats", panel: "kanban", label: "kanban \\\\\\\\u00b7 stats", dangerous: true },
  { method: "*", path: "/api/kanban/tasks", panel: "kanban", label: "kanban \\\\\\\\u00b7 tasks", dangerous: true },
  { method: "*", path: "/api/kanban/tasks/bulk", panel: "kanban", label: "kanban \\\\\\\\u00b7 tasks \\\\\\\\u00b7 bulk", dangerous: true },
  { method: "*", path: "/api/csp-report", panel: "logs", label: "csp report", dangerous: false },
  { method: "*", path: "/api/errors", panel: "logs", label: "errors", dangerous: false },
  { method: "*", path: "/api/errors/clear", panel: "logs", label: "errors \\\\\\\\u00b7 clear", dangerous: true },
  { method: "*", path: "/api/errors/db-path", panel: "logs", label: "errors \\\\\\\\u00b7 db path", dangerous: false },
  { method: "*", path: "/api/errors/log", panel: "logs", label: "errors \\\\\\\\u00b7 log", dangerous: false },
  { method: "*", path: "/api/errors/stats", panel: "logs", label: "errors \\\\\\\\u00b7 stats", dangerous: false },
  { method: "*", path: "/api/events", panel: "logs", label: "events", dangerous: false },
  { method: "*", path: "/api/logs", panel: "logs", label: "logs", dangerous: false },
  { method: "GET", path: "/api/logs", panel: "logs", label: "GET logs", dangerous: false },
  { method: "*", path: "/api/memory", panel: "memory", label: "memory", dangerous: false },
  { method: "*", path: "/api/memory/hybrid/search", panel: "memory", label: "memory \\\\\\\\u00b7 hybrid \\\\\\\\u00b7 search", dangerous: false },
  { method: "*", path: "/api/memory/supermemory/add", panel: "memory", label: "memory \\\\\\\\u00b7 supermemory \\\\\\\\u00b7 add", dangerous: false },
  { method: "*", path: "/api/memory/supermemory/document", panel: "memory", label: "memory \\\\\\\\u00b7 supermemory \\\\\\\\u00b7 document", dangerous: false },
  { method: "*", path: "/api/memory/supermemory/forget", panel: "memory", label: "memory \\\\\\\\u00b7 supermemory \\\\\\\\u00b7 forget", dangerous: false },
  { method: "*", path: "/api/memory/supermemory/list", panel: "memory", label: "memory \\\\\\\\u00b7 supermemory \\\\\\\\u00b7 list", dangerous: false },
  { method: "*", path: "/api/memory/supermemory/search", panel: "memory", label: "memory \\\\\\\\u00b7 supermemory \\\\\\\\u00b7 search", dangerous: false },
  { method: "*", path: "/api/memory/supermemory/status", panel: "memory", label: "memory \\\\\\\\u00b7 supermemory \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/memory/write", panel: "memory", label: "memory \\\\\\\\u00b7 write", dangerous: false },
  { method: "*", path: "/api/profile/active", panel: "profiles", label: "profile \\\\\\\\u00b7 active", dangerous: false },
  { method: "*", path: "/api/profile/create", panel: "profiles", label: "profile \\\\\\\\u00b7 create", dangerous: false },
  { method: "*", path: "/api/profile/delete", panel: "profiles", label: "profile \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/profile/switch", panel: "profiles", label: "profile \\\\\\\\u00b7 switch", dangerous: false },
  { method: "*", path: "/api/profiles", panel: "profiles", label: "profiles", dangerous: false },
  { method: "GET", path: "/api/profiles", panel: "profiles", label: "GET profiles", dangerous: false },
  { method: "POST", path: "/api/profiles", panel: "profiles", label: "POST profiles", dangerous: false },
  { method: "DELETE", path: "/api/profiles/{name}", panel: "profiles", label: "DELETE profiles · {name}", dangerous: true },
  { method: "PATCH", path: "/api/profiles/{name}", panel: "profiles", label: "PATCH profiles · {name}", dangerous: false },
  { method: "POST", path: "/api/profiles/{name}/open-terminal", panel: "profiles", label: "POST profiles · {name} · open terminal", dangerous: false },
  { method: "GET", path: "/api/profiles/{name}/setup-command", panel: "profiles", label: "GET profiles · {name} · setup command", dangerous: false },
  { method: "GET", path: "/api/profiles/{name}/soul", panel: "profiles", label: "GET profiles · {name} · soul", dangerous: false },
  { method: "PUT", path: "/api/profiles/{name}/soul", panel: "profiles", label: "PUT profiles · {name} · soul", dangerous: false },
  { method: "DELETE", path: "/api/{path:path}", panel: "settings", label: "DELETE {path:path}", dangerous: true },
  { method: "GET", path: "/api/{path:path}", panel: "settings", label: "GET {path:path}", dangerous: false },
  { method: "HEAD", path: "/api/{path:path}", panel: "settings", label: "HEAD {path:path}", dangerous: false },
  { method: "PATCH", path: "/api/{path:path}", panel: "settings", label: "PATCH {path:path}", dangerous: false },
  { method: "POST", path: "/api/{path:path}", panel: "settings", label: "POST {path:path}", dangerous: false },
  { method: "PUT", path: "/api/{path:path}", panel: "settings", label: "PUT {path:path}", dangerous: false },
  { method: "GET", path: "/api/actions/{name}/status", panel: "settings", label: "GET actions · {name} · status", dangerous: false },
  { method: "*", path: "/api/admin/reload", panel: "settings", label: "admin \\\\\\\\u00b7 reload", dangerous: false },
  { method: "GET", path: "/api/analytics/models", panel: "settings", label: "GET analytics · models", dangerous: false },
  { method: "GET", path: "/api/analytics/usage", panel: "settings", label: "GET analytics · usage", dangerous: false },
  { method: "*", path: "/api/auth/login", panel: "settings", label: "auth \\\\\\\\u00b7 login", dangerous: false },
  { method: "*", path: "/api/auth/logout", panel: "settings", label: "auth \\\\\\\\u00b7 logout", dangerous: false },
  { method: "*", path: "/api/auth/status", panel: "settings", label: "auth \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/background", panel: "settings", label: "background", dangerous: false },
  { method: "*", path: "/api/background/status", panel: "settings", label: "background \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/cast/start", panel: "settings", label: "cast \\\\\\\\u00b7 start", dangerous: false },
  { method: "*", path: "/api/cast/status", panel: "settings", label: "cast \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/cast/toggle", panel: "settings", label: "cast \\\\\\\\u00b7 toggle", dangerous: false },
  { method: "*", path: "/api/cockpit/settings", panel: "settings", label: "cockpit \\\\\\\\u00b7 settings", dangerous: false },
  { method: "GET", path: "/api/config", panel: "settings", label: "GET config", dangerous: false },
  { method: "PUT", path: "/api/config", panel: "settings", label: "PUT config", dangerous: false },
  { method: "GET", path: "/api/config/defaults", panel: "settings", label: "GET config · defaults", dangerous: false },
  { method: "GET", path: "/api/config/raw", panel: "settings", label: "GET config · raw", dangerous: false },
  { method: "PUT", path: "/api/config/raw", panel: "settings", label: "PUT config · raw", dangerous: false },
  { method: "GET", path: "/api/config/schema", panel: "settings", label: "GET config · schema", dangerous: false },
  { method: "*", path: "/api/dashboard/config", panel: "settings", label: "dashboard \\\\\\\\u00b7 config", dangerous: false },
  { method: "PUT", path: "/api/dashboard/plugin-providers", panel: "settings", label: "PUT dashboard · plugin providers", dangerous: false },
  { method: "GET", path: "/api/dashboard/plugins", panel: "settings", label: "GET dashboard · plugins", dangerous: false },
  { method: "POST", path: "/api/dashboard/plugins/{name}/visibility", panel: "settings", label: "POST dashboard · plugins · {name} · visibility", dangerous: false },
  { method: "GET", path: "/api/dashboard/plugins/hub", panel: "settings", label: "GET dashboard · plugins · hub", dangerous: false },
  { method: "GET", path: "/api/dashboard/plugins/rescan", panel: "settings", label: "GET dashboard · plugins · rescan", dangerous: false },
  { method: "*", path: "/api/dashboard/status", panel: "settings", label: "dashboard \\\\\\\\u00b7 status", dangerous: false },
  { method: "PUT", path: "/api/dashboard/theme", panel: "settings", label: "PUT dashboard · theme", dangerous: false },
  { method: "GET", path: "/api/dashboard/themes", panel: "settings", label: "GET dashboard · themes", dangerous: false },
  { method: "*", path: "/api/default-model", panel: "settings", label: "default model", dangerous: false },
  { method: "DELETE", path: "/api/env", panel: "settings", label: "DELETE env", dangerous: true },
  { method: "GET", path: "/api/env", panel: "settings", label: "GET env", dangerous: false },
  { method: "PUT", path: "/api/env", panel: "settings", label: "PUT env", dangerous: false },
  { method: "POST", path: "/api/env/reveal", panel: "settings", label: "POST env · reveal", dangerous: false },
  { method: "*", path: "/api/evey", panel: "settings", label: "evey", dangerous: false },
  { method: "*", path: "/api/evey/cache", panel: "settings", label: "evey \\\\\\\\u00b7 cache", dangerous: false },
  { method: "*", path: "/api/evey/cache/lookup", panel: "settings", label: "evey \\\\\\\\u00b7 cache \\\\\\\\u00b7 lookup", dangerous: false },
  { method: "*", path: "/api/evey/delegation/log", panel: "settings", label: "evey \\\\\\\\u00b7 delegation \\\\\\\\u00b7 log", dangerous: false },
  { method: "*", path: "/api/evey/delegation/stats", panel: "settings", label: "evey \\\\\\\\u00b7 delegation \\\\\\\\u00b7 stats", dangerous: false },
  { method: "*", path: "/api/evey/habits/insights", panel: "settings", label: "evey \\\\\\\\u00b7 habits \\\\\\\\u00b7 insights", dangerous: false },
  { method: "*", path: "/api/evey/habits/log", panel: "settings", label: "evey \\\\\\\\u00b7 habits \\\\\\\\u00b7 log", dangerous: false },
  { method: "*", path: "/api/evey/learn", panel: "settings", label: "evey \\\\\\\\u00b7 learn", dangerous: false },
  { method: "*", path: "/api/evey/learnings", panel: "settings", label: "evey \\\\\\\\u00b7 learnings", dangerous: false },
  { method: "*", path: "/api/evey/learnings/apply", panel: "settings", label: "evey \\\\\\\\u00b7 learnings \\\\\\\\u00b7 apply", dangerous: true },
  { method: "*", path: "/api/evey/memory/decay", panel: "settings", label: "evey \\\\\\\\u00b7 memory \\\\\\\\u00b7 decay", dangerous: false },
  { method: "*", path: "/api/evey/memory/score", panel: "settings", label: "evey \\\\\\\\u00b7 memory \\\\\\\\u00b7 score", dangerous: false },
  { method: "*", path: "/api/evey/schedule", panel: "settings", label: "evey \\\\\\\\u00b7 schedule", dangerous: false },
  { method: "*", path: "/api/evey/status", panel: "settings", label: "evey \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/evey/telemetry", panel: "settings", label: "evey \\\\\\\\u00b7 telemetry", dangerous: false },
  { method: "*", path: "/api/evey/validate", panel: "settings", label: "evey \\\\\\\\u00b7 validate", dangerous: false },
  { method: "*", path: "/api/evey/watchdog/heartbeat", panel: "settings", label: "evey \\\\\\\\u00b7 watchdog \\\\\\\\u00b7 heartbeat", dangerous: false },
  { method: "*", path: "/api/evey/watchdog/status", panel: "settings", label: "evey \\\\\\\\u00b7 watchdog \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/game-mode/status", panel: "settings", label: "game mode \\\\\\\\u00b7 status", dangerous: false },
  { method: "POST", path: "/api/gateway/restart", panel: "settings", label: "POST gateway · restart", dangerous: true },
  { method: "*", path: "/api/gateway/status", panel: "settings", label: "gateway \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/git-info", panel: "settings", label: "git info", dangerous: false },
  { method: "*", path: "/api/goal", panel: "settings", label: "goal", dangerous: false },
  { method: "*", path: "/api/health/agent", panel: "settings", label: "health \\\\\\\\u00b7 agent", dangerous: false },
  { method: "*", path: "/api/image_generate", panel: "settings", label: "image generate", dangerous: false },
  { method: "*", path: "/api/list", panel: "settings", label: "list", dangerous: false },
  { method: "*", path: "/api/mcp/servers", panel: "settings", label: "mcp \\\\\\\\u00b7 servers", dangerous: false },
  { method: "*", path: "/api/mcp/tools", panel: "settings", label: "mcp \\\\\\\\u00b7 tools", dangerous: false },
  { method: "*", path: "/api/media", panel: "settings", label: "media", dangerous: false },
  { method: "GET", path: "/api/model/auxiliary", panel: "settings", label: "GET model · auxiliary", dangerous: false },
  { method: "GET", path: "/api/model/info", panel: "settings", label: "GET model · info", dangerous: false },
  { method: "GET", path: "/api/model/options", panel: "settings", label: "GET model · options", dangerous: false },
  { method: "POST", path: "/api/model/set", panel: "settings", label: "POST model · set", dangerous: false },
  { method: "*", path: "/api/models", panel: "settings", label: "models", dangerous: false },
  { method: "GET", path: "/api/models", panel: "settings", label: "GET models", dangerous: false },
  { method: "*", path: "/api/models/live", panel: "settings", label: "models \\\\\\\\u00b7 live", dangerous: false },
  { method: "GET", path: "/api/models/live", panel: "settings", label: "GET models · live", dangerous: false },
  { method: "POST", path: "/api/models/refresh", panel: "settings", label: "POST models · refresh", dangerous: false },
  { method: "*", path: "/api/oauth/google/disconnect", panel: "settings", label: "oauth \\\\\\\\u00b7 google \\\\\\\\u00b7 disconnect", dangerous: false },
  { method: "*", path: "/api/onboarding/complete", panel: "settings", label: "onboarding \\\\\\\\u00b7 complete", dangerous: false },
  { method: "POST", path: "/api/onboarding/complete", panel: "settings", label: "POST onboarding · complete", dangerous: false },
  { method: "POST", path: "/api/onboarding/oauth/cancel", panel: "settings", label: "POST onboarding · oauth · cancel", dangerous: false },
  { method: "GET", path: "/api/onboarding/oauth/poll", panel: "settings", label: "GET onboarding · oauth · poll", dangerous: false },
  { method: "POST", path: "/api/onboarding/oauth/start", panel: "settings", label: "POST onboarding · oauth · start", dangerous: false },
  { method: "*", path: "/api/onboarding/probe", panel: "settings", label: "onboarding \\\\\\\\u00b7 probe", dangerous: false },
  { method: "POST", path: "/api/onboarding/probe", panel: "settings", label: "POST onboarding · probe", dangerous: false },
  { method: "*", path: "/api/onboarding/setup", panel: "settings", label: "onboarding \\\\\\\\u00b7 setup", dangerous: false },
  { method: "POST", path: "/api/onboarding/setup", panel: "settings", label: "POST onboarding · setup", dangerous: false },
  { method: "*", path: "/api/onboarding/status", panel: "settings", label: "onboarding \\\\\\\\u00b7 status", dangerous: false },
  { method: "GET", path: "/api/onboarding/status", panel: "settings", label: "GET onboarding · status", dangerous: false },
  { method: "*", path: "/api/personalities", panel: "settings", label: "personalities", dangerous: false },
  { method: "*", path: "/api/personality/set", panel: "settings", label: "personality \\\\\\\\u00b7 set", dangerous: false },
  { method: "*", path: "/api/plugins", panel: "settings", label: "plugins", dangerous: false },
  { method: "*", path: "/api/provider/quota", panel: "settings", label: "provider \\\\\\\\u00b7 quota", dangerous: false },
  { method: "*", path: "/api/providers", panel: "settings", label: "providers", dangerous: false },
  { method: "*", path: "/api/providers/delete", panel: "settings", label: "providers \\\\\\\\u00b7 delete", dangerous: true },
  { method: "GET", path: "/api/providers/oauth", panel: "settings", label: "GET providers · oauth", dangerous: false },
  { method: "DELETE", path: "/api/providers/oauth/{provider_id}", panel: "settings", label: "DELETE providers · oauth · {provider_id}", dangerous: true },
  { method: "GET", path: "/api/providers/oauth/{provider_id}/poll/{session_id}", panel: "settings", label: "GET providers · oauth · {provider_id} · poll · {session_id}", dangerous: false },
  { method: "POST", path: "/api/providers/oauth/{provider_id}/start", panel: "settings", label: "POST providers · oauth · {provider_id} · start", dangerous: false },
  { method: "POST", path: "/api/providers/oauth/{provider_id}/submit", panel: "settings", label: "POST providers · oauth · {provider_id} · submit", dangerous: false },
  { method: "*", path: "/api/reasoning", panel: "settings", label: "reasoning", dangerous: false },
  { method: "*", path: "/api/review/diff", panel: "settings", label: "review \\\\\\\\u00b7 diff", dangerous: false },
  { method: "*", path: "/api/rollback/diff", panel: "settings", label: "rollback \\\\\\\\u00b7 diff", dangerous: true },
  { method: "*", path: "/api/rollback/list", panel: "settings", label: "rollback \\\\\\\\u00b7 list", dangerous: true },
  { method: "*", path: "/api/rollback/restore", panel: "settings", label: "rollback \\\\\\\\u00b7 restore", dangerous: true },
  { method: "*", path: "/api/runtime/fingerprint", panel: "settings", label: "runtime \\\\\\\\u00b7 fingerprint", dangerous: false },
  { method: "*", path: "/api/settings", panel: "settings", label: "settings", dangerous: false },
  { method: "POST", path: "/api/sidekick/update", panel: "settings", label: "POST sidekick · update", dangerous: false },
  { method: "*", path: "/api/spaces", panel: "settings", label: "spaces", dangerous: false },
  { method: "GET", path: "/api/status", panel: "settings", label: "GET status", dangerous: false },
  { method: "*", path: "/api/system/health", panel: "settings", label: "system \\\\\\\\u00b7 health", dangerous: false },
  { method: "*", path: "/api/system/restart", panel: "settings", label: "system \\\\\\\\u00b7 restart", dangerous: true },
  { method: "*", path: "/api/system/shutdown", panel: "settings", label: "system \\\\\\\\u00b7 shutdown", dangerous: true },
  { method: "GET", path: "/api/tools/toolsets", panel: "settings", label: "GET tools · toolsets", dangerous: false },
  { method: "*", path: "/api/transcribe", panel: "settings", label: "transcribe", dangerous: false },
  { method: "*", path: "/api/updates/apply", panel: "settings", label: "updates \\\\\\\\u00b7 apply", dangerous: true },
  { method: "*", path: "/api/updates/check", panel: "settings", label: "updates \\\\\\\\u00b7 check", dangerous: false },
  { method: "*", path: "/api/updates/force", panel: "settings", label: "updates \\\\\\\\u00b7 force", dangerous: true },
  { method: "*", path: "/api/web/backend", panel: "settings", label: "web \\\\\\\\u00b7 backend", dangerous: false },
  { method: "*", path: "/api/wiki/status", panel: "settings", label: "wiki \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/window/control", panel: "settings", label: "window \\\\\\\\u00b7 control", dangerous: false },
  { method: "*", path: "/api/workers", panel: "settings", label: "workers", dangerous: false },
  { method: "*", path: "/api/worktree/settings", panel: "settings", label: "worktree \\\\\\\\u00b7 settings", dangerous: false },
  { method: "GET", path: "/api/worktree/settings", panel: "settings", label: "GET worktree · settings", dangerous: false },
  { method: "POST", path: "/api/worktree/settings", panel: "settings", label: "POST worktree · settings", dangerous: false },
  { method: "*", path: "/api/skills", panel: "skills", label: "skills", dangerous: false },
  { method: "GET", path: "/api/skills", panel: "skills", label: "GET skills", dangerous: false },
  { method: "*", path: "/api/skills/content", panel: "skills", label: "skills \\\\\\\\u00b7 content", dangerous: false },
  { method: "*", path: "/api/skills/delete", panel: "skills", label: "skills \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/skills/disable", panel: "skills", label: "skills \\\\\\\\u00b7 disable", dangerous: false },
  { method: "*", path: "/api/skills/fingerprint", panel: "skills", label: "skills \\\\\\\\u00b7 fingerprint", dangerous: false },
  { method: "*", path: "/api/skills/pin", panel: "skills", label: "skills \\\\\\\\u00b7 pin", dangerous: false },
  { method: "*", path: "/api/skills/save", panel: "skills", label: "skills \\\\\\\\u00b7 save", dangerous: false },
  { method: "PUT", path: "/api/skills/toggle", panel: "skills", label: "PUT skills · toggle", dangerous: false },
  { method: "*", path: "/api/claude-jobs", panel: "tasks", label: "claude jobs", dangerous: false },
  { method: "GET", path: "/api/cron/jobs", panel: "tasks", label: "GET cron · jobs", dangerous: false },
  { method: "POST", path: "/api/cron/jobs", panel: "tasks", label: "POST cron · jobs", dangerous: false },
  { method: "DELETE", path: "/api/cron/jobs/{job_id}", panel: "tasks", label: "DELETE cron · jobs · {job_id}", dangerous: true },
  { method: "GET", path: "/api/cron/jobs/{job_id}", panel: "tasks", label: "GET cron · jobs · {job_id}", dangerous: false },
  { method: "PUT", path: "/api/cron/jobs/{job_id}", panel: "tasks", label: "PUT cron · jobs · {job_id}", dangerous: false },
  { method: "POST", path: "/api/cron/jobs/{job_id}/pause", panel: "tasks", label: "POST cron · jobs · {job_id} · pause", dangerous: false },
  { method: "POST", path: "/api/cron/jobs/{job_id}/resume", panel: "tasks", label: "POST cron · jobs · {job_id} · resume", dangerous: false },
  { method: "POST", path: "/api/cron/jobs/{job_id}/trigger", panel: "tasks", label: "POST cron · jobs · {job_id} · trigger", dangerous: false },
  { method: "*", path: "/api/crons", panel: "tasks", label: "crons", dangerous: false },
  { method: "*", path: "/api/crons/create", panel: "tasks", label: "crons \\\\\\\\u00b7 create", dangerous: false },
  { method: "*", path: "/api/crons/delete", panel: "tasks", label: "crons \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/crons/history", panel: "tasks", label: "crons \\\\\\\\u00b7 history", dangerous: false },
  { method: "*", path: "/api/crons/output", panel: "tasks", label: "crons \\\\\\\\u00b7 output", dangerous: false },
  { method: "*", path: "/api/crons/pause", panel: "tasks", label: "crons \\\\\\\\u00b7 pause", dangerous: false },
  { method: "*", path: "/api/crons/recent", panel: "tasks", label: "crons \\\\\\\\u00b7 recent", dangerous: false },
  { method: "*", path: "/api/crons/resume", panel: "tasks", label: "crons \\\\\\\\u00b7 resume", dangerous: false },
  { method: "*", path: "/api/crons/run", panel: "tasks", label: "crons \\\\\\\\u00b7 run", dangerous: false },
  { method: "*", path: "/api/crons/status", panel: "tasks", label: "crons \\\\\\\\u00b7 status", dangerous: false },
  { method: "*", path: "/api/crons/update", panel: "tasks", label: "crons \\\\\\\\u00b7 update", dangerous: false },
  { method: "*", path: "/api/dispatch/active", panel: "tasks", label: "dispatch \\\\\\\\u00b7 active", dangerous: false },
  { method: "*", path: "/api/dispatch/run", panel: "tasks", label: "dispatch \\\\\\\\u00b7 run", dangerous: false },
  { method: "*", path: "/api/commands", panel: "terminal", label: "commands", dangerous: false },
  { method: "*", path: "/api/commands/exec", panel: "terminal", label: "commands \\\\\\\\u00b7 exec", dangerous: false },
  { method: "*", path: "/api/execute_code", panel: "terminal", label: "execute code", dangerous: false },
  { method: "*", path: "/api/terminal/close", panel: "terminal", label: "terminal \\\\\\\\u00b7 close", dangerous: false },
  { method: "*", path: "/api/terminal/input", panel: "terminal", label: "terminal \\\\\\\\u00b7 input", dangerous: false },
  { method: "*", path: "/api/terminal/output", panel: "terminal", label: "terminal \\\\\\\\u00b7 output", dangerous: false },
  { method: "*", path: "/api/terminal/resize", panel: "terminal", label: "terminal \\\\\\\\u00b7 resize", dangerous: false },
  { method: "*", path: "/api/terminal/start", panel: "terminal", label: "terminal \\\\\\\\u00b7 start", dangerous: false },
  { method: "*", path: "/api/terminal/stream", panel: "terminal", label: "terminal \\\\\\\\u00b7 stream", dangerous: false },
  { method: "*", path: "/api/file", panel: "workspaces", label: "file", dangerous: false },
  { method: "*", path: "/api/file/create", panel: "workspaces", label: "file \\\\\\\\u00b7 create", dangerous: false },
  { method: "*", path: "/api/file/create-dir", panel: "workspaces", label: "file \\\\\\\\u00b7 create dir", dangerous: false },
  { method: "*", path: "/api/file/delete", panel: "workspaces", label: "file \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/file/path", panel: "workspaces", label: "file \\\\\\\\u00b7 path", dangerous: false },
  { method: "*", path: "/api/file/raw", panel: "workspaces", label: "file \\\\\\\\u00b7 raw", dangerous: false },
  { method: "*", path: "/api/file/rename", panel: "workspaces", label: "file \\\\\\\\u00b7 rename", dangerous: false },
  { method: "*", path: "/api/file/reveal", panel: "workspaces", label: "file \\\\\\\\u00b7 reveal", dangerous: false },
  { method: "*", path: "/api/file/save", panel: "workspaces", label: "file \\\\\\\\u00b7 save", dangerous: false },
  { method: "*", path: "/api/projects", panel: "workspaces", label: "projects", dangerous: false },
  { method: "*", path: "/api/projects/create", panel: "workspaces", label: "projects \\\\\\\\u00b7 create", dangerous: false },
  { method: "*", path: "/api/projects/delete", panel: "workspaces", label: "projects \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/projects/rename", panel: "workspaces", label: "projects \\\\\\\\u00b7 rename", dangerous: false },
  { method: "*", path: "/api/space/agent/create", panel: "workspaces", label: "space \\\\\\\\u00b7 agent \\\\\\\\u00b7 create", dangerous: false },
  { method: "*", path: "/api/space/agent/delete", panel: "workspaces", label: "space \\\\\\\\u00b7 agent \\\\\\\\u00b7 delete", dangerous: true },
  { method: "*", path: "/api/space/agents", panel: "workspaces", label: "space \\\\\\\\u00b7 agents", dangerous: false },
  { method: "*", path: "/api/space/agents/list", panel: "workspaces", label: "space \\\\\\\\u00b7 agents \\\\\\\\u00b7 list", dangerous: false },
  { method: "*", path: "/api/space/config", panel: "workspaces", label: "space \\\\\\\\u00b7 config", dangerous: false },
  { method: "*", path: "/api/space/create", panel: "workspaces", label: "space \\\\\\\\u00b7 create", dangerous: false },
  { method: "*", path: "/api/space/delete", panel: "workspaces", label: "space \\\\\\\\u00b7 delete", dangerous: true },
  { method: "GET", path: "/api/spaces", panel: "workspaces", label: "GET spaces", dangerous: false },
  { method: "*", path: "/api/upload", panel: "workspaces", label: "upload", dangerous: false },
  { method: "*", path: "/api/upload/extract", panel: "workspaces", label: "upload \\\\\\\\u00b7 extract", dangerous: false },
  { method: "GET", path: "/api/workspace/git-status", panel: "workspaces", label: "GET workspace · git status", dangerous: false },
  { method: "*", path: "/api/workspace/write", panel: "workspaces", label: "workspace \\\\\\\\u00b7 write", dangerous: false },
  { method: "*", path: "/api/workspaces", panel: "workspaces", label: "workspaces", dangerous: false },
  { method: "GET", path: "/api/workspaces", panel: "workspaces", label: "GET workspaces", dangerous: false },
  { method: "*", path: "/api/workspaces/add", panel: "workspaces", label: "workspaces \\\\\\\\u00b7 add", dangerous: false },
  { method: "*", path: "/api/workspaces/remove", panel: "workspaces", label: "workspaces \\\\\\\\u00b7 remove", dangerous: true },
  { method: "*", path: "/api/workspaces/rename", panel: "workspaces", label: "workspaces \\\\\\\\u00b7 rename", dangerous: false },
  { method: "*", path: "/api/workspaces/reorder", panel: "workspaces", label: "workspaces \\\\\\\\u00b7 reorder", dangerous: false },
  { method: "*", path: "/api/workspaces/suggest", panel: "workspaces", label: "workspaces \\\\\\\\u00b7 suggest", dangerous: false },
];

/** Endpoints for one panel, for the endpoint explorer. */
export function catalogEndpointsForPanel(panel: LastbrowserPanelId): CatalogEndpoint[] {
  return webuiEndpointCatalog.filter((entry) => entry.panel === panel);
}
