"""Eight-language wizard copy, exported as fresh dictionaries for UI adapters."""
LOCALES = ("de", "en", "it", "es", "fr", "pt-BR", "ru", "ja")
_KEYS = ("title", "lightweight", "balanced", "max_local", "hybrid", "custom", "automatic", "skip",
         "estimated", "unknown", "unsupported", "download_consent", "local_offline", "cloud_consent")
_ROWS = {
    "de": ("Lokale KI", "Geringe Rechnerbelastung", "Ausgewogen", "Beste geprüfte lokale Qualität", "Lokal und freigegebene Cloud", "Selbst wählen", "Automatische Empfehlung", "Überspringen / vorhandenen Provider nutzen", "Vorläufige Schätzung", "Noch nicht geprüft", "Nicht unterstützt", "Nur die ausgewählten Dateien nach Ihrer Zustimmung herunterladen", "Lokale KI funktioniert offline, sobald alle benötigten Dateien vorhanden sind", "Cloud wird nur mit Ihrer ausdrücklichen Freigabe verwendet"),
    "en": ("Local AI", "Low resource use", "Balanced", "Best verified local quality", "Local and approved cloud", "Choose individually", "Automatic recommendation", "Skip / use existing provider", "Preliminary estimate", "Not yet verified", "Unsupported", "Download only the selected files after your consent", "Local AI works offline once all required files are present", "Cloud is used only with your explicit permission"),
    "it": ("IA locale", "Basso uso di risorse", "Bilanciato", "Migliore qualità locale verificata", "Locale e cloud autorizzato", "Scegli singolarmente", "Raccomandazione automatica", "Salta / usa il provider esistente", "Stima preliminare", "Non ancora verificato", "Non supportato", "Scarica solo i file selezionati dopo il tuo consenso", "L’IA locale funziona offline quando tutti i file richiesti sono presenti", "Il cloud viene usato solo con il tuo consenso esplicito"),
    "es": ("IA local", "Bajo uso de recursos", "Equilibrado", "Mejor calidad local verificada", "Local y nube autorizada", "Elegir individualmente", "Recomendación automática", "Omitir / usar proveedor existente", "Estimación preliminar", "Aún sin verificar", "No compatible", "Descargar solo los archivos elegidos con tu consentimiento", "La IA local funciona sin conexión cuando están todos los archivos necesarios", "La nube solo se usa con tu autorización explícita"),
    "fr": ("IA locale", "Faible consommation", "Équilibré", "Meilleure qualité locale vérifiée", "Local et cloud autorisé", "Choisir individuellement", "Recommandation automatique", "Ignorer / utiliser le fournisseur existant", "Estimation provisoire", "Pas encore vérifié", "Non pris en charge", "Télécharger uniquement les fichiers choisis après votre accord", "L’IA locale fonctionne hors ligne lorsque tous les fichiers requis sont présents", "Le cloud est utilisé uniquement avec votre autorisation explicite"),
    "pt-BR": ("IA local", "Baixo uso de recursos", "Equilibrado", "Melhor qualidade local verificada", "Local e nuvem autorizada", "Escolher individualmente", "Recomendação automática", "Pular / usar provedor existente", "Estimativa preliminar", "Ainda não verificado", "Não compatível", "Baixar somente os arquivos escolhidos após seu consentimento", "A IA local funciona offline quando todos os arquivos necessários estão presentes", "A nuvem é usada somente com sua autorização explícita"),
    "ru": ("Локальный ИИ", "Низкая нагрузка", "Сбалансированный", "Лучшее проверенное локальное качество", "Локально и разрешённое облако", "Выбрать отдельно", "Автоматическая рекомендация", "Пропустить / использовать текущего провайдера", "Предварительная оценка", "Ещё не проверено", "Не поддерживается", "Скачать только выбранные файлы после вашего согласия", "Локальный ИИ работает офлайн после получения всех необходимых файлов", "Облако используется только с вашим явным разрешением"),
    "ja": ("ローカルAI", "低負荷", "バランス", "検証済みの最高ローカル品質", "ローカルと許可したクラウド", "個別に選択", "自動推奨", "スキップ / 既存のプロバイダーを使用", "暫定的な推定", "未検証", "非対応", "同意後に選択したファイルのみダウンロード", "必要なファイルがすべて揃うとローカルAIはオフラインで動作します", "クラウドは明示的な許可がある場合のみ使用します"),
}
_REASON_KEYS = ("runtime", "platform", "operation", "cpu", "memory", "pressure", "context", "manifest", "license", "head", "projector", "quality", "benchmark", "consent", "disk", "stale", "game_mode", "admission", "cloud", "sequential", "custom")
_REASON_ROWS = {
    "de": ("Keine geprüfte Modell-Laufzeit verfügbar", "Diese Laufzeit passt nicht zum Betriebssystem oder zur Prozessorarchitektur", "Der Adapter unterstützt diese Modellaufgabe nicht nachweislich", "Benötigte Prozessorbefehle fehlen oder sind ungeprüft", "Der verfügbare Inferenzspeicher ist noch nicht belastbar geprüft", "Das gemeinsame Speicherbudget reicht für diese Auswahl nicht aus", "Kontext oder Parallelität überschreiten den geprüften Bereich", "Die Modell-Dateien oder ihre Prüfsummen sind unvollständig", "Die genaue Modell-Lizenz ist noch nicht geprüft", "Der Encoder benötigt einen geprüften Aufgabenaufsatz", "Der passende Bildprojektor fehlt", "Der Qualitätstest für diese Aufgabe ist fehlgeschlagen", "Die Leistung wurde auf diesem Rechner noch nicht gemessen", "Für diesen Download fehlt Ihre Zustimmung", "Der freie Speicher für Download und Zwischenablage fehlt oder reicht nicht aus", "Die Messung ist veraltet; bitte erneut prüfen", "Spielmodus blockiert Modellinferenz", "Rechenplätze sind belegt oder noch nicht geprüft", "Hybrid benötigt eine ausdrücklich freigegebene, verfügbare Cloudverbindung", "Die Modelle müssen nacheinander laufen", "Dieses Modell ist nicht im geprüften Katalog"),
    "en": ("No verified model runtime available", "Runtime does not match the operating system or CPU architecture", "The adapter has no verified support for this model task", "Required CPU instructions are absent or unverified", "Available inference memory has not been reliably verified", "The shared memory budget cannot fit this selection", "Context or parallel requests exceed the verified range", "Model files or checksums are incomplete", "The exact model license is not verified", "The encoder requires a verified task head", "The matching image projector is missing", "Quality validation failed for this task", "Performance has not been measured on this computer", "This download needs your consent", "Free download and staging storage is unknown or insufficient", "Measurement is stale; scan again", "Game Mode blocks model inference", "Compute slots are busy or unverified", "Hybrid requires an explicitly approved available cloud connection", "Models must run sequentially", "This model is not in the verified catalog"),
    "it": ("Nessuna runtime verificata disponibile", "Runtime incompatibile con sistema o architettura", "Il supporto dell’adattatore per questa attività non è verificato", "Istruzioni CPU richieste mancanti o non verificate", "Memoria disponibile per inferenza non verificata", "Il budget di memoria condiviso è insufficiente", "Contesto o parallelismo superano il limite verificato", "File o checksum del modello incompleti", "Licenza esatta non verificata", "L’encoder richiede una testa specifica verificata", "Proiettore immagine corrispondente mancante", "Verifica qualità fallita", "Prestazioni non misurate su questo computer", "Il download richiede il tuo consenso", "Spazio per download e file temporanei sconosciuto o insufficiente", "Misurazione obsoleta; ripeti la scansione", "La modalità gioco blocca l’inferenza", "Slot di calcolo occupati o non verificati", "Hybrid richiede una connessione cloud disponibile e autorizzata", "I modelli devono essere eseguiti in sequenza", "Modello assente dal catalogo verificato"),
    "es": ("No hay motor de inferencia verificado", "Motor incompatible con sistema o arquitectura", "No se ha verificado el soporte para esta tarea", "Faltan instrucciones CPU requeridas o están sin verificar", "Memoria disponible para inferencia sin verificar", "El presupuesto de memoria compartida no es suficiente", "Contexto o paralelismo superan el rango verificado", "Archivos o sumas de verificación incompletos", "Licencia exacta sin verificar", "El codificador requiere un componente de tarea verificado", "Falta el proyector de imagen correspondiente", "Falló la validación de calidad", "Rendimiento sin medir en este equipo", "La descarga requiere tu consentimiento", "Espacio para descarga y archivos temporales desconocido o insuficiente", "Medición antigua; repetir análisis", "El modo juego bloquea la inferencia", "Recursos de cómputo ocupados o sin verificar", "Hybrid requiere una conexión de nube disponible y autorizada", "Los modelos deben ejecutarse en secuencia", "Modelo ausente del catálogo verificado"),
    "fr": ("Aucun moteur d’inférence vérifié disponible", "Moteur incompatible avec le système ou l’architecture", "La prise en charge de cette tâche n’est pas vérifiée", "Instructions CPU nécessaires absentes ou non vérifiées", "Mémoire disponible pour l’inférence non vérifiée", "Le budget de mémoire partagée est insuffisant", "Contexte ou parallélisme hors de la plage vérifiée", "Fichiers ou sommes de contrôle incomplets", "Licence exacte non vérifiée", "L’encodeur nécessite une tête de tâche vérifiée", "Projecteur d’image correspondant manquant", "Validation de qualité échouée", "Performances non mesurées sur cet ordinateur", "Le téléchargement nécessite votre accord", "Stockage de téléchargement et temporaire inconnu ou insuffisant", "Mesure ancienne ; relancer l’analyse", "Le mode jeu bloque l’inférence", "Ressources de calcul occupées ou non vérifiées", "Hybrid nécessite une connexion cloud disponible et autorisée", "Les modèles doivent fonctionner en séquence", "Modèle absent du catalogue vérifié"),
    "pt-BR": ("Nenhum motor de inferência verificado disponível", "Motor incompatível com sistema ou arquitetura", "Suporte para esta tarefa não verificado", "Instruções CPU necessárias ausentes ou não verificadas", "Memória disponível para inferência não verificada", "Orçamento de memória compartilhada insuficiente", "Contexto ou paralelismo fora do intervalo verificado", "Arquivos ou somas de verificação incompletos", "Licença exata não verificada", "O encoder exige um componente de tarefa verificado", "Projetor de imagem correspondente ausente", "Validação de qualidade falhou", "Desempenho não medido neste computador", "O download exige seu consentimento", "Espaço para download e arquivos temporários desconhecido ou insuficiente", "Medição antiga; verificar novamente", "Modo de jogo bloqueia inferência", "Recursos de cálculo ocupados ou não verificados", "Hybrid exige conexão de nuvem disponível e autorizada", "Modelos devem executar em sequência", "Modelo ausente do catálogo verificado"),
    "ru": ("Нет проверенной среды исполнения модели", "Среда несовместима с системой или архитектурой", "Поддержка этой задачи не проверена", "Нужные инструкции CPU отсутствуют или не проверены", "Доступная память для инференса не проверена", "Общего лимита памяти недостаточно", "Контекст или параллельность превышают проверенный диапазон", "Файлы или контрольные суммы неполны", "Точная лицензия не проверена", "Энкодеру нужен проверенный модуль задачи", "Нужный проектор изображений отсутствует", "Проверка качества не пройдена", "Производительность на этом компьютере не измерена", "Для загрузки нужно ваше согласие", "Место для загрузки и временных файлов неизвестно или недостаточно", "Измерение устарело; повторите проверку", "Игровой режим блокирует инференс", "Вычислительные слоты заняты или не проверены", "Hybrid требует доступного и явно разрешённого облака", "Модели должны работать последовательно", "Модели нет в проверенном каталоге"),
    "ja": ("検証済みの実行環境がありません", "実行環境がOSまたはCPU構成に対応していません", "このタスクへの対応は未検証です", "必要なCPU命令がないか未検証です", "推論に使えるメモリは未検証です", "共有メモリ予算が不足しています", "コンテキストまたは並列数が検証範囲を超えています", "モデルのファイルまたはチェックサムが不完全です", "正確なライセンスは未検証です", "エンコーダーには検証済みのタスク用ヘッドが必要です", "対応する画像プロジェクターがありません", "タスクの品質検証に失敗しました", "この端末での性能は未計測です", "ダウンロードには同意が必要です", "ダウンロードと一時保存の空き容量が不明または不足しています", "測定が古いため再検査してください", "ゲームモードは推論を停止します", "計算枠が使用中または未検証です", "Hybridには利用可能で明示的に許可されたクラウド接続が必要です", "モデルを順番に実行する必要があります", "検証済みカタログにこのモデルはありません"),
}
REASON_CATEGORY = {
    "runtime_missing": "runtime", "runtime_not_verified": "runtime", "runtime_platform_mismatch": "platform",
    "artifact_role_unsupported": "operation", "runtime_operation_missing": "operation", "gpu_backend_unverified": "operation", "gpu_adapter_missing": "operation",
    "cpu_features_unknown": "cpu", "cpu_instruction_unsupported": "cpu", "cpu_profile_has_gpu_allocation": "operation",
    "model_memory_unknown": "memory", "ram_budget_unknown": "memory", "gpu_budget_unknown": "memory", "gpu_budget_scope_unknown": "memory",
    "ram_budget_exceeded": "pressure", "gpu_budget_exceeded": "pressure", "shared_memory_budget_exceeded": "pressure",
    "context_limit_exceeded": "context", "memory_profile_request_unverified": "context",
    "artifact_revision_unpinned": "manifest", "artifact_manifest_incomplete": "manifest", "artifact_file_integrity_unknown": "manifest",
    "artifact_license_unverified": "license", "encoder_task_head_missing": "head", "vision_projector_missing": "projector",
    "model_quality_failed": "quality", "performance_unmeasured": "benchmark", "download_consent_required": "consent",
    "disk_free_unknown": "disk", "disk_budget_exceeded": "disk", "artifact_not_installed": "manifest",
    "hardware_snapshot_stale": "stale", "memory_profile_stale": "stale", "game_mode_blocks_inference": "game_mode",
    "compute_admission_unknown": "admission", "compute_admission_busy": "admission", "hybrid_requires_explicit_cloud_connection": "cloud",
    "models_must_run_sequentially": "sequential", "custom_artifact_unknown": "custom",
}
_ROLE_NAMES = {
    "de": ("Textklassifikation", "Relevante Inhalte finden", "Optionaler Gedächtnisindex", "Strukturierte Daten extrahieren", "Aufgaben mit Werkzeugen", "Bildinhalte verstehen"),
    "en": ("Text classification", "Find relevant content", "Optional memory index", "Extract structured data", "Tasks with tools", "Understand images"),
    "it": ("Classificazione del testo", "Trova contenuti pertinenti", "Indice di memoria opzionale", "Estrai dati strutturati", "Attività con strumenti", "Comprendi immagini"),
    "es": ("Clasificación de texto", "Buscar contenido relevante", "Índice de memoria opcional", "Extraer datos estructurados", "Tareas con herramientas", "Comprender imágenes"),
    "fr": ("Classification de texte", "Trouver du contenu pertinent", "Index mémoire facultatif", "Extraire des données structurées", "Tâches avec outils", "Comprendre les images"),
    "pt-BR": ("Classificação de texto", "Encontrar conteúdo relevante", "Índice de memória opcional", "Extrair dados estruturados", "Tarefas com ferramentas", "Entender imagens"),
    "ru": ("Классификация текста", "Поиск подходящих материалов", "Необязательный индекс памяти", "Извлечение структурированных данных", "Задачи с инструментами", "Понимание изображений"),
    "ja": ("テキスト分類", "関連する内容の検索", "任意のメモリ索引", "構造化データの抽出", "ツールを使ったタスク", "画像の理解"),
}
_SUITABILITY = {
    "de": ("Empfohlen", "Nutzbar", "Langsam", "Speicher reicht nicht aus", "Noch nicht gemessen"),
    "en": ("Recommended", "Usable", "Slow", "Insufficient memory", "Not measured yet"),
    "it": ("Consigliato", "Utilizzabile", "Lento", "Memoria insufficiente", "Non ancora misurato"),
    "es": ("Recomendado", "Utilizable", "Lento", "Memoria insuficiente", "Aún sin medir"),
    "fr": ("Recommandé", "Utilisable", "Lent", "Mémoire insuffisante", "Pas encore mesuré"),
    "pt-BR": ("Recomendado", "Utilizável", "Lento", "Memória insuficiente", "Ainda não medido"),
    "ru": ("Рекомендуется", "Можно использовать", "Медленно", "Недостаточно памяти", "Ещё не измерено"),
    "ja": ("推奨", "利用可能", "低速", "メモリ不足", "未計測"),
}


def local_ai_copy(locale: str) -> dict:
    selected = locale if locale in LOCALES else "en"
    reasons = dict(zip(_REASON_KEYS, _REASON_ROWS[selected]))
    return {"schemaVersion": 1, "locale": selected, "labels": dict(zip(_KEYS, _ROWS[selected])),
            "reasons": {code: reasons[category] for code, category in REASON_CATEGORY.items()},
            "roles": dict(zip(("encoder", "retrieve", "embed", "extract", "agent", "vision"), _ROLE_NAMES[selected])),
            "suitability": dict(zip(("recommended", "usable", "slow", "insufficient_resources", "unmeasured"), _SUITABILITY[selected])),
            "roleUnavailable": reasons["operation"]}
