import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('lastbrowser', {
  services: {
    status: () => ipcRenderer.invoke('lastbrowser:services:status'),
    start: () => ipcRenderer.invoke('lastbrowser:services:start'),
    stop: () => ipcRenderer.invoke('lastbrowser:services:stop')
  },
  setup: {
    load: () => ipcRenderer.invoke('lastbrowser:setup:load'),
    save: (state: unknown) => ipcRenderer.invoke('lastbrowser:setup:save', state)
  },
  browser: {
    onOpenTab: (callback: (url: string) => void) => {
      const listener = (_event: Electron.IpcRendererEvent, url: string) => callback(url);
      ipcRenderer.on('lastbrowser:browser:openTab', listener);
      return () => ipcRenderer.removeListener('lastbrowser:browser:openTab', listener);
    }
  },
  sidekick: {
    onboardingStatus: () => ipcRenderer.invoke('lastbrowser:sidekick:onboardingStatus'),
    applyCloudSetup: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:applyCloudSetup', request),
    setDefaultModel: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:setDefaultModel', request),
    completeCloudSetup: () => ipcRenderer.invoke('lastbrowser:sidekick:completeCloudSetup'),
    startOAuth: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:startOAuth', request),
    pollOAuth: (flowId: string) => ipcRenderer.invoke('lastbrowser:sidekick:pollOAuth', flowId),
    cancelOAuth: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:cancelOAuth', request),
    requestWebui: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:requestWebui', request),
    listSessions: () => ipcRenderer.invoke('lastbrowser:sidekick:listSessions'),
    listSpaces: () => ipcRenderer.invoke('lastbrowser:sidekick:listSpaces'),
    createSession: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createSession', request),
    getSession: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getSession', request),
    renameSession: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:renameSession', request),
    deleteSession: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:deleteSession', request),
    duplicateSession: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:duplicateSession', request),
    getDraft: (sessionId: string) => ipcRenderer.invoke('lastbrowser:sidekick:getDraft', sessionId),
    saveDraft: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:saveDraft', request),
    startChat: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:startChat', request),
    getStreamStatus: (streamId: string) => ipcRenderer.invoke('lastbrowser:sidekick:getStreamStatus', streamId),
    cancelStream: (streamId: string) => ipcRenderer.invoke('lastbrowser:sidekick:cancelStream', streamId),
    listWorkspace: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:listWorkspace', request),
    readWorkspaceFile: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:readWorkspaceFile', request),
    createWorkspaceFile: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createWorkspaceFile', request),
    saveWorkspaceFile: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:saveWorkspaceFile', request),
    renameWorkspaceEntry: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:renameWorkspaceEntry', request),
    createWorkspaceDirectory: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createWorkspaceDirectory', request),
    deleteWorkspaceEntry: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:deleteWorkspaceEntry', request),
    addSpace: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:addSpace', request),
    removeSpace: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:removeSpace', request),
    renameSpace: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:renameSpace', request),
    reorderSpaces: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:reorderSpaces', request),
    listCrons: () => ipcRenderer.invoke('lastbrowser:sidekick:listCrons'),
    createCron: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createCron', request),
    updateCron: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:updateCron', request),
    deleteCron: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:deleteCron', request),
    runCron: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:runCron', request),
    pauseCron: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:pauseCron', request),
    resumeCron: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:resumeCron', request),
    getKanbanBoard: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getKanbanBoard', request),
    createKanbanTask: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createKanbanTask', request),
    updateKanbanTask: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:updateKanbanTask', request),
    runDispatchOnce: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:runDispatchOnce', request),
    getActiveDispatches: () => ipcRenderer.invoke('lastbrowser:sidekick:getActiveDispatches'),
    listSkills: () => ipcRenderer.invoke('lastbrowser:sidekick:listSkills'),
    getSkillContent: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getSkillContent', request),
    saveSkill: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:saveSkill', request),
    deleteSkill: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:deleteSkill', request),
    listAgents: () => ipcRenderer.invoke('lastbrowser:sidekick:listAgents'),
    getActivatedAgents: () => ipcRenderer.invoke('lastbrowser:sidekick:getActivatedAgents'),
    getCurrentAgent: () => ipcRenderer.invoke('lastbrowser:sidekick:getCurrentAgent'),
    setCurrentAgent: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:setCurrentAgent', request),
    getAgentSplashStatus: () => ipcRenderer.invoke('lastbrowser:sidekick:getAgentSplashStatus'),
    completeAgentSplash: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:completeAgentSplash', request),
    answerAgentSplashQuestion: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:answerAgentSplashQuestion', request),
    getAgentStats: () => ipcRenderer.invoke('lastbrowser:sidekick:getAgentStats'),
    getAgentActivities: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getAgentActivities', request),
    getAgentProfiles: () => ipcRenderer.invoke('lastbrowser:sidekick:getAgentProfiles'),
    getAgentWorkspaces: () => ipcRenderer.invoke('lastbrowser:sidekick:getAgentWorkspaces'),
    getAgent: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getAgent', request),
    getAgentMemory: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getAgentMemory', request),
    getAgentSoul: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getAgentSoul', request),
    saveAgentProfile: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:saveAgentProfile', request),
    activateAgent: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:activateAgent', request),
    listAgentSessions: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:listAgentSessions', request),
    getAgentSession: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getAgentSession', request),
    startAgentChat: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:startAgentChat', request),
    listAgentWorkspace: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:listAgentWorkspace', request),
    startAgentWorkspaceProcess: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:startAgentWorkspaceProcess', request),
    sendAgentWorkspaceCommand: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:sendAgentWorkspaceCommand', request),
    stopAgentWorkspace: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:stopAgentWorkspace', request),
    createAgent: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createAgent', request),
    updateAgent: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:updateAgent', request),
    deleteAgent: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:deleteAgent', request),
    startAgentWorkspaceStream: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:startAgentWorkspaceStream', request),
    stopAgentWorkspaceStream: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:stopAgentWorkspaceStream', request),
    onAgentWorkspaceEvent: (callback: (event: unknown) => void) => {
      const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);
      ipcRenderer.on('lastbrowser:sidekick:agentWorkspaceEvent', listener);
      return () => ipcRenderer.removeListener('lastbrowser:sidekick:agentWorkspaceEvent', listener);
    },
    listProfiles: () => ipcRenderer.invoke('lastbrowser:sidekick:listProfiles'),
    switchProfile: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:switchProfile', request),
    createProfile: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createProfile', request),
    deleteProfile: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:deleteProfile', request),
    getMemory: () => ipcRenderer.invoke('lastbrowser:sidekick:getMemory'),
    writeMemory: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:writeMemory', request),
    getSupermemoryStatus: () => ipcRenderer.invoke('lastbrowser:sidekick:getSupermemoryStatus'),
    listSupermemoryDocuments: () => ipcRenderer.invoke('lastbrowser:sidekick:listSupermemoryDocuments'),
    getSupermemoryDocument: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getSupermemoryDocument', request),
    searchSupermemory: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:searchSupermemory', request),
    addSupermemoryDocument: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:addSupermemoryDocument', request),
    forgetSupermemoryDocument: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:forgetSupermemoryDocument', request),
    hybridMemorySearch: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:hybridMemorySearch', request),
    getInsights: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getInsights', request),
    getWikiStatus: () => ipcRenderer.invoke('lastbrowser:sidekick:getWikiStatus'),
    getLogs: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getLogs', request),
    listAppstore: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:listAppstore', request),
    getAppstoreUpdates: () => ipcRenderer.invoke('lastbrowser:sidekick:getAppstoreUpdates'),
    getAppstoreSdk: () => ipcRenderer.invoke('lastbrowser:sidekick:getAppstoreSdk'),
    installAppstoreApp: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:installAppstoreApp', request),
    uninstallAppstoreApp: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:uninstallAppstoreApp', request),
    updateAllAppstore: () => ipcRenderer.invoke('lastbrowser:sidekick:updateAllAppstore'),
    submitAppstoreApp: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:submitAppstoreApp', request),
    getSettings: () => ipcRenderer.invoke('lastbrowser:sidekick:getSettings'),
    saveSettings: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:saveSettings', request),
    listGmailAccounts: () => ipcRenderer.invoke('lastbrowser:sidekick:listGmailAccounts'),
    listGmailMessages: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:listGmailMessages', request),
    readGmailMessage: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:readGmailMessage', request),
    searchGmailMessages: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:searchGmailMessages', request),
    listGmailFolders: () => ipcRenderer.invoke('lastbrowser:sidekick:listGmailFolders'),
    summarizeGmailThread: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:summarizeGmailThread', request),
    draftGmailReply: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:draftGmailReply', request),
    getRelatedGmailMessages: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getRelatedGmailMessages', request),
    sendGmailMessage: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:sendGmailMessage', request),
    deleteGmailMessage: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:deleteGmailMessage', request),
    moveGmailMessage: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:moveGmailMessage', request),
    createGmailTask: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:createGmailTask', request),
    getDiscordGuild: () => ipcRenderer.invoke('lastbrowser:sidekick:getDiscordGuild'),
    listDiscordChannels: () => ipcRenderer.invoke('lastbrowser:sidekick:listDiscordChannels'),
    listDiscordRoles: () => ipcRenderer.invoke('lastbrowser:sidekick:listDiscordRoles'),
    getDiscordStats: () => ipcRenderer.invoke('lastbrowser:sidekick:getDiscordStats'),
    getDiscordMember: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:getDiscordMember', request),
    getDiscordBotInfo: () => ipcRenderer.invoke('lastbrowser:sidekick:getDiscordBotInfo'),
    getDiscordWarns: () => ipcRenderer.invoke('lastbrowser:sidekick:getDiscordWarns'),
    listDiscordChannelsTree: () => ipcRenderer.invoke('lastbrowser:sidekick:listDiscordChannelsTree'),
    listDiscordMembers: (request?: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:listDiscordMembers', request),
    listDiscordMessages: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:listDiscordMessages', request),
    sendDiscordMessage: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:sendDiscordMessage', request),
    warnDiscordMember: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:warnDiscordMember', request),
    timeoutDiscordMember: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:timeoutDiscordMember', request),
    kickDiscordMember: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:kickDiscordMember', request),
    banDiscordMember: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:banDiscordMember', request),
    purgeDiscordChannel: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:purgeDiscordChannel', request),
    untimeoutDiscordMember: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:untimeoutDiscordMember', request),
    unbanDiscordMember: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:unbanDiscordMember', request),
    configureDiscord: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:configureDiscord', request),
    sendMessage: (request: unknown) => ipcRenderer.invoke('lastbrowser:sidekick:sendMessage', request)
  },
  updates: {
    status: () => ipcRenderer.invoke('lastbrowser:updates:status'),
    check: () => ipcRenderer.invoke('lastbrowser:updates:check'),
    download: () => ipcRenderer.invoke('lastbrowser:updates:download'),
    install: () => ipcRenderer.invoke('lastbrowser:updates:install'),
    onStatus: (callback: (status: unknown) => void) => {
      const listener = (_event: Electron.IpcRendererEvent, status: unknown) => callback(status);
      ipcRenderer.on('lastbrowser:updates:status', listener);
      return () => ipcRenderer.removeListener('lastbrowser:updates:status', listener);
    }
  },
  window: {
    minimize: () => ipcRenderer.invoke('lastbrowser:window:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('lastbrowser:window:toggleMaximize'),
    close: () => ipcRenderer.invoke('lastbrowser:window:close')
  }
});
