import type { DesktopLocaleId } from './keys.js';
const keys=['title','origin','label','start','confirm','cancel','logout','logoutReview','refresh','noGrant','clearScope','starting','awaiting_user','user_confirmed','cancelled','expired','interrupted','revoking','revoked','invalidOrigin','unavailable'] as const;
const rows:Record<DesktopLocaleId,readonly string[]>={
 en:['Task-browser accounts','Website origin','Account label (optional)','Open sign-in window','I have signed in here','Cancel setup','Sign out','Confirm sign-out','Refresh','Account setup does not grant permission to act. Bind the selected account uses separately.','Signing out clears this Space’s entire task-browser session and invalidates its other account confirmations. Your normal browser and other Spaces are preserved.','Opening sign-in window','Waiting for your sign-in and confirmation','Confirmed by you','Setup cancelled','Setup expired','Setup interrupted','Signing out','Signed out','Enter an exact HTTP(S) origin without a path, query or credentials.','Account setup is unavailable; refresh to retry.'],
 de:['Konten im Auftragsbrowser','Website-Origin','Kontobezeichnung (optional)','Anmeldefenster öffnen','Ich habe mich hier angemeldet','Einrichtung abbrechen','Abmelden','Abmelden bestätigen','Aktualisieren','Die Kontoeinrichtung erteilt keine Handlungserlaubnis. Gewünschte Kontonutzungen separat zuordnen.','Abmelden leert die gesamte Auftragsbrowser-Sitzung dieses Space und entwertet dessen weitere Kontobestätigungen. Normaler Browser und andere Spaces bleiben erhalten.','Anmeldefenster wird geöffnet','Wartet auf deine Anmeldung und Bestätigung','Von dir bestätigt','Einrichtung abgebrochen','Einrichtung abgelaufen','Einrichtung unterbrochen','Wird abgemeldet','Abgemeldet','Exakten HTTP(S)-Origin ohne Pfad, Query oder Zugangsdaten eingeben.','Kontoeinrichtung nicht verfügbar; aktualisieren und erneut versuchen.'],
 es:['Cuentas del navegador de tareas','Origen del sitio web','Nombre de la cuenta (opcional)','Abrir ventana de acceso','He iniciado sesión aquí','Cancelar configuración','Cerrar sesión','Confirmar cierre de sesión','Actualizar','Configurar una cuenta no concede permiso para actuar. Vincula por separado los usos de cuenta elegidos.','Cerrar sesión vacía la sesión completa del navegador de tareas de este Space e invalida sus otras confirmaciones. Tu navegador habitual y otros Spaces se conservan.','Abriendo ventana de acceso','Esperando tu acceso y confirmación','Confirmado por ti','Configuración cancelada','Configuración caducada','Configuración interrumpida','Cerrando sesión','Sesión cerrada','Introduce un origen HTTP(S) exacto sin ruta, consulta ni credenciales.','Configuración no disponible; actualiza para reintentar.'],
 fr:['Comptes du navigateur de tâches','Origine du site','Nom du compte (facultatif)','Ouvrir la fenêtre de connexion','Je me suis connecté ici','Annuler la configuration','Déconnexion','Confirmer la déconnexion','Actualiser','La configuration d’un compte n’autorise aucune action. Associez séparément les usages du compte choisis.','La déconnexion vide toute la session du navigateur de tâches de ce Space et invalide ses autres confirmations. Votre navigateur habituel et les autres Spaces sont préservés.','Ouverture de la fenêtre de connexion','Attend votre connexion et confirmation','Confirmé par vous','Configuration annulée','Configuration expirée','Configuration interrompue','Déconnexion en cours','Déconnecté','Saisissez une origine HTTP(S) exacte, sans chemin, requête ou identifiants.','Configuration indisponible ; actualisez pour réessayer.'],
 it:['Account del browser delle attività','Origine del sito','Nome dell’account (facoltativo)','Apri finestra di accesso','Ho effettuato l’accesso qui','Annulla configurazione','Esci','Conferma uscita','Aggiorna','La configurazione dell’account non autorizza azioni. Associa separatamente gli usi scelti dell’account.','L’uscita cancella l’intera sessione del browser delle attività di questo Space e invalida le altre conferme. Il browser normale e gli altri Space restano invariati.','Apertura della finestra di accesso','In attesa del tuo accesso e della conferma','Confermato da te','Configurazione annullata','Configurazione scaduta','Configurazione interrotta','Uscita in corso','Disconnesso','Inserisci un’origine HTTP(S) esatta senza percorso, query o credenziali.','Configurazione non disponibile; aggiorna e riprova.'],
 'pt-BR':['Contas do navegador de tarefas','Origem do site','Nome da conta (opcional)','Abrir janela de login','Entrei na conta aqui','Cancelar configuração','Sair','Confirmar saída','Atualizar','Configurar a conta não concede permissão para agir. Vincule separadamente os usos escolhidos.','Sair limpa toda a sessão do navegador de tarefas deste Space e invalida suas outras confirmações. Seu navegador normal e outros Spaces são preservados.','Abrindo janela de login','Aguardando seu login e confirmação','Confirmado por você','Configuração cancelada','Configuração expirada','Configuração interrompida','Saindo','Desconectado','Insira uma origem HTTP(S) exata sem caminho, consulta ou credenciais.','Configuração indisponível; atualize para tentar novamente.'],
 ru:['Аккаунты браузера задач','Источник сайта','Название аккаунта (необязательно)','Открыть окно входа','Я вошёл здесь','Отменить настройку','Выйти','Подтвердить выход','Обновить','Настройка аккаунта не разрешает действия. Отдельно привяжите выбранные способы использования аккаунта.','Выход очищает всю сессию браузера задач этого Space и отменяет другие подтверждения аккаунтов. Обычный браузер и другие Spaces сохраняются.','Открывается окно входа','Ожидается ваш вход и подтверждение','Подтверждено вами','Настройка отменена','Настройка истекла','Настройка прервана','Выход выполняется','Выполнен выход','Введите точный источник HTTP(S) без пути, запроса или учётных данных.','Настройка недоступна; обновите и повторите попытку.'],
 ja:['作業用ブラウザーのアカウント','サイトのオリジン','アカウント名（任意）','ログイン画面を開く','この画面でログインしました','設定をキャンセル','ログアウト','ログアウトを確認','更新','アカウントの設定だけでは操作を許可しません。許可するアカウントの用途は別に関連付けてください。','ログアウトすると、このSpaceの作業用ブラウザー全体のセッションを消去し、他のアカウント確認も無効にします。通常のブラウザーと他のSpaceは保持します。','ログイン画面を開いています','ログインとあなたの確認を待っています','あなたが確認済み','設定をキャンセルしました','設定の有効期限が切れました','設定が中断されました','ログアウトしています','ログアウトしました','パス、クエリ、認証情報を含まない正確なHTTP(S)オリジンを入力してください。','設定を利用できません。更新して再試行してください。'],
};
export const browserAccountCopy=(locale:DesktopLocaleId)=>Object.fromEntries(keys.map((key,index)=>[key,rows[locale][index]])) as Record<typeof keys[number],string>;
export const browserAccountUseCopy:Record<DesktopLocaleId,string>={en:'Use this account in task browsing',de:'Dieses Konto für Auftragsbrowser nutzen',es:'Usar esta cuenta en el navegador de tareas',fr:'Utiliser ce compte pour la navigation des tâches',it:'Usa questo account nel browser delle attività','pt-BR':'Usar esta conta no navegador de tarefas',ru:'Использовать аккаунт в браузере задач',ja:'作業用ブラウザーでこのアカウントを使用する'};
export const browserAccountRecoveryCopy:Record<DesktopLocaleId,Readonly<{unknown:string;retry:string}>>={
 en:{unknown:'The sign-in start has not been acknowledged. Retry the same request to recover its actual state; no sign-in is confirmed automatically.',retry:'Recover this sign-in request'},
 de:{unknown:'Der Anmeldestart wurde noch nicht bestätigt. Wiederhole denselben Auftrag, um den tatsächlichen Zustand abzurufen. Die Anmeldung wird nicht automatisch bestätigt.',retry:'Diesen Anmeldeauftrag wiederaufnehmen'},
 es:{unknown:'El inicio del acceso no se ha confirmado. Repite la misma solicitud para recuperar su estado real; el acceso no se confirma automáticamente.',retry:'Recuperar esta solicitud de acceso'},
 fr:{unknown:'Le démarrage de la connexion n’a pas été confirmé. Réessayez la même demande pour retrouver son état réel ; aucune connexion n’est confirmée automatiquement.',retry:'Reprendre cette demande de connexion'},
 it:{unknown:'L’avvio dell’accesso non è stato confermato. Ripeti la stessa richiesta per recuperarne lo stato reale; l’accesso non viene confermato automaticamente.',retry:'Riprendi questa richiesta di accesso'},
 'pt-BR':{unknown:'O início do login ainda não foi confirmado. Repita a mesma solicitação para recuperar o estado real; o login não é confirmado automaticamente.',retry:'Recuperar esta solicitação de login'},
 ru:{unknown:'Начало входа ещё не подтверждено. Повторите тот же запрос, чтобы получить его фактическое состояние. Вход не подтверждается автоматически.',retry:'Восстановить этот запрос входа'},
 ja:{unknown:'ログインの開始応答をまだ受信していません。同じ要求を再試行して実際の状態を確認してください。ログインを自動で確認することはありません。',retry:'このログイン要求を再開'},
};
