import type { DesktopCatalog, LegacyDesktopLocaleId as DesktopLocaleId, DesktopTranslationKey } from './keys.js';

const rows: Partial<Record<DesktopTranslationKey, Record<DesktopLocaleId, string>>> = {
  'settings.panels.providers.geminiSubscriptionTitle': { en: 'Gemini subscription access changed', de: 'Gemini-Abozugriff wurde geändert', es: 'Cambió el acceso de suscripción a Gemini', fr: 'L’accès Gemini par abonnement a changé', it: 'È cambiato l’accesso Gemini con abbonamento', 'pt-BR': 'O acesso à Gemini por assinatura mudou', ru: 'Доступ Gemini по подписке изменился' },
  'settings.panels.providers.geminiSubscriptionMigration': { en: 'Since June 18, 2026, Gemini CLI no longer serves individual/free accounts or Google AI Pro and Ultra subscriptions. Google directs consumers to Antigravity CLI. Gemini Code Assist Standard and Enterprise access is unaffected. Lastbrowser does not offer a Gemini or Antigravity subscription connector.', de: 'Seit dem 18. Juni 2026 bedient Gemini CLI keine Einzel-/Gratis-Konten und Google-AI-Pro- oder-Ultra-Abos mehr. Google verweist Privatnutzer auf Antigravity CLI. Gemini Code Assist Standard und Enterprise sind nicht betroffen. Lastbrowser bietet keine Gemini- oder Antigravity-Aboanbindung.', es: 'Desde el 18 de junio de 2026, Gemini CLI dejó de atender cuentas individuales/gratuitas y suscripciones Google AI Pro y Ultra. Google dirige a los consumidores a Antigravity CLI. Gemini Code Assist Standard y Enterprise no se ven afectados. Lastbrowser no ofrece conexión de suscripción a Gemini ni Antigravity.', fr: 'Depuis le 18 juin 2026, Gemini CLI ne répond plus aux comptes individuels/gratuits ni aux abonnements Google AI Pro et Ultra. Google oriente les particuliers vers Antigravity CLI. Gemini Code Assist Standard et Enterprise ne sont pas concernés. Lastbrowser ne propose pas de connexion d’abonnement Gemini ou Antigravity.', it: 'Dal 18 giugno 2026 Gemini CLI non serve più gli account individuali/gratuiti né gli abbonamenti Google AI Pro e Ultra. Google indirizza i consumatori a Antigravity CLI. Gemini Code Assist Standard ed Enterprise non sono interessati. Lastbrowser non offre un collegamento agli abbonamenti Gemini o Antigravity.', 'pt-BR': 'Desde 18 de junho de 2026, a Gemini CLI não atende mais contas individuais/gratuitas nem assinaturas Google AI Pro e Ultra. O Google direciona consumidores para a Antigravity CLI. O Gemini Code Assist Standard e Enterprise não foram afetados. O Lastbrowser não oferece conexão de assinatura Gemini ou Antigravity.', ru: 'С 18 июня 2026 года Gemini CLI больше не обслуживает индивидуальные/бесплатные аккаунты и подписки Google AI Pro и Ultra. Google направляет пользователей на Antigravity CLI. Gemini Code Assist Standard и Enterprise не затронуты. Lastbrowser не подключает подписки Gemini или Antigravity.' },
  'settings.panels.providers.geminiSubscriptionDocs': { en: 'Antigravity CLI migration guide', de: 'Migrationsanleitung für Antigravity CLI', es: 'Guía de migración a Antigravity CLI', fr: 'Guide de migration vers Antigravity CLI', it: 'Guida alla migrazione ad Antigravity CLI', 'pt-BR': 'Guia de migração da Antigravity CLI', ru: 'Руководство по переходу на Antigravity CLI' },
  'settings.panels.providers.geminiSubscriptionAnnouncement': { en: 'Google announcement', de: 'Google-Ankündigung', es: 'Anuncio de Google', fr: 'Annonce de Google', it: 'Annuncio di Google', 'pt-BR': 'Anúncio do Google', ru: 'Объявление Google' },
  'settings.panels.providers.geminiSubscriptionApiKey': { en: 'Gemini API-key access is configured separately and may have separate billing.', de: 'Gemini-Zugriff per API-Schlüssel wird separat eingerichtet und kann separat abgerechnet werden.', es: 'El acceso a Gemini con clave API se configura por separado y puede tener facturación independiente.', fr: 'L’accès Gemini par clé API se configure séparément et peut entraîner une facturation distincte.', it: 'L’accesso Gemini tramite chiave API si configura separatamente e può avere una fatturazione distinta.', 'pt-BR': 'O acesso à Gemini por chave de API é configurado separadamente e pode ter cobrança própria.', ru: 'Доступ Gemini по API-ключу настраивается отдельно и может оплачиваться отдельно.' },
  'settings.panels.providers.antigravityRoundRobinHint': { en: 'Connect one or more Google accounts; chat requests rotate round-robin across all connected accounts.', de: 'Verbinde ein oder mehrere Google-Konten; Chat-Anfragen rotieren im Round-Robin über alle verbundenen Konten.', es: 'Conecta una o más cuentas de Google; las solicitudes de chat rotan en round-robin entre todas las cuentas conectadas.', fr: 'Connectez un ou plusieurs comptes Google ; les requêtes de chat tournent en round-robin entre tous les comptes connectés.', it: 'Collega uno o più account Google; le richieste di chat ruotano in round-robin tra tutti gli account collegati.', 'pt-BR': 'Conecte uma ou mais contas do Google; as solicitações de chat alternam em round-robin entre todas as contas conectadas.', ru: 'Подключите один или несколько аккаунтов Google; запросы чата распределяются по кругу между всеми подключёнными аккаунтами.' },
  'settings.panels.providers.antigravityAddAccount': { en: 'Add Google account', de: 'Google-Konto hinzufügen', es: 'Añadir cuenta de Google', fr: 'Ajouter un compte Google', it: 'Aggiungi account Google', 'pt-BR': 'Adicionar conta do Google', ru: 'Добавить аккаунт Google' },
  'settings.panels.providers.antigravityEmptyHint': { en: 'No Antigravity account connected yet. Add one to use Gemini models with your Google account.', de: 'Noch kein Antigravity-Konto verbunden. Füge eines hinzu, um Gemini-Modelle mit deinem Google-Konto zu nutzen.', es: 'Aún no hay ninguna cuenta de Antigravity conectada. Añade una para usar modelos Gemini con tu cuenta de Google.', fr: 'Aucun compte Antigravity connecté pour le moment. Ajoutez-en un pour utiliser les modèles Gemini avec votre compte Google.', it: 'Nessun account Antigravity collegato. Aggiungine uno per usare i modelli Gemini con il tuo account Google.', 'pt-BR': 'Nenhuma conta do Antigravity conectada ainda. Adicione uma para usar os modelos Gemini com sua conta do Google.', ru: 'Аккаунт Antigravity ещё не подключён. Добавьте его, чтобы использовать модели Gemini со своим аккаунтом Google.' },
  'settings.panels.providers.antigravityStarting': { en: 'Starting Google sign-in…', de: 'Google-Anmeldung wird gestartet…', es: 'Iniciando el inicio de sesión de Google…', fr: 'Démarrage de la connexion Google…', it: 'Avvio dell’accesso a Google…', 'pt-BR': 'Iniciando o login do Google…', ru: 'Запуск входа в Google…' },
  'settings.panels.providers.antigravityWaiting': { en: 'Waiting for sign-in to complete in your browser…', de: 'Warte auf die Anmeldung in deinem Browser…', es: 'Esperando a que se complete el inicio de sesión en tu navegador…', fr: 'En attente de la connexion dans votre navigateur…', it: 'In attesa del completamento dell’accesso nel browser…', 'pt-BR': 'Aguardando a conclusão do login no seu navegador…', ru: 'Ожидание завершения входа в браузере…' }
};

export const geminiSubscriptionTranslations: Record<DesktopLocaleId, DesktopCatalog> = Object.fromEntries(
  (['en', 'de', 'it', 'es', 'fr', 'pt-BR', 'ru'] as DesktopLocaleId[]).map((locale) => [locale, Object.fromEntries(Object.entries(rows).map(([key, translations]) => [key, translations[locale]]))])
) as Record<DesktopLocaleId, DesktopCatalog>;
