import type { DesktopCatalog, LegacyDesktopLocaleId as DesktopLocaleId, DesktopTranslationKey } from './keys.js';

const rows: Partial<Record<DesktopTranslationKey, Record<DesktopLocaleId, string>>> = {
  'settings.panels.providers.geminiSubscriptionTitle': { en: 'Gemini subscription access changed', de: 'Gemini-Abozugriff wurde geändert', es: 'Cambió el acceso de suscripción a Gemini', fr: 'L’accès Gemini par abonnement a changé', it: 'È cambiato l’accesso Gemini con abbonamento', 'pt-BR': 'O acesso à Gemini por assinatura mudou', ru: 'Доступ Gemini по подписке изменился' },
  'settings.panels.providers.geminiSubscriptionMigration': { en: 'Since June 18, 2026, Gemini CLI no longer serves individual/free accounts or Google AI Pro and Ultra subscriptions. Google directs consumers to Antigravity CLI. Gemini Code Assist Standard and Enterprise access is unaffected. LastBrowser does not offer a Gemini or Antigravity subscription connector.', de: 'Seit dem 18. Juni 2026 bedient Gemini CLI keine Einzel-/Gratis-Konten und Google-AI-Pro- oder-Ultra-Abos mehr. Google verweist Privatnutzer auf Antigravity CLI. Gemini Code Assist Standard und Enterprise sind nicht betroffen. LastBrowser bietet keine Gemini- oder Antigravity-Aboanbindung.', es: 'Desde el 18 de junio de 2026, Gemini CLI dejó de atender cuentas individuales/gratuitas y suscripciones Google AI Pro y Ultra. Google dirige a los consumidores a Antigravity CLI. Gemini Code Assist Standard y Enterprise no se ven afectados. LastBrowser no ofrece conexión de suscripción a Gemini ni Antigravity.', fr: 'Depuis le 18 juin 2026, Gemini CLI ne répond plus aux comptes individuels/gratuits ni aux abonnements Google AI Pro et Ultra. Google oriente les particuliers vers Antigravity CLI. Gemini Code Assist Standard et Enterprise ne sont pas concernés. LastBrowser ne propose pas de connexion d’abonnement Gemini ou Antigravity.', it: 'Dal 18 giugno 2026 Gemini CLI non serve più gli account individuali/gratuiti né gli abbonamenti Google AI Pro e Ultra. Google indirizza i consumatori a Antigravity CLI. Gemini Code Assist Standard ed Enterprise non sono interessati. LastBrowser non offre un collegamento agli abbonamenti Gemini o Antigravity.', 'pt-BR': 'Desde 18 de junho de 2026, a Gemini CLI não atende mais contas individuais/gratuitas nem assinaturas Google AI Pro e Ultra. O Google direciona consumidores para a Antigravity CLI. O Gemini Code Assist Standard e Enterprise não foram afetados. O LastBrowser não oferece conexão de assinatura Gemini ou Antigravity.', ru: 'С 18 июня 2026 года Gemini CLI больше не обслуживает индивидуальные/бесплатные аккаунты и подписки Google AI Pro и Ultra. Google направляет пользователей на Antigravity CLI. Gemini Code Assist Standard и Enterprise не затронуты. LastBrowser не подключает подписки Gemini или Antigravity.' },
  'settings.panels.providers.geminiSubscriptionDocs': { en: 'Antigravity CLI migration guide', de: 'Migrationsanleitung für Antigravity CLI', es: 'Guía de migración a Antigravity CLI', fr: 'Guide de migration vers Antigravity CLI', it: 'Guida alla migrazione ad Antigravity CLI', 'pt-BR': 'Guia de migração da Antigravity CLI', ru: 'Руководство по переходу на Antigravity CLI' },
  'settings.panels.providers.geminiSubscriptionAnnouncement': { en: 'Google announcement', de: 'Google-Ankündigung', es: 'Anuncio de Google', fr: 'Annonce de Google', it: 'Annuncio di Google', 'pt-BR': 'Anúncio do Google', ru: 'Объявление Google' },
  'settings.panels.providers.geminiSubscriptionApiKey': { en: 'Gemini API key access requires separate setup and may incur separate charges.', de: 'Der Zugriff mit einem Gemini-API-Schlüssel muss separat eingerichtet werden und kann zusätzliche Kosten verursachen.', es: 'El acceso mediante una clave de API de Gemini requiere una configuración aparte y puede generar cargos adicionales.', fr: 'L’accès avec une clé API Gemini nécessite une configuration distincte et peut entraîner des frais supplémentaires.', it: 'L’accesso tramite chiave API Gemini richiede una configurazione separata e potrebbe comportare costi aggiuntivi.', 'pt-BR': 'O acesso com uma chave de API do Gemini requer configuração separada e pode gerar cobranças adicionais.', ru: 'Для доступа с ключом API Gemini требуется отдельная настройка; он может повлечь дополнительные расходы.' },
  'settings.panels.providers.antigravityRoundRobinHint': { en: 'Connect one or more Google accounts for Antigravity. Model selection and account usage require a verified provider catalog.', de: 'Verbinde ein oder mehrere Google-Konten für Antigravity. Modellauswahl und Kontonutzung erfordern einen verifizierten Anbieterkatalog.', es: 'Conecta una o más cuentas de Google para Antigravity. La selección de modelos y el uso de cuentas requieren un catálogo verificado del proveedor.', fr: 'Connectez un ou plusieurs comptes Google pour Antigravity. La sélection de modèles et l’utilisation des comptes nécessitent un catalogue vérifié du fournisseur.', it: 'Collega uno o più account Google per Antigravity. La selezione dei modelli e l’uso degli account richiedono un catalogo verificato del provider.', 'pt-BR': 'Conecte uma ou mais contas do Google para Antigravity. A seleção de modelos e o uso de contas exigem um catálogo verificado do provedor.', ru: 'Подключите один или несколько аккаунтов Google для Antigravity. Выбор моделей и использование аккаунтов требуют подтверждённого каталога провайдера.' },
  'settings.panels.providers.googleAccountsRoundRobin': { en: 'Account rotation', de: 'Kontenrotation', es: 'Rotación de cuentas', fr: 'Rotation des comptes', it: 'Rotazione account', 'pt-BR': 'Rotação de contas', ru: 'Ротация аккаунтов' },
  'settings.panels.providers.googleAccountsRoundRobinDescription': { en: 'Chat requests rotate across usable connected accounts.', de: 'Chat-Anfragen rotieren über nutzbare verbundene Konten.', es: 'Las solicitudes de chat rotan entre las cuentas conectadas utilizables.', fr: 'Les requêtes de chat tournent entre les comptes connectés utilisables.', it: 'Le richieste di chat ruotano tra gli account collegati utilizzabili.', 'pt-BR': 'As solicitações de chat alternam entre as contas conectadas utilizáveis.', ru: 'Запросы чата распределяются между доступными подключёнными аккаунтами.' },
  'settings.panels.providers.antigravityAddAccount': { en: 'Add Google account', de: 'Google-Konto hinzufügen', es: 'Añadir cuenta de Google', fr: 'Ajouter un compte Google', it: 'Aggiungi account Google', 'pt-BR': 'Adicionar conta do Google', ru: 'Добавить аккаунт Google' },
  'settings.panels.providers.antigravityEmptyHint': { en: 'No Antigravity account connected yet. Add a Google account to manage its connection here.', de: 'Noch kein Antigravity-Konto verbunden. Füge ein Google-Konto hinzu, um die Verbindung hier zu verwalten.', es: 'Aún no hay ninguna cuenta de Antigravity conectada. Añade una cuenta de Google para gestionar aquí la conexión.', fr: 'Aucun compte Antigravity connecté pour le moment. Ajoutez un compte Google pour gérer la connexion ici.', it: 'Nessun account Antigravity collegato. Aggiungi un account Google per gestire qui la connessione.', 'pt-BR': 'Nenhuma conta do Antigravity conectada ainda. Adicione uma conta do Google para gerenciar a conexão aqui.', ru: 'Аккаунт Antigravity ещё не подключён. Добавьте аккаунт Google, чтобы управлять подключением здесь.' },
  'settings.panels.providers.antigravityStarting': { en: 'Starting Google sign-in…', de: 'Google-Anmeldung wird gestartet…', es: 'Iniciando el inicio de sesión de Google…', fr: 'Démarrage de la connexion Google…', it: 'Avvio dell’accesso a Google…', 'pt-BR': 'Iniciando o login do Google…', ru: 'Запуск входа в Google…' },
  'settings.panels.providers.antigravityWaiting': { en: 'Waiting for sign-in to complete in your browser…', de: 'Warte auf die Anmeldung in deinem Browser…', es: 'Esperando a que se complete el inicio de sesión en tu navegador…', fr: 'En attente de la connexion dans votre navigateur…', it: 'In attesa del completamento dell’accesso nel browser…', 'pt-BR': 'Aguardando a conclusão do login no seu navegador…', ru: 'Ожидание завершения входа в браузере…' },
  'settings.panels.providers.antigravityReconnectRequired': { en: 'reconnect required', de: 'erneute Verbindung erforderlich', es: 'reconexión requerida', fr: 'reconnexion requise', it: 'riconnessione richiesta', 'pt-BR': 'reconexão necessária', ru: 'требуется повторное подключение' },
  'settings.panels.providers.antigravityCatalogUnavailable': { en: 'No Antigravity models are currently selectable because the model catalog is unavailable.', de: 'Derzeit sind keine Antigravity-Modelle auswählbar, da der Modellkatalog nicht verfügbar ist.', es: 'No se pueden seleccionar modelos de Antigravity ahora porque el catálogo no está disponible.', fr: 'Aucun modèle Antigravity ne peut être sélectionné actuellement, car le catalogue est indisponible.', it: 'Al momento non è possibile selezionare modelli Antigravity perché il catalogo non è disponibile.', 'pt-BR': 'Nenhum modelo do Antigravity pode ser selecionado no momento porque o catálogo está indisponível.', ru: 'Сейчас нельзя выбрать модели Antigravity, так как каталог недоступен.' },
  'settings.panels.providers.antigravityCatalogUnknown': { en: 'Antigravity catalog status could not be verified; its models are not selectable.', de: 'Der Status des Antigravity-Katalogs konnte nicht überprüft werden; seine Modelle sind nicht auswählbar.', es: 'No se pudo verificar el estado del catálogo de Antigravity; sus modelos no están disponibles para seleccionar.', fr: 'Impossible de vérifier l’état du catalogue Antigravity ; ses modèles ne sont pas sélectionnables.', it: 'Impossibile verificare lo stato del catalogo Antigravity; i relativi modelli non sono selezionabili.', 'pt-BR': 'Não foi possível verificar o status do catálogo do Antigravity; os modelos não podem ser selecionados.', ru: 'Не удалось проверить статус каталога Antigravity; его модели недоступны для выбора.' },
  'settings.panels.providers.antigravityCatalogReady': { en: 'Available live models', de: 'Verfügbare Live-Modelle', es: 'Modelos en vivo disponibles', fr: 'Modèles en direct disponibles', it: 'Modelli live disponibili', 'pt-BR': 'Modelos ao vivo disponíveis', ru: 'Доступные модели' }
};

export const geminiSubscriptionTranslations: Record<DesktopLocaleId, DesktopCatalog> = Object.fromEntries(
  (['en', 'de', 'it', 'es', 'fr', 'pt-BR', 'ru'] as DesktopLocaleId[]).map((locale) => [locale, Object.fromEntries(Object.entries(rows).map(([key, translations]) => [key, translations[locale]]))])
) as Record<DesktopLocaleId, DesktopCatalog>;
