import type { DesktopLocaleId } from './keys.js';
import { localAiReason } from './local-ai-copy.js';
const keys=['title','explain','review','start','retry','unknown','expired','complete','technical','synthetic','loaded','stopped','noHandles','scan','reserve','cold','latency','peak','inspect','budget'] as const;
const rows:Record<DesktopLocaleId,readonly string[]>={
 en:['Local runtime test','Choose an installed artifact and task. A fresh hardware scan is followed by a review. The separate confirmation starts one bounded CPU test.','Review local test','Start local test','Retry the same test request','The outcome is unconfirmed. Keep this request identity; do not start a second test.','The review expired. Review again before starting a new test.','Technical test completed','This single sample checks the operation format and observes memory use. Quality, speed targets, full context capacity and memory limits remain unverified. It does not enable inference or an automatic recommendation.','Synthetic test evidence','Process loaded','Process stopped','No owned runtime processes reported','Fresh hardware scan','RAM limit','Cold start','Sample latency','Observed peak memory','Refresh process status','Time budget'],
 de:['Lokalen Laufzeittest prüfen','Wähle eine installierte Datei und Aufgabe. Auf eine neue Hardwareprüfung folgt die Prüfung des Auftrags. Erst die separate Bestätigung startet einen begrenzten CPU-Test.','Lokalen Test prüfen','Lokalen Test starten','Dieselbe Testanfrage wiederholen','Das Ergebnis ist unbestätigt. Behalte diese Anfragekennung; starte keinen zweiten Test.','Die Prüfung ist abgelaufen. Prüfe den Auftrag erneut, bevor du einen neuen Test startest.','Technischer Test abgeschlossen','Diese einzelne Stichprobe prüft das Ausgabeformat und beobachtet den Speicherverbrauch. Qualität, Geschwindigkeitsziele, volle Kontextkapazität und Speichergrenzen bleiben ungeprüft. Sie aktiviert keine Inferenz oder automatische Empfehlung.','Synthetischer Testnachweis','Prozess geladen','Prozess gestoppt','Keine eigenen Laufzeitprozesse gemeldet','Neue Hardwareprüfung','RAM-Grenze','Kaltstart','Latenz der Stichprobe','Beobachteter Spitzenverbrauch','Prozessstatus aktualisieren','Zeitbudget'],
 es:['Prueba del motor local','Elige un archivo instalado y una tarea. Se comprobará el hardware y podrás revisar la solicitud. Una confirmación separada inicia una prueba limitada de CPU.','Revisar prueba local','Iniciar prueba local','Repetir la misma solicitud','El resultado no está confirmado. Conserva esta identidad y no inicies una segunda prueba.','La revisión caducó. Revisa de nuevo antes de iniciar otra prueba.','Prueba técnica completada','Una muestra comprueba el formato de salida y observa la memoria. La calidad, los objetivos de velocidad, el contexto completo y los límites de memoria siguen sin verificar. No habilita inferencia ni recomendaciones automáticas.','Resultado de prueba sintética','Proceso cargado','Proceso detenido','No se informan procesos propios','Nueva comprobación de hardware','Límite de RAM','Arranque en frío','Latencia de la muestra','Pico de memoria observado','Actualizar procesos','Tiempo máximo'],
 fr:['Test du moteur local','Choisissez un fichier installé et une tâche. Un contrôle matériel récent précède la vérification de la demande. Une confirmation distincte démarre un test CPU limité.','Vérifier le test local','Démarrer le test local','Réessayer la même demande','Le résultat n’est pas confirmé. Conservez cette identité et ne lancez pas un second test.','La vérification a expiré. Vérifiez à nouveau avant un nouveau test.','Test technique terminé','Un échantillon vérifie le format de sortie et observe la mémoire. La qualité, les objectifs de vitesse, le contexte complet et les limites mémoire restent non vérifiés. Aucun accès à l’inférence ni recommandation automatique n’en découle.','Résultat de test synthétique','Processus chargé','Processus arrêté','Aucun processus propre signalé','Nouveau contrôle matériel','Limite RAM','Démarrage à froid','Latence de l’échantillon','Pic mémoire observé','Actualiser les processus','Durée maximale'],
 it:['Test del runtime locale','Scegli un file installato e un’attività. Una nuova verifica hardware precede il controllo della richiesta. Una conferma separata avvia un test CPU limitato.','Controlla test locale','Avvia test locale','Ripeti la stessa richiesta','L’esito non è confermato. Conserva questa identità e non avviare un secondo test.','La verifica è scaduta. Controlla di nuovo prima di un nuovo test.','Test tecnico completato','Un campione verifica il formato e osserva la memoria. Qualità, obiettivi di velocità, contesto completo e limiti di memoria restano non verificati. Non abilita inferenza o consigli automatici.','Risultato di test sintetico','Processo caricato','Processo arrestato','Nessun processo proprio segnalato','Nuova verifica hardware','Limite RAM','Avvio a freddo','Latenza del campione','Picco memoria osservato','Aggiorna processi','Tempo massimo'],
 'pt-BR':['Teste do runtime local','Escolha um arquivo instalado e uma tarefa. Uma nova verificação de hardware precede a revisão do pedido. Uma confirmação separada inicia um teste limitado de CPU.','Revisar teste local','Iniciar teste local','Repetir a mesma solicitação','O resultado não foi confirmado. Mantenha esta identidade e não inicie outro teste.','A revisão expirou. Revise novamente antes de iniciar outro teste.','Teste técnico concluído','Uma amostra verifica o formato e observa a memória. Qualidade, metas de velocidade, contexto completo e limites de memória continuam sem verificação. Isso não habilita inferência nem recomendação automática.','Resultado de teste sintético','Processo carregado','Processo parado','Nenhum processo próprio informado','Nova verificação de hardware','Limite de RAM','Inicialização a frio','Latência da amostra','Pico de memória observado','Atualizar processos','Tempo máximo'],
 ru:['Проверка локальной среды','Выберите установленный файл и задачу. Новая проверка оборудования предшествует просмотру запроса. Отдельное подтверждение запускает ограниченный CPU-тест.','Проверить локальный тест','Запустить локальный тест','Повторить тот же запрос','Результат не подтверждён. Сохраните этот идентификатор и не запускайте второй тест.','Срок проверки истёк. Проверьте запрос заново перед новым тестом.','Технический тест завершён','Один образец проверяет формат результата и наблюдает память. Качество, целевая скорость, полный контекст и пределы памяти не проверены. Инференс и автоматические рекомендации не включаются.','Результат синтетического теста','Процесс загружен','Процесс остановлен','Собственные процессы не обнаружены','Новая проверка оборудования','Предел RAM','Холодный запуск','Задержка образца','Наблюдаемый пик памяти','Обновить процессы','Лимит времени'],
 ja:['ローカルランタイムテスト','インストール済みファイルとタスクを選びます。ハードウェアを再確認した後に要求を確認し、別の確認操作で制限付きCPUテストを開始します。','ローカルテストを確認','ローカルテストを開始','同じテスト要求を再試行','結果を確認できませんでした。この要求IDを保持し、別のテストを開始しないでください。','確認の有効期限が切れました。新しいテストの前にもう一度確認してください。','技術テスト完了','1件のサンプルで出力形式とメモリ使用量を確認します。品質、速度目標、コンテキスト全体の容量、メモリ制限は未検証です。推論や自動推奨を有効にするものではありません。','合成テストの結果','プロセス読み込み済み','プロセス停止済み','このSpaceのランタイムプロセスは報告されていません','ハードウェアを再確認','RAM上限','コールドスタート','サンプルのレイテンシ','観測した最大メモリ','プロセス状態を更新','制限時間'],
};
const recovery:Record<DesktopLocaleId,Readonly<{retry:string;running:string;install:string;stopUnknown:string;artifact:string}>>={
 en:{retry:'Check the existing test result',running:'This test is still reported as running. Its existing result will be checked without starting another test.',install:'Complete the download first. The review then checks this exact artifact and its runtime support.',stopUnknown:'Stop is unconfirmed. Refresh the process status; resources have not been confirmed as released.',artifact:'Model file'},
 de:{retry:'Vorhandenes Testergebnis prüfen',running:'Dieser Test wird noch als laufend gemeldet. Sein vorhandenes Ergebnis wird ohne neuen Test geprüft.',install:'Schließe zuerst den Download ab. Die Auftragsprüfung kontrolliert danach genau diese Datei und ihre Laufzeitunterstützung.',stopUnknown:'Der Stopp ist unbestätigt. Aktualisiere den Prozessstatus; die Ressourcen sind noch nicht bestätigt freigegeben.',artifact:'Modelldatei'},
 es:{retry:'Consultar el resultado existente',running:'La prueba sigue en ejecución según el estado recibido. Se consultará su resultado sin iniciar otra prueba.',install:'Completa primero la descarga. La revisión comprobará este archivo exacto y su compatibilidad con el motor.',stopUnknown:'La detención no está confirmada. Actualiza el estado; la liberación de recursos no se ha confirmado.',artifact:'Archivo del modelo'},
 fr:{retry:'Consulter le résultat existant',running:'Ce test est encore signalé en cours. Son résultat sera consulté sans lancer un autre test.',install:'Terminez d’abord le téléchargement. La vérification contrôlera ce fichier précis et sa prise en charge.',stopUnknown:'L’arrêt n’est pas confirmé. Actualisez l’état ; la libération des ressources n’est pas confirmée.',artifact:'Fichier du modèle'},
 it:{retry:'Controlla il risultato esistente',running:'Il test risulta ancora in esecuzione. Il risultato verrà controllato senza avviare un altro test.',install:'Completa prima il download. La verifica controllerà questo file preciso e il supporto del runtime.',stopUnknown:'L’arresto non è confermato. Aggiorna lo stato; il rilascio delle risorse non è confermato.',artifact:'File del modello'},
 'pt-BR':{retry:'Consultar o resultado existente',running:'Este teste ainda consta como em execução. Seu resultado será consultado sem iniciar outro teste.',install:'Conclua o download primeiro. A revisão verificará este arquivo exato e seu suporte no runtime.',stopUnknown:'A parada não foi confirmada. Atualize o estado; a liberação de recursos ainda não foi confirmada.',artifact:'Arquivo do modelo'},
 ru:{retry:'Проверить существующий результат',running:'По полученному статусу тест ещё выполняется. Его результат будет проверен без запуска другого теста.',install:'Сначала завершите загрузку. Проверка затем подтвердит этот файл и поддержку среды выполнения.',stopUnknown:'Остановка не подтверждена. Обновите статус; освобождение ресурсов ещё не подтверждено.',artifact:'Файл модели'},
 ja:{retry:'既存のテスト結果を確認',running:'このテストはまだ実行中と報告されています。別のテストを起動せず、既存の結果を確認します。',install:'先にダウンロードを完了してください。その後の確認で、このファイルとランタイムの対応状況を確認します。',stopUnknown:'停止は未確認です。プロセス状態を更新してください。リソース解放はまだ確認できていません。',artifact:'モデルファイル'},
};
export const localAiRuntimeCopy=(locale:DesktopLocaleId)=>({...Object.fromEntries(keys.map((key,index)=>[key,rows[locale][index]])) as Record<typeof keys[number],string>,...recovery[locale]});
export function localAiRuntimeReason(locale:DesktopLocaleId,code:string):string{
 if(code==='local_ai_runtime_request_storage_unavailable')return {
  en:'The test request identity could not be saved. Starting is blocked so its outcome can be recovered safely.',
  de:'Die Testanfragekennung konnte nicht gespeichert werden. Der Start ist blockiert, damit das Ergebnis sicher wiederaufgenommen werden kann.',
  es:'No se pudo guardar la identidad de la solicitud. El inicio está bloqueado para poder recuperar el resultado de forma segura.',
  fr:'L’identité de la demande n’a pas pu être enregistrée. Le démarrage est bloqué pour garantir la récupération du résultat.',
  it:'Impossibile salvare l’identità della richiesta. L’avvio è bloccato per consentire un recupero sicuro del risultato.',
  'pt-BR':'Não foi possível salvar a identidade da solicitação. O início está bloqueado para permitir a recuperação segura do resultado.',
  ru:'Не удалось сохранить идентификатор запроса. Запуск заблокирован, чтобы результат можно было безопасно восстановить.',
  ja:'テスト要求IDを保存できませんでした。結果を安全に復元できるよう、開始をブロックしています。',
 }[locale];
 const category=/license|approved_plan|artifact.*(?:missing|selected|installed)/.test(code)?'artifact_license':
  /(?:scan|purpose|review).*(?:expired|required)|hardware.*(?:stale|expired)/.test(code)?'hardware_stale':
  /ram_reserve|memory.*exceeded/.test(code)?'budget_exceeded':
  /previous_process|admission|compute.*busy/.test(code)?'compute_admission':
  /adapter|role|head|projector/.test(code)?'task_support_unknown':/source_bundle|native_assets/.test(code)?'runtime_missing':code;
 return localAiReason(locale,category);
}
