import type { DesktopLocaleId } from './keys.js';
const keys=['title','lightweight','balanced','max_local','hybrid','custom','scan','recommend','automatic','skip','unknown','measured','estimated','unsupported','supported','unavailable','fresh','context','parallel','roles','encoder','retrieve','embed','extract','agent','vision','ram','gpu','disk','select','review','license','consent','confirm','start','cancel','refresh','filesOnly','cloud','noAuto','preferences','pending','running','downloading','verifying','stopping','complete','cancelled','interrupted','failed','downloaded','verified','recommended','usable','slow','insufficient_resources','unmeasured'] as const;
type Copy=Record<typeof keys[number],string>;
const rows:Record<DesktopLocaleId,readonly string[]>={
en:['Local AI','Lightweight','Balanced','Max local','Hybrid','Custom','Scan hardware','Recommend','Automatic recommendation','Skip / use existing provider','Unknown','Measured','Estimated','Unsupported','Supported','Unavailable','Hardware scan expired. Scan again.','Context tokens','Concurrent requests','Optional tasks','Classification','Retrieval','Memory index','Extraction','Agent','Vision','Available RAM','GPU budget','Free disk','Save preference','Review files','License','I agree to these exact licenses and downloads.','Confirm consent','Start download','Cancel','Refresh','Downloaded files alone do not make inference available. A verified runtime is still required.','Hybrid does not authorize cloud use. Configure cloud permissions separately.','Nothing is downloaded or started automatically.','Saved preference','Queued','Running','Downloading','Verifying','Stopping','Files verified','Cancelled','Interrupted','Failed','Downloaded','Verified','Recommended','Usable','Slow','Insufficient resources','Not measured'],
de:['Lokale KI','Geringe Last','Ausgewogen','Maximal lokal','Hybrid','Eigene Auswahl','Hardware prüfen','Empfehlung berechnen','Automatische Empfehlung','Überspringen / vorhandenen Provider nutzen','Unbekannt','Gemessen','Geschätzt','Nicht unterstützt','Unterstützt','Nicht verfügbar','Hardwareprüfung abgelaufen. Erneut prüfen.','Kontexttokens','Parallele Anfragen','Optionale Aufgaben','Klassifikation','Inhalte finden','Gedächtnisindex','Extraktion','Agent','Bildverständnis','Verfügbarer RAM','GPU-Budget','Freier Speicher','Präferenz speichern','Dateien prüfen','Lizenz','Ich stimme diesen konkreten Lizenzen und Downloads zu.','Zustimmung bestätigen','Download starten','Abbrechen','Aktualisieren','Heruntergeladene Dateien allein machen Inferenz nicht verfügbar. Eine geprüfte Laufzeit ist weiter erforderlich.','Hybrid erlaubt keine Cloudnutzung. Cloudrechte werden separat eingerichtet.','Es wird nichts automatisch heruntergeladen oder gestartet.','Gespeicherte Präferenz','In Warteschlange','Läuft','Wird heruntergeladen','Wird geprüft','Stoppt','Dateien geprüft','Abgebrochen','Unterbrochen','Fehlgeschlagen','Heruntergeladen','Geprüft','Empfohlen','Nutzbar','Langsam','Ressourcen reichen nicht','Nicht gemessen'],
it:['IA locale','Leggera','Bilanciata','Massimo locale','Ibrida','Personalizzata','Controlla hardware','Calcola consiglio','Consiglio automatico','Salta / usa il provider esistente','Sconosciuto','Misurato','Stimato','Non supportato','Supportato','Non disponibile','Controllo hardware scaduto. Ripetilo.','Token di contesto','Richieste parallele','Attività facoltative','Classificazione','Ricerca contenuti','Indice di memoria','Estrazione','Agente','Visione','RAM disponibile','Budget GPU','Spazio libero','Salva preferenza','Esamina file','Licenza','Accetto queste specifiche licenze e questi download.','Conferma consenso','Avvia download','Annulla','Aggiorna','I file scaricati non rendono disponibile l’inferenza. Serve ancora un runtime verificato.','Ibrida non autorizza il cloud. Configura i permessi separatamente.','Nessun download o avvio automatico.','Preferenza salvata','In coda','In esecuzione','Download','Verifica','Arresto','File verificati','Annullato','Interrotto','Non riuscito','Scaricati','Verificati','Consigliato','Utilizzabile','Lento','Risorse insufficienti','Non misurato'],
es:['IA local','Ligera','Equilibrada','Máximo local','Híbrida','Personalizada','Comprobar hardware','Calcular recomendación','Recomendación automática','Omitir / usar proveedor existente','Desconocido','Medido','Estimado','No compatible','Compatible','No disponible','La comprobación caducó. Repítela.','Tokens de contexto','Solicitudes paralelas','Tareas opcionales','Clasificación','Buscar contenido','Índice de memoria','Extracción','Agente','Visión','RAM disponible','Presupuesto GPU','Espacio libre','Guardar preferencia','Revisar archivos','Licencia','Acepto estas licencias y descargas concretas.','Confirmar consentimiento','Iniciar descarga','Cancelar','Actualizar','Los archivos descargados no habilitan la inferencia. Aún se necesita un motor verificado.','Híbrida no autoriza el uso de la nube. Configura los permisos aparte.','No se descarga ni inicia nada automáticamente.','Preferencia guardada','En cola','En ejecución','Descargando','Verificando','Deteniendo','Archivos verificados','Cancelado','Interrumpido','Fallido','Descargados','Verificados','Recomendado','Utilizable','Lento','Recursos insuficientes','Sin medir'],
fr:['IA locale','Légère','Équilibrée','Maximum local','Hybride','Personnalisée','Vérifier le matériel','Calculer la recommandation','Recommandation automatique','Ignorer / utiliser le fournisseur existant','Inconnu','Mesuré','Estimé','Non pris en charge','Pris en charge','Indisponible','Le contrôle matériel a expiré. Recommencez.','Tokens de contexte','Requêtes simultanées','Tâches facultatives','Classification','Recherche de contenu','Index mémoire','Extraction','Agent','Vision','RAM disponible','Budget GPU','Espace libre','Enregistrer le choix','Examiner les fichiers','Licence','J’accepte ces licences et téléchargements précis.','Confirmer l’accord','Démarrer le téléchargement','Annuler','Actualiser','Les fichiers téléchargés ne permettent pas seuls l’inférence. Un moteur vérifié reste nécessaire.','Hybride n’autorise pas le cloud. Configurez les permissions séparément.','Aucun téléchargement ni démarrage automatique.','Choix enregistré','En attente','En cours','Téléchargement','Vérification','Arrêt en cours','Fichiers vérifiés','Annulé','Interrompu','Échec','Téléchargés','Vérifiés','Recommandé','Utilisable','Lent','Ressources insuffisantes','Non mesuré'],
'pt-BR':['IA local','Leve','Equilibrada','Máximo local','Híbrida','Personalizada','Verificar hardware','Calcular recomendação','Recomendação automática','Pular / usar provedor existente','Desconhecido','Medido','Estimado','Não compatível','Compatível','Indisponível','A verificação expirou. Faça novamente.','Tokens de contexto','Solicitações paralelas','Tarefas opcionais','Classificação','Buscar conteúdo','Índice de memória','Extração','Agente','Visão','RAM disponível','Orçamento GPU','Espaço livre','Salvar preferência','Revisar arquivos','Licença','Aceito estas licenças e estes downloads específicos.','Confirmar consentimento','Iniciar download','Cancelar','Atualizar','Os arquivos baixados não disponibilizam a inferência. Ainda é necessário um runtime verificado.','Híbrida não autoriza a nuvem. Configure as permissões separadamente.','Nada é baixado ou iniciado automaticamente.','Preferência salva','Na fila','Em execução','Baixando','Verificando','Parando','Arquivos verificados','Cancelado','Interrompido','Falhou','Baixados','Verificados','Recomendado','Utilizável','Lento','Recursos insuficientes','Não medido'],
ru:['Локальный ИИ','Минимальная нагрузка','Сбалансированный','Максимально локально','Гибридный','Свой выбор','Проверить оборудование','Рассчитать рекомендацию','Автоматическая рекомендация','Пропустить / текущий провайдер','Неизвестно','Измерено','Оценка','Не поддерживается','Поддерживается','Недоступно','Проверка устарела. Повторите её.','Токены контекста','Параллельные запросы','Дополнительные задачи','Классификация','Поиск материалов','Индекс памяти','Извлечение','Агент','Распознавание изображений','Доступная RAM','Бюджет GPU','Свободное место','Сохранить выбор','Проверить файлы','Лицензия','Согласен с этими конкретными лицензиями и загрузками.','Подтвердить согласие','Начать загрузку','Отмена','Обновить','Загруженные файлы сами не обеспечивают инференс. Нужна проверенная среда выполнения.','Гибридный режим не разрешает облако. Права задаются отдельно.','Ничего не загружается и не запускается автоматически.','Сохранённый выбор','В очереди','Выполняется','Загрузка','Проверка','Останавливается','Файлы проверены','Отменено','Прервано','Ошибка','Загружено','Проверено','Рекомендуется','Можно использовать','Медленно','Недостаточно ресурсов','Не измерено'],
ja:['ローカルAI','低負荷','バランス','最大ローカル','ハイブリッド','カスタム','ハードウェアを確認','推奨を計算','自動推奨','スキップ / 既存プロバイダーを使用','不明','実測','推定','非対応','対応','利用不可','ハードウェア確認が古いため、再確認してください。','コンテキストトークン','同時リクエスト','追加タスク','分類','関連内容の検索','メモリ索引','抽出','エージェント','画像理解','使用可能なRAM','GPU予算','ディスク空き容量','設定を保存','ファイルを確認','ライセンス','この具体的なライセンスとダウンロードに同意します。','同意を確定','ダウンロード開始','キャンセル','更新','ダウンロードしたファイルだけでは推論できません。検証済みランタイムが必要です。','ハイブリッド選択はクラウド使用を許可しません。権限は別途設定します。','自動でダウンロードや起動はしません。','保存済み設定','待機中','実行中','ダウンロード中','検証中','停止中','ファイル検証済み','キャンセル済み','中断','失敗','ダウンロード済み','検証済み','推奨','使用可能','低速','リソース不足','未計測']};
const modelDownloadPolicy:Record<DesktopLocaleId,string>={
  en:'Additional models are downloaded only after you choose them.',de:'Weitere Modelle werden erst heruntergeladen, wenn du sie auswählst.',
  it:'Gli altri modelli vengono scaricati solo dopo averli scelti.',es:'Los modelos adicionales solo se descargan después de que los elijas.',
  fr:'Les autres modèles sont téléchargés uniquement après votre choix.',
  'pt-BR':'Modelos adicionais só são baixados depois que você os escolhe.',
  ru:'Дополнительные модели загружаются только после вашего выбора.',ja:'追加モデルは選択した後にのみダウンロードされます。'
};
const testBuildUnavailable:Record<DesktopLocaleId,string>={
  en:'The Local Model Store and bundled CPU inference are unavailable in this test build.',
  de:'Der lokale Modell-Store und die gebündelte CPU-Inferenz sind in dieser Testversion nicht verfügbar.',
  it:'Il catalogo di modelli locali e l’inferenza CPU inclusa non sono disponibili in questa versione di test.',
  es:'La tienda de modelos locales y la inferencia de CPU incluida no están disponibles en esta versión de prueba.',
  fr:'La boutique de modèles locaux et l’inférence CPU intégrée ne sont pas disponibles dans cette version de test.',
  'pt-BR':'A loja de modelos locais e a inferência de CPU incluída não estão disponíveis nesta versão de teste.',
  ru:'Магазин локальных моделей и встроенный инференс на CPU недоступны в этой тестовой версии.',
  ja:'このテスト版では、ローカルモデルストアと同梱CPU推論は利用できません。'
};
const externalProvidersUnaffected:Record<DesktopLocaleId,string>={
  en:'External AI providers are unaffected. Configure them under AI & local models.',
  de:'Externe KI-Anbieter sind davon nicht betroffen. Richte sie unter „KI & lokale Modelle“ ein.',
  it:'I provider AI esterni non sono interessati. Configurali in “IA e modelli locali”.',
  es:'Los proveedores de IA externos no se ven afectados. Configúralos en «IA y modelos locales».',
  fr:'Les fournisseurs d’IA externes ne sont pas concernés. Configurez-les dans « IA et modèles locaux ».',
  'pt-BR':'Os provedores externos de IA não são afetados. Configure-os em “IA e modelos locais”.',
  ru:'Внешние ИИ-провайдеры не затронуты. Настройте их в разделе «ИИ и локальные модели».',
  ja:'外部AIプロバイダーには影響しません。「AIとローカルモデル」で設定できます。'
};
export function localAiCopy(locale:DesktopLocaleId):Copy&Readonly<{testBuildUnavailable:string;externalProvidersUnaffected:string}>{return {
  ...Object.fromEntries(keys.map((key,index)=>[key,rows[locale][index]])),noAuto:modelDownloadPolicy[locale],
  testBuildUnavailable:testBuildUnavailable[locale],externalProvidersUnaffected:externalProvidersUnaffected[locale]
} as Copy&Readonly<{testBuildUnavailable:string;externalProvidersUnaffected:string}>;}
export type LocalAiSetupCopy=Readonly<{simple:string;advanced:string;simpleHelp:string;advancedHelp:string;checking:string;scanTimeout:string;scanFailed:string;scanReady:string;
  lightweightHelp:string;balancedHelp:string;hybridHelp:string;noLocalAi:string;scanRetry:string;recommendedForDevice?:string;noSupportedRecommendation?:string}>;
const setupRows:Record<DesktopLocaleId,LocalAiSetupCopy>={
  en:{simple:'Simple',advanced:'Advanced',simpleHelp:'Start with a few clear choices. Model and hardware details stay out of the way.',advancedHelp:'Show individual models, runtimes, quantization and measured hardware details.',checking:'Checking this device…',scanTimeout:'The hardware check did not respond in time. You can try again.',scanFailed:'The hardware check could not be completed. Check the local assistant and try again.',scanReady:'Device check complete. Measurements are shown as measured, estimated or unavailable.',lightweightHelp:'Choose a smaller local setup for modest devices.',balancedHelp:'A balanced local setup for everyday use.',hybridHelp:'Consider local and cloud options. Cloud access still needs separate permission.',noLocalAi:'Continue without local AI',scanRetry:'Try hardware check again'},
  de:{simple:'Einfach',advanced:'Erweitert',simpleHelp:'Wenige klare Auswahlmöglichkeiten. Modell- und Hardwaredetails bleiben ausgeblendet.',advancedHelp:'Einzelne Modelle, Laufzeiten, Quantisierung und gemessene Hardwaredetails anzeigen.',checking:'Prüfe dieses Gerät …',scanTimeout:'Die Hardwareprüfung hat nicht rechtzeitig geantwortet. Du kannst es erneut versuchen.',scanFailed:'Die Hardwareprüfung konnte nicht abgeschlossen werden. Prüfe den lokalen Assistenten und versuche es erneut.',scanReady:'Geräteprüfung abgeschlossen. Werte sind als gemessen, geschätzt oder nicht verfügbar gekennzeichnet.',lightweightHelp:'Eine kleinere lokale Auswahl für Geräte mit weniger Leistung.',balancedHelp:'Eine ausgewogene lokale Auswahl für den Alltag.',hybridHelp:'Lokale und Cloud-Optionen vergleichen. Cloudzugriff braucht weiterhin eine eigene Freigabe.',noLocalAi:'Ohne lokale KI fortfahren',scanRetry:'Hardwareprüfung erneut versuchen'},
  it:{simple:'Semplice',advanced:'Avanzata',simpleHelp:'Poche scelte chiare. I dettagli su modelli e hardware restano nascosti.',advancedHelp:'Mostra modelli, runtime, quantizzazione e dettagli hardware misurati.',checking:'Controllo del dispositivo…',scanTimeout:'Il controllo hardware non ha risposto in tempo. Puoi riprovare.',scanFailed:'Impossibile completare il controllo hardware. Verifica l’assistente locale e riprova.',scanReady:'Controllo completato. I valori sono indicati come misurati, stimati o non disponibili.',lightweightHelp:'Una configurazione locale più piccola per dispositivi meno potenti.',balancedHelp:'Una configurazione locale equilibrata per l’uso quotidiano.',hybridHelp:'Valuta opzioni locali e cloud. Il cloud richiede comunque un’autorizzazione separata.',noLocalAi:'Continua senza AI locale',scanRetry:'Riprova il controllo hardware'},
  es:{simple:'Sencillo',advanced:'Avanzado',simpleHelp:'Pocas opciones claras. Los detalles del modelo y el hardware quedan ocultos.',advancedHelp:'Muestra modelos, runtimes, cuantización y detalles medidos del hardware.',checking:'Comprobando este dispositivo…',scanTimeout:'La comprobación de hardware no respondió a tiempo. Puedes intentarlo de nuevo.',scanFailed:'No se pudo completar la comprobación. Revisa el asistente local e inténtalo de nuevo.',scanReady:'Comprobación completada. Los valores se marcan como medidos, estimados o no disponibles.',lightweightHelp:'Una opción local más pequeña para equipos modestos.',balancedHelp:'Una opción local equilibrada para el uso diario.',hybridHelp:'Compara opciones locales y en la nube. La nube requiere permiso independiente.',noLocalAi:'Continuar sin IA local',scanRetry:'Reintentar comprobación'},
  fr:{simple:'Simple',advanced:'Avancé',simpleHelp:'Quelques choix faciles. Les détails du modèle et du matériel restent masqués.',advancedHelp:'Afficher les modèles, moteurs, quantifications et mesures matérielles.',checking:'Vérification de cet appareil…',scanTimeout:'La vérification du matériel n’a pas répondu à temps. Vous pouvez réessayer.',scanFailed:'La vérification du matériel a échoué. Vérifiez l’assistant local puis réessayez.',scanReady:'Vérification terminée. Les valeurs sont mesurées, estimées ou indisponibles.',lightweightHelp:'Une option locale plus légère pour les appareils modestes.',balancedHelp:'Une option locale équilibrée au quotidien.',hybridHelp:'Comparer les options locales et cloud. Le cloud nécessite toujours une autorisation distincte.',noLocalAi:'Continuer sans IA locale',scanRetry:'Réessayer la vérification'},
  'pt-BR':{simple:'Simples',advanced:'Avançado',simpleHelp:'Poucas opções claras. Detalhes de modelo e hardware ficam ocultos.',advancedHelp:'Mostrar modelos, runtimes, quantização e detalhes medidos do hardware.',checking:'Verificando este dispositivo…',scanTimeout:'A verificação de hardware não respondeu a tempo. Você pode tentar novamente.',scanFailed:'Não foi possível concluir a verificação. Confira o assistente local e tente novamente.',scanReady:'Verificação concluída. Os valores são medidos, estimados ou indisponíveis.',lightweightHelp:'Uma opção local menor para dispositivos modestos.',balancedHelp:'Uma opção local equilibrada para o uso diário.',hybridHelp:'Compare opções locais e na nuvem. A nuvem ainda exige permissão separada.',noLocalAi:'Continuar sem IA local',scanRetry:'Tentar verificação novamente'},
  ru:{simple:'Простой',advanced:'Расширенный',simpleHelp:'Несколько понятных вариантов. Подробности о моделях и оборудовании скрыты.',advancedHelp:'Показать модели, среды, квантование и измеренные данные оборудования.',checking:'Проверяем устройство…',scanTimeout:'Проверка оборудования не ответила вовремя. Можно попробовать ещё раз.',scanFailed:'Не удалось завершить проверку. Проверьте локальный помощник и повторите попытку.',scanReady:'Проверка завершена. Значения отмечены как измеренные, оценочные или недоступные.',lightweightHelp:'Более лёгкий локальный вариант для скромных устройств.',balancedHelp:'Сбалансированный локальный вариант на каждый день.',hybridHelp:'Сравнить локальные и облачные варианты. Для облака нужно отдельное разрешение.',noLocalAi:'Продолжить без локального ИИ',scanRetry:'Повторить проверку оборудования'},
  ja:{simple:'シンプル',advanced:'詳細',simpleHelp:'わかりやすい選択肢だけを表示し、モデルやハードウェアの詳細は隠します。',advancedHelp:'個別モデル、ランタイム、量子化、測定済みハードウェア情報を表示します。',checking:'デバイスを確認中…',scanTimeout:'ハードウェア確認が時間内に応答しませんでした。もう一度試せます。',scanFailed:'ハードウェアを確認できませんでした。ローカルアシスタントを確認して再試行してください。',scanReady:'確認完了。値は実測、推定、利用不可のいずれかで表示されます。',lightweightHelp:'性能が限られたデバイス向けの軽量なローカル構成です。',balancedHelp:'日常利用向けのバランスの取れたローカル構成です。',hybridHelp:'ローカルとクラウドの選択肢を比較します。クラウドには別途許可が必要です。',noLocalAi:'ローカルAIを使わずに続行',scanRetry:'ハードウェア確認を再試行'}
};
const recommendationLabels:Record<DesktopLocaleId,readonly [string,string]>={en:['Recommended for this PC','Local setup is not available for this PC right now.'],de:['Empfehlung für diesen PC','Lokale Einrichtung ist für diesen PC derzeit nicht verfügbar.'],it:['Consigliato per questo PC','La configurazione locale non è disponibile per questo PC.'],es:['Recomendado para este PC','La configuración local no está disponible para este PC.'],fr:['Recommandé pour ce PC','La configuration locale est indisponible pour ce PC.'],'pt-BR':['Recomendado para este PC','A configuração local não está disponível para este PC.'],ru:['Рекомендация для этого ПК','Локальная настройка сейчас недоступна для этого ПК.'],ja:['この PC におすすめ','この PC では現在ローカル設定を利用できません。']};
const chatCandidateRows:Record<DesktopLocaleId,Readonly<{title:string;eligible:string;setup:string;blocked:string;notReady:string;consent:string;qualifying:string;qualified:string;retry:string;failed:string;lowRam:string;technicalDetails:string}>>={
  en:{title:'Local short answers',eligible:'This PC can try the optional 350M model for short answers. It becomes available in this Space only after the download and quality check pass.',setup:'Set up local short answers',blocked:'This PC does not currently meet the measured requirements for this model.',notReady:'This model is not yet qualified for this PC or available for chat.',consent:'I also authorize the bounded quality check and enabling short chat in this Space only if it passes.',qualifying:'Testing local short answers for this Space…',qualified:'Local short answers are ready in this Space.',retry:'Retry the existing qualification check',failed:'The check did not qualify this model. Local chat remains unavailable.',lowRam:'There is not enough free memory to test this model. Close some apps and try again.',technicalDetails:'Technical details'},
  de:{title:'Lokale Kurzantworten',eligible:'Dieser PC kann das optionale 350M-Modell für kurze Antworten testen. In diesem Space wird es erst nach erfolgreichem Download und Qualitätstest verfügbar.',setup:'Lokale Kurzantworten einrichten',blocked:'Dieser PC erfüllt die gemessenen Anforderungen für dieses Modell derzeit nicht.',notReady:'Dieses Modell ist für diesen PC noch nicht qualifiziert und nicht im Chat verfügbar.',consent:'Ich erlaube auch den begrenzten Qualitätstest und die Freigabe des Kurzchats nur in diesem Space, falls er bestanden wird.',qualifying:'Lokale Kurzantworten für diesen Space werden getestet …',qualified:'Lokale Kurzantworten sind in diesem Space bereit.',retry:'Vorhandene Qualifizierungsprüfung fortsetzen',failed:'Die Prüfung hat das Modell nicht qualifiziert. Lokaler Chat bleibt nicht verfügbar.',lowRam:'Zum Testen dieses Modells ist zu wenig Arbeitsspeicher frei. Schließe einige Apps und versuche es erneut.',technicalDetails:'Technische Details'},
  it:{title:'Risposte brevi locali',eligible:'Questo PC può provare il modello facoltativo da 350M per risposte brevi. Sarà disponibile in questo Space solo dopo il download e il test di qualità.',setup:'Configura le risposte brevi locali',blocked:'Questo PC al momento non soddisfa i requisiti misurati per il modello.',notReady:'Il modello non è ancora qualificato per questo PC né disponibile per la chat.',consent:'Autorizzo anche il controllo qualità limitato e l’attivazione della chat breve solo in questo Space se il test riesce.',qualifying:'Verifica in corso delle risposte brevi locali per questo Space…',qualified:'Le risposte brevi locali sono pronte in questo Space.',retry:'Riprendi il controllo di qualificazione esistente',failed:'Il controllo non ha qualificato il modello. La chat locale non è disponibile.',lowRam:'Memoria libera insufficiente per provare questo modello. Chiudi alcune app e riprova.',technicalDetails:'Dettagli tecnici'},
  es:{title:'Respuestas locales breves',eligible:'Este PC puede probar el modelo opcional de 350M para respuestas breves. Solo estará disponible en este Space si supera la descarga y la prueba de calidad.',setup:'Configurar respuestas locales breves',blocked:'Este PC no cumple actualmente los requisitos medidos para este modelo.',notReady:'Este modelo aún no está cualificado para este PC ni disponible para el chat.',consent:'También autorizo la prueba de calidad limitada y habilitar el chat breve solo en este Space si la supera.',qualifying:'Probando las respuestas locales breves de este Space…',qualified:'Las respuestas locales breves están listas en este Space.',retry:'Reanudar la prueba de cualificación existente',failed:'La prueba no cualificó este modelo. El chat local no está disponible.',lowRam:'No hay suficiente memoria libre para probar este modelo. Cierra algunas aplicaciones e inténtalo de nuevo.',technicalDetails:'Detalles técnicos'},
  fr:{title:'Réponses courtes locales',eligible:'Ce PC peut essayer le modèle facultatif de 350M pour des réponses courtes. Il sera disponible dans cet espace uniquement après le téléchargement et la réussite du test qualité.',setup:'Configurer les réponses courtes locales',blocked:'Ce PC ne satisfait pas actuellement aux exigences mesurées de ce modèle.',notReady:'Ce modèle n’est pas encore qualifié pour ce PC et n’est pas disponible dans le chat.',consent:'J’autorise également le test qualité limité et l’activation du chat court dans cet espace uniquement en cas de réussite.',qualifying:'Test des réponses courtes locales pour cet espace…',qualified:'Les réponses courtes locales sont prêtes dans cet espace.',retry:'Reprendre le test de qualification existant',failed:'Le test n’a pas qualifié ce modèle. Le chat local reste indisponible.',lowRam:'La mémoire libre est insuffisante pour tester ce modèle. Fermez quelques applications et réessayez.',technicalDetails:'Détails techniques'},
  'pt-BR':{title:'Respostas locais curtas',eligible:'Este PC pode testar o modelo opcional de 350M para respostas curtas. Ele ficará disponível neste Space somente após o download e a aprovação no teste de qualidade.',setup:'Configurar respostas locais curtas',blocked:'Este PC não atende aos requisitos medidos para este modelo no momento.',notReady:'Este modelo ainda não foi qualificado para este PC nem está disponível no chat.',consent:'Também autorizo o teste limitado de qualidade e a ativação da conversa curta apenas neste Space se for aprovado.',qualifying:'Testando respostas locais curtas neste Space…',qualified:'As respostas locais curtas estão prontas neste Space.',retry:'Retomar o teste de qualificação existente',failed:'O teste não qualificou este modelo. A conversa local continua indisponível.',lowRam:'Não há memória livre suficiente para testar este modelo. Feche alguns aplicativos e tente novamente.',technicalDetails:'Detalhes técnicos'},
  ru:{title:'Короткие локальные ответы',eligible:'На этом компьютере можно проверить необязательную модель 350M для коротких ответов. Она станет доступна в этом Space только после загрузки и успешной проверки качества.',setup:'Настроить короткие локальные ответы',blocked:'Этот компьютер пока не соответствует измеренным требованиям модели.',notReady:'Эта модель ещё не проверена на этом компьютере и недоступна для чата.',consent:'Также разрешаю ограниченную проверку качества и включение короткого чата только в этом Space при успешном результате.',qualifying:'Проверяем короткие локальные ответы в этом Space…',qualified:'Короткие локальные ответы готовы в этом Space.',retry:'Продолжить существующую проверку',failed:'Модель не прошла проверку. Локальный чат недоступен.',lowRam:'Недостаточно свободной памяти для проверки модели. Закройте несколько приложений и повторите попытку.',technicalDetails:'Технические сведения'},
  ja:{title:'ローカル短文回答',eligible:'この PC で任意の350Mモデルによる短文回答を試せます。このSpaceでは、ダウンロードと品質確認に合格した後のみ利用できます。',setup:'ローカル短文回答を設定',blocked:'この PC は現在、このモデルの測定済み要件を満たしていません。',notReady:'このモデルはこの PC での適格性が未確認のため、チャットでは利用できません。',consent:'制限付き品質確認を許可し、合格した場合のみこのSpaceで短文チャットを有効にします。',qualifying:'このSpaceのローカル短文回答を確認中…',qualified:'このSpaceでローカル短文回答を利用できます。',retry:'既存の適格性確認を再開',failed:'この確認ではモデルは適格になりませんでした。ローカルチャットは利用できません。',lowRam:'このモデルを確認する空きメモリが不足しています。アプリをいくつか閉じて、もう一度お試しください。',technicalDetails:'技術的な詳細'}
};
export function localAiChatCandidateCopy(locale:DesktopLocaleId){return chatCandidateRows[locale];}
type LocalAiFlowCopy=Readonly<{stepCheck:string;stepCheckHelp:string;stepRecommend:string;stepRecommendHelp:string;stepSetup:string;stepSetupHelp:string;
  assistantNotReady:string;serviceFailed:string;recommendationWaiting:string;diagnostics:string;modelDetails:string;resourceDetails:string}>;
const flowRows:Record<DesktopLocaleId,LocalAiFlowCopy>={
  en:{stepCheck:'Check your PC',stepCheckHelp:'Read-only check of CPU, memory, graphics and free disk space.',stepRecommend:'Choose a recommendation',stepRecommendHelp:'We recommend only models with verified requirements and a known download size.',stepSetup:'Set up local AI',stepSetupHelp:'Review the exact files and license before any download.',assistantNotReady:'Hardware checks still work. Model recommendations need the local assistant service to be ready.',serviceFailed:'The local assistant could not complete this step. Check its status and try again.',recommendationWaiting:'A recommendation will appear after the device check and service are ready.',diagnostics:'Scan diagnostics',modelDetails:'Models and presets',resourceDetails:'Resource limits'},
  de:{stepCheck:'PC prüfen',stepCheckHelp:'Liest CPU, Arbeitsspeicher, Grafik und freien Speicherplatz aus.',stepRecommend:'Empfehlung ansehen',stepRecommendHelp:'Wir empfehlen nur Modelle mit geprüften Anforderungen und bekannter Downloadgröße.',stepSetup:'Lokale KI einrichten',stepSetupHelp:'Prüfe Dateien und Lizenz, bevor ein Download startet.',assistantNotReady:'Die Hardwareprüfung funktioniert trotzdem. Für Modellempfehlungen muss der lokale Assistent bereit sein.',serviceFailed:'Der lokale Assistent konnte diesen Schritt nicht abschließen. Prüfe seinen Status und versuche es erneut.',recommendationWaiting:'Die Empfehlung erscheint, sobald Geräteprüfung und lokaler Assistent bereit sind.',diagnostics:'Diagnose der Prüfung',modelDetails:'Modelle und Profile',resourceDetails:'Ressourcenbegrenzungen'},
  it:{stepCheck:'Controlla il PC',stepCheckHelp:'Legge CPU, memoria, grafica e spazio libero.',stepRecommend:'Valuta il consiglio',stepRecommendHelp:'Consigliamo solo modelli con requisiti verificati e dimensione nota.',stepSetup:'Configura l’IA locale',stepSetupHelp:'Esamina file e licenza prima di avviare qualsiasi download.',assistantNotReady:'Il controllo hardware funziona comunque. Per i consigli sui modelli serve l’assistente locale.',serviceFailed:'L’assistente locale non è riuscito a completare questo passaggio. Controllane lo stato e riprova.',recommendationWaiting:'Il consiglio apparirà quando il controllo e l’assistente saranno pronti.',diagnostics:'Diagnostica del controllo',modelDetails:'Modelli e profili',resourceDetails:'Limiti risorse'},
  es:{stepCheck:'Comprobar el PC',stepCheckHelp:'Lee CPU, memoria, gráficos y espacio libre.',stepRecommend:'Ver la recomendación',stepRecommendHelp:'Solo recomendamos modelos con requisitos verificados y tamaño conocido.',stepSetup:'Configurar IA local',stepSetupHelp:'Revisa los archivos y la licencia antes de iniciar una descarga.',assistantNotReady:'La comprobación del hardware sigue funcionando. Para recomendar modelos, el asistente local debe estar listo.',serviceFailed:'El asistente local no pudo completar este paso. Comprueba su estado e inténtalo de nuevo.',recommendationWaiting:'La recomendación aparecerá cuando la comprobación y el asistente estén listos.',diagnostics:'Diagnóstico de comprobación',modelDetails:'Modelos y perfiles',resourceDetails:'Límites de recursos'},
  fr:{stepCheck:'Vérifier le PC',stepCheckHelp:'Lit le processeur, la mémoire, le graphique et l’espace libre.',stepRecommend:'Voir la recommandation',stepRecommendHelp:'Nous recommandons uniquement les modèles aux exigences vérifiées et à la taille connue.',stepSetup:'Configurer l’IA locale',stepSetupHelp:'Vérifiez les fichiers et la licence avant tout téléchargement.',assistantNotReady:'La vérification matérielle fonctionne. Les recommandations nécessitent que l’assistant local soit prêt.',serviceFailed:'L’assistant local n’a pas pu terminer cette étape. Vérifiez son état et réessayez.',recommendationWaiting:'La recommandation apparaîtra lorsque la vérification et l’assistant seront prêts.',diagnostics:'Diagnostic de vérification',modelDetails:'Modèles et profils',resourceDetails:'Limites de ressources'},
  'pt-BR':{stepCheck:'Verificar o PC',stepCheckHelp:'Lê CPU, memória, gráficos e espaço livre.',stepRecommend:'Ver recomendação',stepRecommendHelp:'Recomendamos apenas modelos com requisitos verificados e tamanho conhecido.',stepSetup:'Configurar IA local',stepSetupHelp:'Confira os arquivos e a licença antes de iniciar qualquer download.',assistantNotReady:'A verificação do hardware ainda funciona. Para recomendar modelos, o assistente local precisa estar pronto.',serviceFailed:'O assistente local não conseguiu concluir esta etapa. Confira o status e tente novamente.',recommendationWaiting:'A recomendação aparecerá quando a verificação e o assistente estiverem prontos.',diagnostics:'Diagnóstico da verificação',modelDetails:'Modelos e perfis',resourceDetails:'Limites de recursos'},
  ru:{stepCheck:'Проверить ПК',stepCheckHelp:'Определяет процессор, память, графику и свободное место.',stepRecommend:'Посмотреть рекомендацию',stepRecommendHelp:'Рекомендуются только модели с проверенными требованиями и известным размером.',stepSetup:'Настроить локальный ИИ',stepSetupHelp:'Проверьте файлы и лицензию до начала загрузки.',assistantNotReady:'Проверка оборудования работает. Для рекомендаций должен быть готов локальный помощник.',serviceFailed:'Локальный помощник не смог выполнить этот шаг. Проверьте его состояние и повторите попытку.',recommendationWaiting:'Рекомендация появится после проверки устройства и готовности помощника.',diagnostics:'Диагностика проверки',modelDetails:'Модели и профили',resourceDetails:'Ограничения ресурсов'},
  ja:{stepCheck:'PC を確認',stepCheckHelp:'CPU、メモリ、グラフィックス、空き容量を読み取ります。',stepRecommend:'おすすめを確認',stepRecommendHelp:'要件を確認でき、ダウンロードサイズが分かるモデルだけをおすすめします。',stepSetup:'ローカル AI を設定',stepSetupHelp:'ダウンロード前にファイルとライセンスを確認してください。',assistantNotReady:'ハードウェア確認は引き続き利用できます。モデルのおすすめにはローカルアシスタントが必要です。',serviceFailed:'ローカルアシスタントがこの手順を完了できませんでした。状態を確認して再試行してください。',recommendationWaiting:'デバイス確認とアシスタントの準備ができると、おすすめが表示されます。',diagnostics:'確認の診断',modelDetails:'モデルとプリセット',resourceDetails:'リソース上限'}
};
export function localAiSetupCopy(locale:DesktopLocaleId):LocalAiSetupCopy&LocalAiFlowCopy{return {...setupRows[locale],...flowRows[locale],recommendedForDevice:recommendationLabels[locale][0],noSupportedRecommendation:recommendationLabels[locale][1]};}
const reasonRows:Record<DesktopLocaleId,readonly string[]>={
en:['Runtime is missing or unverified','Task support has not been verified','Memory availability or limits are unverified','The available memory budget is insufficient','Context or concurrency exceeds verified limits','File manifest, checksum or license is incomplete','Task head or vision projector is missing','Performance and quality have not been measured','A fresh hardware scan is required','Compute capacity is busy or unknown','Cloud requires separate explicit permission','Download and temporary disk space are insufficient or unknown'],
de:['Laufzeit fehlt oder ist ungeprüft','Aufgabenunterstützung ist ungeprüft','Speicherverfügbarkeit oder Grenzen sind ungeprüft','Verfügbares Speicherbudget reicht nicht','Kontext oder Parallelität überschreitet geprüfte Grenzen','Dateimanifest, Prüfsumme oder Lizenz ist unvollständig','Task-Head oder Bildprojektor fehlt','Leistung und Qualität sind nicht gemessen','Eine neue Hardwareprüfung ist erforderlich','Rechenkapazität ist belegt oder unbekannt','Cloud braucht eine separate ausdrückliche Freigabe','Download- und Zwischenspeicherplatz fehlt oder ist unbekannt'],
it:['Runtime assente o non verificato','Supporto attività non verificato','Memoria o limiti non verificati','Budget memoria insufficiente','Contesto o concorrenza oltre i limiti verificati','Manifesto, checksum o licenza incompleti','Head o proiettore visivo assente','Prestazioni e qualità non misurate','Serve una nuova verifica hardware','Capacità occupata o sconosciuta','Il cloud richiede un consenso separato','Spazio per download e file temporanei insufficiente o sconosciuto'],
es:['Motor ausente o sin verificar','Tarea no verificada','Memoria o límites sin verificar','Memoria disponible insuficiente','Contexto o concurrencia supera límites verificados','Manifiesto, suma o licencia incompletos','Falta head o proyector visual','Rendimiento y calidad sin medir','Se requiere una nueva comprobación','Capacidad ocupada o desconocida','La nube requiere autorización aparte','Espacio de descarga y temporal insuficiente o desconocido'],
fr:['Moteur absent ou non vérifié','Prise en charge non vérifiée','Mémoire ou limites non vérifiées','Budget mémoire insuffisant','Contexte ou concurrence dépasse les limites vérifiées','Manifeste, somme ou licence incomplets','Tête de tâche ou projecteur visuel absent','Performance et qualité non mesurées','Un nouveau contrôle matériel est nécessaire','Capacité occupée ou inconnue','Le cloud nécessite un accord séparé','Espace de téléchargement et temporaire insuffisant ou inconnu'],
'pt-BR':['Runtime ausente ou não verificado','Tarefa não verificada','Memória ou limites não verificados','Orçamento de memória insuficiente','Contexto ou concorrência excede limites verificados','Manifesto, checksum ou licença incompletos','Head ou projetor visual ausente','Desempenho e qualidade não medidos','É necessária uma nova verificação','Capacidade ocupada ou desconhecida','A nuvem precisa de autorização separada','Espaço de download e temporário insuficiente ou desconhecido'],
ru:['Среда отсутствует или не проверена','Поддержка задачи не проверена','Память или пределы не проверены','Недостаточный бюджет памяти','Контекст или параллельность выше проверенных пределов','Манифест, сумма или лицензия неполны','Нет головы задачи или проектора','Скорость и качество не измерены','Нужна новая проверка оборудования','Вычисления заняты или неизвестны','Облаку нужно отдельное разрешение','Место для загрузки и временных файлов неизвестно или недостаточно'],
ja:['ランタイムがないか未検証です','タスク対応は未検証です','メモリや制限は未検証です','メモリ予算が不足しています','コンテキストや並列数が検証範囲を超えています','ファイル情報、チェックサム、ライセンスが不完全です','タスクヘッドや画像プロジェクターがありません','性能と品質は未計測です','ハードウェアを再確認してください','計算枠は使用中か不明です','クラウドには別の明示的許可が必要です','ダウンロードや一時保存の容量が不足または不明です']};
export function localAiReason(locale:DesktopLocaleId,code:string):string{
  let index=1;if(code.startsWith('runtime_'))index=0;else if(/memory_unknown|budget_unknown|budget_scope_unknown/.test(code))index=2;
  else if(/budget_exceeded/.test(code))index=3;else if(/context|memory_profile_request/.test(code))index=4;else if(/artifact_|license/.test(code))index=5;
  else if(/head|projector/.test(code))index=6;else if(/quality|performance/.test(code))index=7;else if(/stale/.test(code))index=8;
  else if(/admission/.test(code))index=9;else if(/cloud/.test(code))index=10;else if(/disk/.test(code))index=11;
  return reasonRows[locale][index];
}
