import type { DesktopLocaleId } from './keys.js';
const keys=['title','mode','fixed','automatic','models','orchestrator','none','cloud','deny','allow','data','public','private','workspace','browsing','rpm','tpm','concurrent','output','cost','save','refresh','available','unavailable','unknown','stale','observed','remaining','limit','reset','actionRequired','choose','privacy','bindingRequired','changed','executionRequired','configure','requests','tokens','input_tokens','output_tokens','project_tokens','actualDecision','decisionUnknown','configuredPreference','decisionOrchestrator','decisionAllowed','decisionPending','lastCompletedTurn'] as const;
type Copy=Record<typeof keys[number],string>;
const rows:Record<DesktopLocaleId,readonly string[]>={
  en:['Automatic model selection','Selection','Fixed model','AUTO','Allowed models','Orchestrator','None','Cloud use','Do not allow','Allow selected data','Data allowed in the cloud','Public data','Private chat content','Workspace files','Browsing content','Requests per minute','Tokens per minute','Concurrent requests','Output tokens per request','USD per minute (optional)','Save policy','Refresh','Execution available','Execution unavailable','Unknown','Outdated observation','Observed','Remaining','Limit','Reset','Account action required','Choose at least one actual model','Only selected models and data are allowed. Tool permissions remain separate.','Connect and explicitly bind these providers in the Space Assistant first.','The connection or policy changed. Refresh before retrying.','This host has not confirmed isolated AUTO execution and its required governance.','Configure AUTO','Requests','Tokens','Input tokens','Output tokens','Project tokens','Actual decision','Decision not yet known','Configured preference','Configured orchestrator','Configured candidate','Pending turn execution','Last completed turn'],
  de:['Automatische Modellauswahl','Auswahl','Festes Modell','AUTO','Erlaubte Modelle','Orchestrator','Keiner','Cloudnutzung','Nicht erlauben','Ausgewählte Daten erlauben','In der Cloud erlaubte Daten','Öffentliche Daten','Private Chatinhalte','Workspace-Dateien','Browserinhalte','Anfragen pro Minute','Tokens pro Minute','Parallele Anfragen','Ausgabetokens pro Anfrage','USD pro Minute (optional)','Richtlinie speichern','Aktualisieren','Ausführung verfügbar','Ausführung nicht verfügbar','Unbekannt','Veralteter Beobachtungsstand','Beobachtet','Verbleibend','Limit','Zurücksetzung','Aktion am Konto erforderlich','Mindestens ein tatsächliches Modell auswählen','Nur ausgewählte Modelle und Daten sind erlaubt. Toolrechte bleiben getrennt.','Diese Provider zuerst im Space Assistant verbinden und ausdrücklich zuordnen.','Verbindung oder Richtlinie geändert. Vor dem erneuten Versuch aktualisieren.','Dieser Host hat isolierte AUTO-Ausführung und die erforderliche Governance noch nicht bestätigt.','AUTO konfigurieren','Anfragen','Tokens','Eingabetokens','Ausgabetokens','Projekttokens','Tatsächliche Entscheidung','Entscheidung noch nicht bekannt','Konfigurierte Präferenz','Konfigurierter Orchestrator','Konfigurierter Kandidat','Wartet auf Turn-Ausführung','Letzter abgeschlossener Turn'],
  es:['Selección automática de modelo','Selección','Modelo fijo','AUTO','Modelos permitidos','Orquestador','Ninguno','Uso de la nube','No permitir','Permitir datos seleccionados','Datos permitidos en la nube','Datos públicos','Contenido privado del chat','Archivos del espacio de trabajo','Contenido de navegación','Solicitudes por minuto','Tokens por minuto','Solicitudes simultáneas','Tokens de salida por solicitud','USD por minuto (opcional)','Guardar política','Actualizar','Ejecución disponible','Ejecución no disponible','Desconocido','Observación desactualizada','Observado','Restantes','Límite','Restablecimiento','Se requiere una acción en la cuenta','Seleccione al menos un modelo real','Solo se permiten los modelos y datos seleccionados. Los permisos de herramientas son independientes.','Conecte y vincule estos proveedores explícitamente en el asistente del Space.','La conexión o la política cambió. Actualice antes de reintentar.','Este equipo aún no ha confirmado la ejecución AUTO aislada y la gobernanza requerida.','Configurar AUTO','Solicitudes','Tokens','Tokens de entrada','Tokens de salida','Tokens del proyecto','Decisión real','Decisión aún no conocida','Preferencia configurada','Orquestador configurado','Candidato configurado','Pendiente de ejecución del turno','Último turno completado'],
  fr:['Sélection automatique du modèle','Sélection','Modèle fixe','AUTO','Modèles autorisés','Orchestrateur','Aucun','Utilisation du cloud','Ne pas autoriser','Autoriser les données sélectionnées','Données autorisées dans le cloud','Données publiques','Contenu privé du chat','Fichiers du projet','Contenu de navigation','Requêtes par minute','Tokens par minute','Requêtes simultanées','Tokens de sortie par requête','USD par minute (facultatif)','Enregistrer la règle','Actualiser','Exécution disponible','Exécution indisponible','Inconnu','Observation ancienne','Observé','Restants','Limite','Réinitialisation','Action requise sur le compte','Choisissez au moins un modèle réel','Seuls les modèles et données sélectionnés sont autorisés. Les permissions des outils restent distinctes.','Connectez et associez explicitement ces fournisseurs dans l’assistant du Space.','La connexion ou la règle a changé. Actualisez avant de réessayer.','Cet hôte n’a pas encore confirmé l’exécution AUTO isolée et la gouvernance nécessaire.','Configurer AUTO','Requêtes','Tokens','Tokens d’entrée','Tokens de sortie','Tokens du projet','Décision réelle','Décision pas encore connue','Préférence configurée','Orchestrateur configuré','Candidat configuré','En attente de l’exécution du tour','Dernier tour terminé'],
  it:['Selezione automatica del modello','Selezione','Modello fisso','AUTO','Modelli consentiti','Orchestratore','Nessuno','Uso del cloud','Non consentire','Consenti i dati selezionati','Dati consentiti nel cloud','Dati pubblici','Contenuto privato della chat','File del progetto','Contenuto di navigazione','Richieste al minuto','Token al minuto','Richieste simultanee','Token di output per richiesta','USD al minuto (facoltativo)','Salva criteri','Aggiorna','Esecuzione disponibile','Esecuzione non disponibile','Sconosciuto','Osservazione precedente','Osservato','Rimanenti','Limite','Ripristino','È richiesta un’azione sull’account','Scegli almeno un modello effettivo','Sono consentiti solo i modelli e i dati selezionati. I permessi degli strumenti restano separati.','Collega e associa esplicitamente questi provider nell’assistente dello Space.','La connessione o i criteri sono cambiati. Aggiorna prima di riprovare.','Questo host non ha ancora confermato l’esecuzione AUTO isolata e la governance richiesta.','Configura AUTO','Richieste','Token','Token di input','Token di output','Token del progetto','Decisione effettiva','Decisione non ancora nota','Preferenza configurata','Orchestratore configurato','Candidato configurato','In attesa dell’esecuzione del turno','Ultimo turno completato'],
  'pt-BR':['Seleção automática de modelo','Seleção','Modelo fixed','AUTO','Modelos permitidos','Orquestador','Nenhum','Uso da nuvem','Não permitir','Permitir dados selecionados','Dados permitidos na nuvem','Dados públicos','Conteúdo privado do chat','Arquivos do projeto','Conteúdo de navegação','Solicitações por minuto','Tokens por minuto','Solicitações simultâneas','Tokens de saída por solicitação','USD por minuto (opcional)','Salvar política','Atualizar','Execução disponível','Execução indisponível','Desconhecido','Observação desatualizada','Observado','Restantes','Limite','Redefinição','Ação necessária na conta','Escolha ao menos um modelo real','Somente os modelos e dados selecionados são permitidos. As permissões das ferramentas são separadas.','Conecte e vincule explicitamente estes provedores no assistente do Space.','A conexão ou a política mudou. Atualize antes de tentar novamente.','Este host ainda não confirmou a execução AUTO isolada e a governança necessária.','Configurar AUTO','Solicitações','Tokens','Tokens de entrada','Tokens de saída','Tokens do projeto','Decisão real','Decisão ainda não conhecida','Preferência configurada','Orquestador configurado','Candidato configurado','Aguardando execução do turno','Último turno concluído'],
  ru:['Автоматический выбор модели','Выбор','Фиксированная модель','AUTO','Разрешённые модели','Оркестратор','Нет','Использование облака','Не разрешать','Разрешить выбранные данные','Данные, разрешённые в облаке','Открытые данные','Личное содержимое чата','Файлы проекта','Содержимое браузера','Запросы в минуту','Токены в минуту','Одновременные запросы','Выходные токены на запрос','USD в минуту (необязательно)','Сохранить правила','Обновить','Выполнение доступно','Выполнение недоступно','Неизвестно','Устаревшее наблюдение','Время наблюдения','Осталось','Лимит','Сброс','Требуется действие в аккаунте','Выберите хотя бы одну реальную модель','Разрешены только выбранные модели и данные. Права инструментов задаются отдельно.','Сначала подключите и явно привяжите этих провайдеров в помощнике Space.','Подключение или правила изменились. Обновите перед повторной попыткой.','Этот компьютер ещё не подтвердил изолированное выполнение AUTO и необходимые правила управления.','Настроить AUTO','Запросы','Токены','Входные токены','Выходные токены','Токены проекта','Фактическое решение','Решение ещё не известно','Настроенное предпочтение','Настроенный оркестратор','Настроенный кандидат','Ожидает выполнения хода','Последний завершённый ход'],
  ja:['モデルの自動選択','選択方式','固定モデル','AUTO','使用を許可するモデル','オーケストレーター','なし','クラウドの使用','許可しない','選択したデータのみ許可','クラウドへ送信できるデータ','公開データ','チャットの非公開内容','ワークスペースのファイル','ブラウザーの内容','1分あたりのリクエスト数','1分あたりのトークン数','同時リクエスト数','リクエストごとの出力トークン数','1分あたりのUSD（任意）','設定を保存','更新','実行可能','実行できません','不明','古い観測データ','観測日時','残り','上限','リセット','アカウントでの操作が必要','実際のモデルを1つ以上選択してください','選択したモデルとデータだけを許可します。ツールの実行権限は別に設定します。','先にSpaceアシスタントでプロバイダーを接続し、明示的に関連付けてください。','接続または設定が変更されました。更新してから再試行してください。','このホストでは隔離されたAUTO実行と必要なガバナンスがまだ確認されていません。','AUTOを設定','リクエスト','トークン','入力トークン','出力トークン','プロジェクトのトークン','実際の決定','決定はまだ不明です','設定された優先設定','設定されたオーケストレーター','設定された候補','ターンの実行待ち','最後に完了したターン'],
};
export function modelPolicyCopy(locale:DesktopLocaleId):Copy {
  const row=rows[locale];return Object.fromEntries(keys.map((key,index)=>[key,row[index]])) as Copy;
}
export function modelPolicyReason(locale:DesktopLocaleId,code?:string):string {
  const copy=modelPolicyCopy(locale);
  if(code==='auto_provider_binding_required'||code==='scope_connection_adapter_required')return copy.bindingRequired;
  if(code==='provider_connection_changed'||code==='model_policy_revision_conflict')return copy.changed;
  if(code==='native_auto_execution_adapter_required'||code==='auto_managed_authorizer_required')return copy.executionRequired;
  return copy.unavailable;
}
