import type { DesktopLocaleId } from './keys.js';

type Copy=Readonly<{title:string;view:string;takeover:string;refresh:string;close:string;busy:string;paused:string;effect:string;stale:string;unavailable:string;changed:string;unknown:string;retry:string;preview:string}>;
export const nativeChatBrowserCopy:Record<DesktopLocaleId,Copy>={
  en:{title:'Working chat browser',view:'View browser',takeover:'Take over browser',refresh:'Refresh preview',close:'Close preview',busy:'Reading actual browser status…',paused:'Browser automation is paused.',effect:'Taking over pauses browser actions only. The working chat continues. Turn end, Stop or revoked access closes this browser.',stale:'The current chat or browser status is no longer confirmed. Refresh before acting.',unavailable:'This working chat has no available browser target.',changed:'Browser ownership or permissions changed. Refresh the actual status.',unknown:'The takeover result is unknown. Retry the same request to check it.',retry:'Retry takeover request',preview:'Actual working chat browser preview'},
  de:{title:'Browser des Arbeitschats',view:'Browser ansehen',takeover:'Browser übernehmen',refresh:'Vorschau aktualisieren',close:'Vorschau schließen',busy:'Tatsächlicher Browserstatus wird gelesen…',paused:'Automatische Browseraktionen sind angehalten.',effect:'Übernehmen hält nur Browseraktionen an. Der Arbeitschat läuft weiter. Turnende, Stop oder Rechteentzug schließen diesen Browser.',stale:'Der aktuelle Chat- oder Browserstatus ist nicht mehr bestätigt. Aktualisiere ihn vor einer Aktion.',unavailable:'Dieser Arbeitschat hat kein verfügbares Browserziel.',changed:'Browserbesitz oder Freigaben haben sich geändert. Aktualisiere den tatsächlichen Status.',unknown:'Das Ergebnis der Übernahme ist unbekannt. Prüfe es mit derselben Anfrage erneut.',retry:'Übernahmeanfrage erneut prüfen',preview:'Tatsächliche Browservorschau des Arbeitschats'},
  es:{title:'Navegador del chat de trabajo',view:'Ver navegador',takeover:'Tomar control del navegador',refresh:'Actualizar vista previa',close:'Cerrar vista previa',busy:'Consultando el estado real del navegador…',paused:'Las acciones automáticas del navegador están pausadas.',effect:'Tomar control pausa solo las acciones del navegador. El chat continúa. El fin del turno, Detener o revocar el acceso cierra este navegador.',stale:'El estado actual del chat o navegador ya no está confirmado. Actualízalo antes de actuar.',unavailable:'Este chat de trabajo no tiene un navegador disponible.',changed:'Cambió el propietario del navegador o los permisos. Actualiza el estado real.',unknown:'Se desconoce el resultado de la toma de control. Compruébalo repitiendo la misma solicitud.',retry:'Reintentar solicitud de control',preview:'Vista previa real del navegador del chat'},
  fr:{title:'Navigateur du chat de travail',view:'Voir le navigateur',takeover:'Prendre le contrôle',refresh:'Actualiser l’aperçu',close:'Fermer l’aperçu',busy:'Lecture de l’état réel du navigateur…',paused:'Les actions automatiques du navigateur sont en pause.',effect:'La prise de contrôle suspend uniquement les actions du navigateur. Le chat continue. La fin du tour, Arrêter ou la révocation de l’accès ferme ce navigateur.',stale:'L’état actuel du chat ou du navigateur n’est plus confirmé. Actualisez-le avant toute action.',unavailable:'Ce chat de travail ne dispose d’aucun navigateur accessible.',changed:'Le propriétaire du navigateur ou les autorisations ont changé. Actualisez l’état réel.',unknown:'Le résultat de la prise de contrôle est inconnu. Vérifiez-le en répétant la même demande.',retry:'Réessayer la demande de contrôle',preview:'Aperçu réel du navigateur du chat'},
  it:{title:'Browser della chat di lavoro',view:'Visualizza browser',takeover:'Prendi il controllo',refresh:'Aggiorna anteprima',close:'Chiudi anteprima',busy:'Lettura dello stato reale del browser…',paused:'Le azioni automatiche del browser sono in pausa.',effect:'Il controllo sospende solo le azioni del browser. La chat continua. Fine turno, Stop o revoca dell’accesso chiudono questo browser.',stale:'Lo stato attuale della chat o del browser non è più confermato. Aggiornalo prima di agire.',unavailable:'Questa chat di lavoro non ha un browser disponibile.',changed:'Il proprietario del browser o i permessi sono cambiati. Aggiorna lo stato reale.',unknown:'L’esito del controllo è sconosciuto. Verificalo ripetendo la stessa richiesta.',retry:'Riprova la richiesta di controllo',preview:'Anteprima reale del browser della chat'},
  'pt-BR':{title:'Navegador do chat de trabalho',view:'Ver navegador',takeover:'Assumir controle do navegador',refresh:'Atualizar prévia',close:'Fechar prévia',busy:'Lendo o estado real do navegador…',paused:'As ações automáticas do navegador estão pausadas.',effect:'Assumir o controle pausa apenas as ações do navegador. O chat continua. O fim do turno, Parar ou revogar o acesso fecha este navegador.',stale:'O estado atual do chat ou navegador não está mais confirmado. Atualize antes de agir.',unavailable:'Este chat de trabalho não tem um navegador disponível.',changed:'O responsável pelo navegador ou as permissões mudaram. Atualize o estado real.',unknown:'O resultado da transferência é desconhecido. Confira repetindo a mesma solicitação.',retry:'Repetir solicitação de controle',preview:'Prévia real do navegador do chat'},
  ru:{title:'Браузер рабочего чата',view:'Просмотреть браузер',takeover:'Взять управление',refresh:'Обновить просмотр',close:'Закрыть просмотр',busy:'Чтение фактического состояния браузера…',paused:'Автоматические действия браузера приостановлены.',effect:'Перехват приостанавливает только действия браузера. Чат продолжает работу. Завершение хода, остановка или отзыв доступа закрывают этот браузер.',stale:'Текущее состояние чата или браузера больше не подтверждено. Обновите его перед действием.',unavailable:'Для этого рабочего чата нет доступного браузера.',changed:'Владелец браузера или разрешения изменились. Обновите фактическое состояние.',unknown:'Результат перехвата неизвестен. Проверьте его повтором того же запроса.',retry:'Повторить запрос управления',preview:'Фактический просмотр браузера рабочего чата'},
  ja:{title:'作業チャットのブラウザー',view:'ブラウザーを見る',takeover:'ブラウザーを引き継ぐ',refresh:'プレビューを更新',close:'プレビューを閉じる',busy:'実際のブラウザー状態を確認中…',paused:'ブラウザーの自動操作は一時停止しています。',effect:'引き継ぐとブラウザー操作だけが停止し、作業チャットは続行します。ターン終了、停止、または権限の取り消しでこのブラウザーは閉じられます。',stale:'現在のチャットまたはブラウザー状態を確認できません。操作前に更新してください。',unavailable:'この作業チャットには利用可能なブラウザーがありません。',changed:'ブラウザーの所有者または権限が変わりました。実際の状態を更新してください。',unknown:'引き継ぎの結果が不明です。同じリクエストで再確認してください。',retry:'引き継ぎリクエストを再確認',preview:'作業チャットの実際のブラウザープレビュー'},
};
