import type { DesktopLocaleId } from './keys.js';
const keys=['title','explain','review','migrate','retry','unknown','conflict','success','unavailable','changed','busy','original','revision','namespace','target'] as const;
const rows:Record<DesktopLocaleId,readonly string[]>={
 en:['Saved goal migration','This paused goal is stored in an older workspace namespace. Review it before copying it to this chat’s bound Space. The original is preserved and no work resumes automatically.','Review original goal','Confirm migration','Retry the same migration','The outcome is unconfirmed. Retry the same request; do not start a second migration.','The target already contains a goal. It will not be overwritten.','Migration confirmed. Refreshing the actual goal; it remains paused.','Migration could not be confirmed. Review the actual state and retry.','The goal, chat or binding changed. Review the actual state again.','A writer, process or continuation is still active. Wait until it has stopped.','Original paused goal','Revision','Source namespace','Target namespace'],
 de:['Gespeichertes Ziel migrieren','Dieses pausierte Ziel liegt in einem alten Arbeitsbereich-Namensraum. Prüfe es vor dem Kopieren in den gebundenen Space dieses Chats. Das Original bleibt erhalten; die Arbeit wird nicht automatisch fortgesetzt.','Originalziel prüfen','Migration bestätigen','Dieselbe Migration erneut versuchen','Das Ergebnis ist unbestätigt. Wiederhole dieselbe Anfrage; starte keine zweite Migration.','Am Zielort ist bereits ein Ziel vorhanden. Es wird nicht überschrieben.','Migration bestätigt. Der tatsächliche Zielzustand wird geladen; das Ziel bleibt pausiert.','Die Migration konnte nicht bestätigt werden. Prüfe den tatsächlichen Zustand und versuche es erneut.','Ziel, Chat oder Bindung wurden verändert. Prüfe den tatsächlichen Zustand erneut.','Ein Writer, Prozess oder eine Fortsetzung ist noch aktiv. Warte bis zum Stillstand.','Originales pausiertes Ziel','Revision','Quellnamensraum','Zielnamensraum'],
 es:['Migrar objetivo guardado','Este objetivo pausado está en un espacio de trabajo antiguo. Revísalo antes de copiarlo al Space vinculado al chat. El original se conserva y el trabajo no se reanuda automáticamente.','Revisar objetivo original','Confirmar migración','Reintentar la misma migración','El resultado no está confirmado. Repite la misma solicitud; no inicies otra migración.','El destino ya contiene un objetivo. No se sobrescribirá.','Migración confirmada. Se actualiza el estado real; el objetivo sigue pausado.','No se pudo confirmar la migración. Revisa el estado real y reintenta.','El objetivo, el chat o el vínculo cambió. Revisa de nuevo el estado real.','Un proceso, una escritura o una continuación sigue activa. Espera a que termine.','Objetivo original pausado','Revisión','Espacio de nombres de origen','Espacio de nombres de destino'],
 fr:['Migrer l’objectif enregistré','Cet objectif en pause utilise un ancien espace de travail. Vérifiez-le avant de le copier dans le Space lié à ce chat. L’original est conservé et le travail ne reprend pas automatiquement.','Vérifier l’objectif original','Confirmer la migration','Réessayer la même migration','Le résultat n’est pas confirmé. Réessayez la même demande sans lancer une seconde migration.','La destination contient déjà un objectif. Il ne sera pas remplacé.','Migration confirmée. Actualisation de l’état réel ; l’objectif reste en pause.','La migration n’a pas été confirmée. Vérifiez l’état réel et réessayez.','L’objectif, le chat ou le lien a changé. Vérifiez à nouveau l’état réel.','Une écriture, un processus ou une continuation est encore actif. Attendez son arrêt.','Objectif original en pause','Révision','Espace de noms source','Espace de noms cible'],
 it:['Migrare l’obiettivo salvato','Questo obiettivo in pausa usa un vecchio spazio di lavoro. Controllalo prima di copiarlo nello Space associato alla chat. L’originale resta intatto e il lavoro non riprende automaticamente.','Controlla obiettivo originale','Conferma migrazione','Riprova la stessa migrazione','L’esito non è confermato. Ripeti la stessa richiesta senza avviare una seconda migrazione.','La destinazione contiene già un obiettivo. Non verrà sovrascritto.','Migrazione confermata. Aggiornamento dello stato reale; l’obiettivo resta in pausa.','Migrazione non confermata. Controlla lo stato reale e riprova.','L’obiettivo, la chat o il collegamento è cambiato. Controlla di nuovo lo stato reale.','Una scrittura, un processo o una continuazione è ancora attivo. Attendi l’arresto.','Obiettivo originale in pausa','Revisione','Spazio dei nomi di origine','Spazio dei nomi di destinazione'],
 'pt-BR':['Migrar objetivo salvo','Este objetivo pausado usa um espaço de trabalho antigo. Revise antes de copiar para o Space vinculado ao chat. O original será preservado e o trabalho não retomará automaticamente.','Revisar objetivo original','Confirmar migração','Repetir a mesma migração','O resultado não foi confirmado. Repita a mesma solicitação sem iniciar outra migração.','O destino já contém um objetivo. Ele não será substituído.','Migração confirmada. Atualizando o estado real; o objetivo continua pausado.','Não foi possível confirmar a migração. Revise o estado real e tente novamente.','O objetivo, o chat ou o vínculo mudou. Revise o estado real novamente.','Uma gravação, um processo ou uma continuação ainda está ativa. Aguarde a parada.','Objetivo original pausado','Revisão','Namespace de origem','Namespace de destino'],
 ru:['Перенести сохранённую цель','Эта приостановленная цель хранится в старом рабочем пространстве. Проверьте её перед копированием в Space этого чата. Исходная цель сохраняется, работа не возобновляется автоматически.','Проверить исходную цель','Подтвердить перенос','Повторить тот же перенос','Результат не подтверждён. Повторите тот же запрос, не начинайте второй перенос.','В целевом пространстве уже есть цель. Она не будет перезаписана.','Перенос подтверждён. Обновляется фактическое состояние; цель остаётся на паузе.','Перенос не подтверждён. Проверьте фактическое состояние и повторите запрос.','Цель, чат или привязка изменились. Снова проверьте фактическое состояние.','Запись, процесс или продолжение ещё активно. Дождитесь остановки.','Исходная цель на паузе','Ревизия','Исходное пространство имён','Целевое пространство имён'],
 ja:['保存した目標を移行','この一時停止中の目標は以前のワークスペースに保存されています。内容を確認してから、このチャットのSpaceへコピーしてください。元の目標は保持され、作業は自動で再開されません。','元の目標を確認','移行を確認して実行','同じ移行を再試行','結果を確認できませんでした。同じ要求を再試行し、新しい移行を開始しないでください。','移行先にはすでに目標があります。上書きはしません。','移行を確認しました。実際の状態を更新します。目標は一時停止のままです。','移行を確認できませんでした。実際の状態を確認して再試行してください。','目標、チャット、または関連付けが変更されました。実際の状態をもう一度確認してください。','書き込み、プロセス、または継続処理がまだ動作中です。停止するまでお待ちください。','元の一時停止中の目標','リビジョン','移行元の名前空間','移行先の名前空間'],
};
export const nativeGoalMigrationCopy=(locale:DesktopLocaleId)=>Object.fromEntries(keys.map((key,index)=>[key,rows[locale][index]])) as Record<typeof keys[number],string>;
