import type { DesktopCatalog, DesktopLocaleId, DesktopTranslationKey } from './keys';
const rows: Partial<Record<DesktopTranslationKey, Record<DesktopLocaleId, string>>> = {
  'settings.panels.providers.activeProvider': { en: 'Active provider', de: 'Aktiver Anbieter', es: 'Proveedor activo', fr: 'Fournisseur actif', it: 'Provider attivo', 'pt-BR': 'Provedor ativo', ru: 'Активный провайдер' },
  'settings.panels.providers.apiKey': { en: 'API key', de: 'API-Schlüssel', es: 'Clave de API', fr: 'Clé API', it: 'Chiave API', 'pt-BR': 'Chave de API', ru: 'Ключ API' },
  'settings.panels.providers.cancel': { en: 'Cancel', de: 'Abbrechen', es: 'Cancelar', fr: 'Annuler', it: 'Annulla', 'pt-BR': 'Cancelar', ru: 'Отмена' },
  'settings.panels.providers.codexExpired': { en: 'The sign-in code expired. Start Connect again.', de: 'Der Anmeldecode ist abgelaufen. Starte die Verbindung erneut.', es: 'El código de inicio de sesión caducó. Inicia la conexión de nuevo.', fr: 'Le code de connexion a expiré. Relancez la connexion.', it: 'Il codice di accesso è scaduto. Avvia di nuovo la connessione.', 'pt-BR': 'O código de login expirou. Inicie a conexão novamente.', ru: 'Срок действия кода входа истёк. Начните подключение снова.' },
  'settings.panels.providers.codexRetrying': { en: 'Connection interrupted; retrying ({error}).', de: 'Verbindung unterbrochen; erneuter Versuch ({error}).', es: 'Conexión interrumpida; reintentando ({error}).', fr: 'Connexion interrompue ; nouvelle tentative ({error}).', it: 'Connessione interrotta; nuovo tentativo ({error}).', 'pt-BR': 'Conexão interrompida; tentando novamente ({error}).', ru: 'Соединение прервано; повторная попытка ({error}).' },
  'settings.panels.providers.codexIncomplete': { en: 'Sign-in did not complete.', de: 'Die Anmeldung wurde nicht abgeschlossen.', es: 'No se completó el inicio de sesión.', fr: 'La connexion n’a pas abouti.', it: 'L’accesso non è stato completato.', 'pt-BR': 'O login não foi concluído.', ru: 'Вход не завершён.' },
  'settings.panels.providers.codexCancelled': { en: 'ChatGPT Codex sign-in cancelled.', de: 'ChatGPT-Codex-Anmeldung abgebrochen.', es: 'Inicio de sesión de ChatGPT Codex cancelado.', fr: 'Connexion à ChatGPT Codex annulée.', it: 'Accesso a ChatGPT Codex annullato.', 'pt-BR': 'Login do ChatGPT Codex cancelado.', ru: 'Вход в ChatGPT Codex отменён.' },
  'settings.panels.providers.configuring': { en: 'Configuring…', de: 'Wird konfiguriert…', es: 'Configurando…', fr: 'Configuration…', it: 'Configurazione…', 'pt-BR': 'Configurando…', ru: 'Настройка…' },
  'settings.panels.providers.connectionError': { en: 'Connection failed', de: 'Verbindung fehlgeschlagen', es: 'Falló la conexión', fr: 'Échec de la connexion', it: 'Connessione non riuscita', 'pt-BR': 'Falha na conexão', ru: 'Не удалось подключиться' },
  'settings.panels.providers.connectionSuccess': { en: 'Connected', de: 'Verbunden', es: 'Conectado', fr: 'Connecté', it: 'Connesso', 'pt-BR': 'Conectado', ru: 'Подключено' },
  'settings.panels.providers.default': { en: 'Default', de: 'Standard', es: 'Predeterminado', fr: 'Par défaut', it: 'Predefinito', 'pt-BR': 'Padrão', ru: 'По умолчанию' },
  'settings.panels.providers.groups': { en: 'Groups', de: 'Gruppen', es: 'Grupos', fr: 'Groupes', it: 'Gruppi', 'pt-BR': 'Grupos', ru: 'Группы' },
  'settings.panels.providers.saveActivate': { en: 'Save and activate', de: 'Speichern und aktivieren', es: 'Guardar y activar', fr: 'Enregistrer et activer', it: 'Salva e attiva', 'pt-BR': 'Salvar e ativar', ru: 'Сохранить и активировать' },
  'settings.panels.providers.openrouterKeyHint': { en: 'Your key is stored locally and sent only to OpenRouter.', de: 'Dein Schlüssel wird lokal gespeichert und nur an OpenRouter gesendet.', es: 'La clave se guarda localmente y solo se envía a OpenRouter.', fr: 'La clé est stockée localement et envoyée uniquement à OpenRouter.', it: 'La chiave viene salvata localmente e inviata solo a OpenRouter.', 'pt-BR': 'A chave é armazenada localmente e enviada apenas ao OpenRouter.', ru: 'Ключ хранится локально и отправляется только в OpenRouter.' },
  'settings.panels.providers.openrouterLoadModels': { en: 'Save key and load models', de: 'Schlüssel speichern und Modelle laden', es: 'Guardar clave y cargar modelos', fr: 'Enregistrer la clé et charger les modèles', it: 'Salva la chiave e carica i modelli', 'pt-BR': 'Salvar chave e carregar modelos', ru: 'Сохранить ключ и загрузить модели' },
  'settings.panels.providers.openrouterRefreshModels': { en: 'Refresh models', de: 'Modelle aktualisieren', es: 'Actualizar modelos', fr: 'Actualiser les modèles', it: 'Aggiorna i modelli', 'pt-BR': 'Atualizar modelos', ru: 'Обновить модели' },
  'settings.panels.providers.openrouterChooseModels': { en: 'Models available in Lastbrowser', de: 'In Lastbrowser verfügbare Modelle', es: 'Modelos disponibles en Lastbrowser', fr: 'Modèles disponibles dans Lastbrowser', it: 'Modelli disponibili in Lastbrowser', 'pt-BR': 'Modelos disponíveis no Lastbrowser', ru: 'Модели, доступные в Lastbrowser' },
  'settings.panels.providers.openrouterNoModels': { en: 'No models were returned. Check the API key and try again.', de: 'Es wurden keine Modelle geliefert. Prüfe den API-Schlüssel und versuche es erneut.', es: 'No se devolvieron modelos. Comprueba la clave y vuelve a intentarlo.', fr: 'Aucun modèle reçu. Vérifiez la clé API et réessayez.', it: 'Nessun modello restituito. Controlla la chiave e riprova.', 'pt-BR': 'Nenhum modelo foi retornado. Confira a chave e tente novamente.', ru: 'Список моделей пуст. Проверьте ключ API и повторите попытку.' },
  'settings.panels.providers.openrouterSelectAtLeastOne': { en: 'Select at least one model.', de: 'Wähle mindestens ein Modell aus.', es: 'Selecciona al menos un modelo.', fr: 'Sélectionnez au moins un modèle.', it: 'Seleziona almeno un modello.', 'pt-BR': 'Selecione pelo menos um modelo.', ru: 'Выберите хотя бы одну модель.' },
  'settings.panels.providers.openrouterKeyRequired': { en: 'Enter an OpenRouter API key before loading or using models.', de: 'Gib vor dem Laden oder Verwenden von Modellen einen OpenRouter-API-Schlüssel ein.', es: 'Introduce una clave API de OpenRouter antes de cargar o usar modelos.', fr: 'Saisissez une clé API OpenRouter avant de charger ou d’utiliser des modèles.', it: 'Inserisci una chiave API OpenRouter prima di caricare o usare modelli.', 'pt-BR': 'Informe uma chave de API do OpenRouter antes de carregar ou usar modelos.', ru: 'Перед загрузкой или использованием моделей введите ключ API OpenRouter.' },
  'settings.panels.providers.openrouterKeyPlaceholder': { en: 'Leave blank to keep the saved key', de: 'Leer lassen, um den gespeicherten Schlüssel zu behalten', es: 'Déjala vacía para conservar la clave guardada', fr: 'Laissez vide pour conserver la clé enregistrée', it: 'Lascia vuoto per mantenere la chiave salvata', 'pt-BR': 'Deixe em branco para manter a chave salva', ru: 'Оставьте пустым, чтобы сохранить текущий ключ' },
  'settings.panels.providers.openrouterUnavailable': { en: 'not currently listed', de: 'derzeit nicht gelistet', es: 'no aparece actualmente', fr: 'non répertorié actuellement', it: 'non elencato al momento', 'pt-BR': 'não listado no momento', ru: 'сейчас не отображается' },
  'settings.panels.providers.betaUntested': { en: 'Beta · untested', de: 'Beta · ungetestet', es: 'Beta · sin probar', fr: 'Bêta · non testé', it: 'Beta · non testato', 'pt-BR': 'Beta · não testado', ru: 'Бета · не проверено' },
  'settings.panels.providers.ollamaCloudLiveVerified': { en: 'Live tested · catalog + chat', de: 'Live geprüft · Katalog + Chat', es: 'Probado en vivo · catálogo + chat', fr: 'Testé en direct · catalogue + chat', it: 'Testato dal vivo · catalogo + chat', 'pt-BR': 'Testado ao vivo · catálogo + chat', ru: 'Проверено вживую · каталог + чат' },
  'settings.panels.providers.ollamaCloudCatalogOnly': { en: 'Catalog verified; chat untested', de: 'Katalog geprüft; Chat ungetestet', es: 'Catálogo verificado; chat sin probar', fr: 'Catalogue vérifié ; chat non testé', it: 'Catalogo verificato; chat non testato', 'pt-BR': 'Catálogo verificado; chat não testado', ru: 'Каталог проверен; чат не тестировался' },
  'settings.panels.providers.openrouterCatalogOnly': { en: 'Catalog HTTP 200 verified; chat untested', de: 'Katalog HTTP 200 geprüft; Chat ungetestet', es: 'Catálogo HTTP 200 verificado; chat sin probar', fr: 'Catalogue HTTP 200 vérifié ; chat non testé', it: 'Catalogo HTTP 200 verificato; chat non testato', 'pt-BR': 'Catálogo HTTP 200 verificado; chat não testado', ru: 'Каталог HTTP 200 проверен; чат не тестировался' },
  'settings.panels.providers.openrouterLiveTested': { en: 'Live chat tested · liquid/lfm-2.5-2.6b:free', de: 'Live-Chat geprüft · liquid/lfm-2.5-2.6b:free', es: 'Chat en vivo probado · liquid/lfm-2.5-2.6b:free', fr: 'Chat en direct testé · liquid/lfm-2.5-2.6b:free', it: 'Chat dal vivo testata · liquid/lfm-2.5-2.6b:free', 'pt-BR': 'Chat ao vivo testado · liquid/lfm-2.5-2.6b:free', ru: 'Чат проверен · liquid/lfm-2.5-2.6b:free' },
  'settings.panels.providers.openrouterChatEvidence': { en: 'Lastbrowser received “OK” from this free route; other catalog models remain untested.', de: 'Lastbrowser erhielt „OK“ über diese kostenlose Route; andere Katalogmodelle bleiben ungetestet.', es: 'Lastbrowser recibió “OK” de esta ruta gratuita; los demás modelos del catálogo siguen sin probar.', fr: 'Lastbrowser a reçu « OK » via cette route gratuite ; les autres modèles du catalogue restent non testés.', it: 'Lastbrowser ha ricevuto “OK” da questa route gratuita; gli altri modelli del catalogo restano non testati.', 'pt-BR': 'Lastbrowser recebeu “OK” por esta rota gratuita; os demais modelos do catálogo continuam sem teste.', ru: 'Lastbrowser получил «OK» через этот бесплатный маршрут; остальные модели каталога не проверялись.' },
  'settings.panels.providers.antigravityQuotaOnly': { en: 'OAuth and onboarding reached Antigravity, but inference returned a quota response; no successful chat yet.', de: 'OAuth und Onboarding erreichten Antigravity, aber die Inferenz meldete ein ausgeschöpftes Kontingent; ein erfolgreicher Chat steht noch aus.', es: 'OAuth y la incorporación llegaron a Antigravity, pero la inferencia respondió con una cuota agotada; aún no hay un chat exitoso.', fr: 'OAuth et l’initialisation ont atteint Antigravity, mais l’inférence a renvoyé une réponse de quota épuisé ; aucun chat réussi pour le moment.', it: 'OAuth e onboarding hanno raggiunto Antigravity, ma l’inferenza ha restituito una risposta di quota esaurita; nessuna chat riuscita finora.', 'pt-BR': 'OAuth e integração chegaram ao Antigravity, mas a inferência retornou uma resposta de cota esgotada; ainda não houve um chat bem-sucedido.', ru: 'OAuth и настройка достигли Antigravity, но инференс вернул ответ об исчерпанной квоте; успешного чата пока нет.' },
  'settings.panels.providers.morphTokenLimitWarning': { en: 'Live API probe returned 16,384 tokens despite max_tokens=32; Lastbrowser chat unverified', de: 'Live-API-Test lieferte 16.384 Tokens trotz max_tokens=32; Lastbrowser-Chat ungetestet', es: 'La prueba en vivo devolvió 16.384 tokens pese a max_tokens=32; chat de Lastbrowser sin verificar', fr: 'Le test en direct a renvoyé 16 384 tokens malgré max_tokens=32 ; chat Lastbrowser non vérifié', it: 'Il test dal vivo ha restituito 16.384 token nonostante max_tokens=32; chat Lastbrowser non verificata', 'pt-BR': 'O teste ao vivo retornou 16.384 tokens apesar de max_tokens=32; chat do Lastbrowser não verificado', ru: 'Проверка API вернула 16 384 токена при max_tokens=32; чат Lastbrowser не проверен' }
};
export const settingsProviderTranslations: Record<DesktopLocaleId, DesktopCatalog> = Object.fromEntries(
  (['en', 'de', 'it', 'es', 'fr', 'pt-BR', 'ru'] as DesktopLocaleId[]).map((locale) => [locale, Object.fromEntries(Object.entries(rows).map(([key, translations]) => [key, translations[locale]]))])
) as Record<DesktopLocaleId, DesktopCatalog>;
