import type { DesktopCatalog, LegacyDesktopLocaleId as DesktopLocaleId, DesktopTranslationKey } from './keys.js';

const rows: Partial<Record<DesktopTranslationKey, Record<DesktopLocaleId, string>>> = {
  'spaceSetup.title': { en: 'Set up a new Space', de: 'Neuen Space einrichten', es: 'Configurar un espacio nuevo', fr: 'Configurer un nouvel espace', it: 'Configura un nuovo spazio', 'pt-BR': 'Configurar um novo espaço', ru: 'Настройка нового пространства' },
  'spaceSetup.subtitle': { en: 'A structured workspace with its own profile, AI model, and apps', de: 'Ein strukturierter Arbeitsbereich mit eigenem Profil, KI-Modell und Apps', es: 'Un espacio de trabajo organizado con perfil, modelo de IA y aplicaciones propios', fr: 'Un espace de travail structuré avec son propre profil, modèle d’IA et applications', it: 'Uno spazio di lavoro strutturato con profilo, modello IA e app dedicati', 'pt-BR': 'Um espaço de trabalho organizado com perfil, modelo de IA e aplicativos próprios', ru: 'Организованное рабочее пространство со своим профилем, моделью ИИ и приложениями' },
  'spaceSetup.stepTemplate': { en: '1. Template & basics', de: '1. Vorlage & Basis', es: '1. Plantilla y datos básicos', fr: '1. Modèle et informations', it: '1. Modello e dati di base', 'pt-BR': '1. Modelo e informações básicas', ru: '1. Шаблон и основные данные' },
  'spaceSetup.stepModel': { en: '2. AI model', de: '2. KI-Modell', es: '2. Modelo de IA', fr: '2. Modèle d’IA', it: '2. Modello IA', 'pt-BR': '2. Modelo de IA', ru: '2. Модель ИИ' },
  'spaceSetup.stepApps': { en: '3. Web apps & start page', de: '3. Web-Apps & Start', es: '3. Aplicaciones web e inicio', fr: '3. Applications web et page de démarrage', it: '3. App web e pagina iniziale', 'pt-BR': '3. Aplicativos web e página inicial', ru: '3. Веб-приложения и стартовая страница' },
  'spaceSetup.chooseTemplate': { en: 'Choose a template', de: 'Wähle eine Vorlage', es: 'Elige una plantilla', fr: 'Choisissez un modèle', it: 'Scegli un modello', 'pt-BR': 'Escolha um modelo', ru: 'Выберите шаблон' },
  'spaceSetup.preset.coding': { en: 'Coding & development', de: 'Coding & Dev', es: 'Programación y desarrollo', fr: 'Programmation et développement', it: 'Programmazione e sviluppo', 'pt-BR': 'Programação e desenvolvimento', ru: 'Разработка и программирование' },
  'spaceSetup.preset.codingDescription': { en: 'Optimized for software development, Git workflows, and documentation.', de: 'Optimiert für Software-Entwicklung, Git-Workflows und Dokumentation.', es: 'Optimizado para desarrollo de software, flujos de trabajo de Git y documentación.', fr: 'Optimisé pour le développement logiciel, les workflows Git et la documentation.', it: 'Ottimizzato per lo sviluppo software, i flussi Git e la documentazione.', 'pt-BR': 'Otimizado para desenvolvimento de software, fluxos de trabalho do Git e documentação.', ru: 'Оптимизировано для разработки ПО, работы с Git и документации.' },
  'spaceSetup.preset.research': { en: 'Research & writing', de: 'Recherche & Schreiben', es: 'Investigación y escritura', fr: 'Recherche et rédaction', it: 'Ricerca e scrittura', 'pt-BR': 'Pesquisa e escrita', ru: 'Исследования и тексты' },
  'spaceSetup.preset.researchDescription': { en: 'For research, papers, notes, and deep thinking.', de: 'Ideal für Recherche, Paper, Notizen und Deep Thinking.', es: 'Ideal para investigar, redactar artículos, tomar notas y profundizar.', fr: 'Pour la recherche, les articles, les notes et la réflexion approfondie.', it: 'Per ricerche, articoli, appunti e analisi approfondite.', 'pt-BR': 'Ideal para pesquisas, artigos, anotações e análises aprofundadas.', ru: 'Для исследований, статей, заметок и вдумчивой работы.' },
  'spaceSetup.preset.media': { en: 'Media & design', de: 'Medien & Design', es: 'Medios y diseño', fr: 'Médias et design', it: 'Media e design', 'pt-BR': 'Mídia e design', ru: 'Медиа и дизайн' },
  'spaceSetup.preset.mediaDescription': { en: 'For inspiration, UI/UX design, video, and content creation.', de: 'Für Inspiration, UI/UX-Design, Video und Content Creation.', es: 'Para inspiración, diseño UI/UX, vídeo y creación de contenido.', fr: 'Pour l’inspiration, le design UI/UX, la vidéo et la création de contenu.', it: 'Per ispirazione, design UI/UX, video e creazione di contenuti.', 'pt-BR': 'Para inspiração, design UI/UX, vídeos e criação de conteúdo.', ru: 'Для вдохновения, UI/UX-дизайна, видео и создания контента.' },
  'spaceSetup.preset.blank': { en: 'Blank Space', de: 'Freier Space (Blank)', es: 'Espacio en blanco', fr: 'Espace vierge', it: 'Spazio vuoto', 'pt-BR': 'Espaço em branco', ru: 'Пустое пространство' },
  'spaceSetup.preset.blankDescription': { en: 'A blank workspace for your own routines.', de: 'Vollkommen leerer Arbeitsbereich für deine eigenen Routinen.', es: 'Un espacio vacío para tus propias rutinas.', fr: 'Un espace vierge pour vos propres habitudes.', it: 'Uno spazio vuoto per le tue routine.', 'pt-BR': 'Um espaço em branco para suas próprias rotinas.', ru: 'Пустое рабочее пространство для ваших задач.' },
  'spaceSetup.name': { en: 'Space name', de: 'Name des Space', es: 'Nombre del espacio', fr: 'Nom de l’espace', it: 'Nome dello spazio', 'pt-BR': 'Nome do espaço', ru: 'Название пространства' },
  'spaceSetup.namePlaceholder': { en: 'e.g. Coding & development', de: 'z. B. Coding & Dev', es: 'p. ej., Programación', fr: 'Ex. : développement', it: 'Es. Programmazione', 'pt-BR': 'Ex.: Programação', ru: 'Например: Разработка' },
  'spaceSetup.duplicateName': { en: 'A Space with this name already exists.', de: 'Ein Space mit diesem Namen existiert bereits.', es: 'Ya existe un espacio con este nombre.', fr: 'Un espace portant ce nom existe déjà.', it: 'Esiste già uno spazio con questo nome.', 'pt-BR': 'Já existe um espaço com esse nome.', ru: 'Пространство с таким названием уже существует.' },
  'spaceSetup.colorAccent': { en: 'Accent color', de: 'Farb-Akzent', es: 'Color de énfasis', fr: 'Couleur d’accentuation', it: 'Colore in evidenza', 'pt-BR': 'Cor de destaque', ru: 'Цветовой акцент' },
  'spaceSetup.colorSwatch': { en: 'Color {color}', de: 'Farbe {color}', es: 'Color {color}', fr: 'Couleur {color}', it: 'Colore {color}', 'pt-BR': 'Cor {color}', ru: 'Цвет {color}' },
  'spaceSetup.pathOptional': { en: 'Storage path (optional)', de: 'Speicherort / Pfad (Optional)', es: 'Ruta de almacenamiento (opcional)', fr: 'Chemin de stockage (facultatif)', it: 'Percorso di archiviazione (facoltativo)', 'pt-BR': 'Caminho de armazenamento (opcional)', ru: 'Путь хранения (необязательно)' },
  'spaceSetup.pathHint': { en: 'By default, this Space is isolated under ~/.sidekick/{path}.', de: 'Wird standardmäßig in ~/.sidekick/{path} isoliert.', es: 'De forma predeterminada, este espacio se aísla en ~/.sidekick/{path}.', fr: 'Par défaut, cet espace est isolé dans ~/.sidekick/{path}.', it: 'Per impostazione predefinita, questo spazio è isolato in ~/.sidekick/{path}.', 'pt-BR': 'Por padrão, este espaço fica isolado em ~/.sidekick/{path}.', ru: 'По умолчанию пространство изолируется в ~/.sidekick/{path}.' },
  'spaceSetup.modelLabel': { en: 'Default AI for this Space', de: 'Standard-KI für diesen Space', es: 'IA predeterminada para este espacio', fr: 'IA par défaut pour cet espace', it: 'IA predefinita per questo spazio', 'pt-BR': 'IA padrão para este espaço', ru: 'Модель ИИ по умолчанию для пространства' },
  'spaceSetup.modelDescription': { en: 'Each Space can use a preferred model or routing mode. Chat starts in this mode automatically.', de: 'Jeder Space kann ein bevorzugtes Modell oder Routing nutzen. Der Chat startet automatisch in diesem Modus.', es: 'Cada espacio puede usar un modelo o modo de enrutamiento preferido. El chat lo usará automáticamente.', fr: 'Chaque espace peut utiliser un modèle ou un routage préféré. Le chat démarrera automatiquement dans ce mode.', it: 'Ogni spazio può usare un modello o un routing preferito. La chat partirà automaticamente in questa modalità.', 'pt-BR': 'Cada espaço pode usar um modelo ou modo de roteamento preferido. O chat iniciará nesse modo automaticamente.', ru: 'Для каждого пространства можно выбрать модель или режим маршрутизации. Чат автоматически запустится в этом режиме.' },
  'spaceSetup.model.smartTrack': { en: 'Smart Track Auto-Router (Recommended)', de: 'Smart Track Auto-Router (Empfohlen)', es: 'Enrutador automático Smart Track (recomendado)', fr: 'Routage automatique Smart Track (recommandé)', it: 'Instradamento automatico Smart Track (consigliato)', 'pt-BR': 'Roteador automático Smart Track (recomendado)', ru: 'Автомаршрутизация Smart Track (рекомендуется)' },
  'spaceSetup.model.smartTrackDescription': { en: 'Adaptive single-track pipeline with Low, Medium, and High modes.', de: 'Adaptive Single-Track-Pipeline mit dynamischem Modus (Low, Medium, High).', es: 'Flujo adaptativo de una sola vía con niveles Bajo, Medio y Alto.', fr: 'Flux adaptatif à voie unique avec les niveaux Faible, Moyen et Élevé.', it: 'Flusso adattivo a percorso singolo con modalità Bassa, Media e Alta.', 'pt-BR': 'Fluxo adaptativo de faixa única com níveis Baixo, Médio e Alto.', ru: 'Адаптивный однопоточный процесс с уровнями «Низкий», «Средний» и «Высокий».' },
  'spaceSetup.model.adaptive': { en: 'Adaptive', de: 'Adaptiv', es: 'Adaptativo', fr: 'Adaptatif', it: 'Adattivo', 'pt-BR': 'Adaptativo', ru: 'Адаптивный' },
  'spaceSetup.model.teamwork': { en: 'Teamwork mode (multi-agent)', de: 'Teamwork-Modus (Multi-Agent)', es: 'Modo Teamwork (multiagente)', fr: 'Mode Teamwork (multi-agent)', it: 'Modalità Teamwork (multi-agente)', 'pt-BR': 'Modo Teamwork (multiagente)', ru: 'Режим Teamwork (несколько агентов)' },
  'spaceSetup.model.teamworkDescription': { en: 'Parallel subagents coordinated for complex tasks.', de: 'Parallele Subagenten mit Orchestrator für komplexe Großaufgaben.', es: 'Subagentes paralelos coordinados para tareas complejas.', fr: 'Sous-agents parallèles coordonnés pour les tâches complexes.', it: 'Subagenti paralleli coordinati per attività complesse.', 'pt-BR': 'Subagentes paralelos coordenados para tarefas complexas.', ru: 'Параллельные подагенты для сложных задач.' },
  'spaceSetup.model.multiAgent': { en: 'Multi-agent', de: 'Multi-Agent', es: 'Multiagente', fr: 'Multi-agent', it: 'Multi-agente', 'pt-BR': 'Multiagente', ru: 'Несколько агентов' },
  'spaceSetup.model.ollama': { en: 'Ollama Local / Cloud', de: 'Ollama lokal / Cloud', es: 'Ollama local / nube', fr: 'Ollama local / cloud', it: 'Ollama locale / cloud', 'pt-BR': 'Ollama local / nuvem', ru: 'Ollama: локально / в облаке' },
  'spaceSetup.model.ollamaDescription': { en: 'Local or private cloud inference for greater privacy.', de: 'Lokale oder private Cloud-Inferenz für maximale Privatsphäre.', es: 'Inferencia local o en una nube privada para mayor privacidad.', fr: 'Inférence locale ou dans un cloud privé pour plus de confidentialité.', it: 'Inferenza locale o su cloud privato per una maggiore riservatezza.', 'pt-BR': 'Inferência local ou em nuvem privada para mais privacidade.', ru: 'Локальный запуск или частное облако для большей конфиденциальности.' },
  'spaceSetup.model.local': { en: 'Local', de: 'Lokal', es: 'Local', fr: 'Local', it: 'Locale', 'pt-BR': 'Local', ru: 'Локально' },
  'spaceSetup.model.availableVia': { en: 'Available through {provider}.', de: 'Verfügbar über {provider}.', es: 'Disponible a través de {provider}.', fr: 'Disponible via {provider}.', it: 'Disponibile tramite {provider}.', 'pt-BR': 'Disponível por meio de {provider}.', ru: 'Доступно через {provider}.' },
  'spaceSetup.appsLabel': { en: 'Pinned web apps', de: 'Angeheftete Web-Apps', es: 'Aplicaciones web ancladas', fr: 'Applications web épinglées', it: 'App web fissate', 'pt-BR': 'Aplicativos web fixados', ru: 'Закреплённые веб-приложения' },
  'spaceSetup.appsDescription': { en: 'Choose the default web apps to pin in this Space sidebar:', de: 'Wähle die Standard-Webapps, die in der Seitenleiste dieses Space angeheftet werden sollen:', es: 'Elige las aplicaciones web predeterminadas que quieres anclar en la barra lateral:', fr: 'Choisissez les applications web à épingler par défaut dans la barre latérale :', it: 'Scegli le app web da fissare per impostazione predefinita nella barra laterale:', 'pt-BR': 'Escolha os aplicativos web padrão para fixar na barra lateral deste espaço:', ru: 'Выберите веб-приложения для закрепления на боковой панели пространства:' },
  'spaceSetup.noPresetApps': { en: 'This template has no preset apps. You can add apps from the dock at any time.', de: 'Keine vorausgewählten Apps für diese Vorlage. Du kannst Apps jederzeit über das Dock hinzufügen.', es: 'Esta plantilla no incluye aplicaciones. Puedes añadirlas desde el dock cuando quieras.', fr: 'Aucune application prédéfinie pour ce modèle. Vous pourrez en ajouter depuis le dock à tout moment.', it: 'Questo modello non include app predefinite. Puoi aggiungerle dal dock in qualsiasi momento.', 'pt-BR': 'Este modelo não tem aplicativos predefinidos. Você pode adicioná-los pelo dock quando quiser.', ru: 'В этом шаблоне нет приложений. Их можно добавить через панель в любое время.' },
  'spaceSetup.customAppName': { en: 'Add a custom app', de: 'Eigene App anheften', es: 'Añadir una aplicación personalizada', fr: 'Ajouter une application personnalisée', it: 'Aggiungi un’app personalizzata', 'pt-BR': 'Adicionar aplicativo personalizado', ru: 'Добавить приложение' },
  'spaceSetup.webAddress': { en: 'Web address', de: 'Webadresse', es: 'Dirección web', fr: 'Adresse web', it: 'Indirizzo web', 'pt-BR': 'Endereço web', ru: 'Веб-адрес' },
  'spaceSetup.namePlaceholderCustom': { en: 'Name', de: 'Name', es: 'Nombre', fr: 'Nom', it: 'Nome', 'pt-BR': 'Nome', ru: 'Название' },
  'spaceSetup.urlPlaceholder': { en: 'https://…', de: 'https://…', es: 'https://…', fr: 'https://…', it: 'https://…', 'pt-BR': 'https://…', ru: 'https://…' },
  'spaceSetup.addApp': { en: 'Add app', de: 'App hinzufügen', es: 'Añadir aplicación', fr: 'Ajouter l’application', it: 'Aggiungi app', 'pt-BR': 'Adicionar aplicativo', ru: 'Добавить' },
  'spaceSetup.pinnedApps': { en: 'Pinned: {apps}', de: 'Angeheftet: {apps}', es: 'Ancladas: {apps}', fr: 'Épinglées : {apps}', it: 'Fissate: {apps}', 'pt-BR': 'Fixados: {apps}', ru: 'Закреплено: {apps}' },
  'spaceSetup.startPage': { en: 'Start page', de: 'Start-Webseite beim Öffnen', es: 'Página de inicio', fr: 'Page de démarrage', it: 'Pagina iniziale', 'pt-BR': 'Página inicial', ru: 'Стартовая страница' },
  'spaceSetup.startPagePlaceholder': { en: 'https://…', de: 'https://…', es: 'https://…', fr: 'https://…', it: 'https://…', 'pt-BR': 'https://…', ru: 'https://…' },
  'spaceSetup.submitting': { en: 'Creating Space…', de: 'Space wird erstellt …', es: 'Creando espacio…', fr: 'Création de l’espace…', it: 'Creazione dello spazio…', 'pt-BR': 'Criando espaço…', ru: 'Создание пространства…' },
  'spaceSetup.createAndOpen': { en: 'Create and open Space', de: 'Space erstellen & öffnen', es: 'Crear y abrir espacio', fr: 'Créer et ouvrir l’espace', it: 'Crea e apri lo spazio', 'pt-BR': 'Criar e abrir espaço', ru: 'Создать и открыть пространство' },
  'spaceSetup.createFailed': { en: 'Could not create the Space. Check the storage path and try again.', de: 'Der Space konnte nicht erstellt werden. Bitte prüfe den Speicherort und versuche es erneut.', es: 'No se pudo crear el espacio. Comprueba la ruta de almacenamiento e inténtalo de nuevo.', fr: 'Impossible de créer l’espace. Vérifiez le chemin de stockage et réessayez.', it: 'Impossibile creare lo spazio. Controlla il percorso di archiviazione e riprova.', 'pt-BR': 'Não foi possível criar o espaço. Confira o caminho de armazenamento e tente novamente.', ru: 'Не удалось создать пространство. Проверьте путь хранения и повторите попытку.' }
};

export const spaceSetupTranslations: Record<DesktopLocaleId, DesktopCatalog> = Object.fromEntries(
  (['en', 'de', 'es', 'fr', 'it', 'pt-BR', 'ru'] as DesktopLocaleId[]).map((locale) => [
    locale,
    Object.fromEntries(Object.entries(rows).map(([key, values]) => [key, values?.[locale]]))
  ])
) as Record<DesktopLocaleId, DesktopCatalog>;
